### ISSUE TITLE
Complete dir_create semantics

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#10]
* [x] Work like `file_create()` and silently succeed if directory already exists
* [x] Implement `recursive = TRUE` (and make the default?)

**Comment by jimhester** [comment]
This should now be done including some simple tests.

https://github.com/r-lib/fs/commit/e07f7987cfb20237dbe4a27c4bb9a716760ee78a, https://github.com/r-lib/fs/commit/f3a61c779bb510478de197af5f83937bee43b449, https://github.com/r-lib/fs/commit/621a794cf83bffc03d47673af78d6762a74158cf, https://github.com/r-lib/fs/commit/c0cd363d0c3bad3239d66add431b94db902fbc7e
