### ISSUE TITLE
`move_file` deletes files when `new_path` contains duplicates: Fail would be preferable.

### ISSUE THREAD

**Issue by Plebejer** [r-lib/fs#101]
The description of `file_move()` says that it always fails if it is unable to move a file. This gives the impression that it is a safer version of `file.rename()`.

However, when you pass a character vector containing duplicates as `new_path`, it silently deletes files. To really be a safe function, `file_move()` should check wheter `new_path` contains duplicates. If so, if should fail.

**Comment by jimhester** [comment]
I am not sure I want to do this much input validation, but will leave this open a while longer to consider.
