### ISSUE TITLE
Emulate behaviour of cp when target is directory

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#102]
Any interest in emulating this aspect of cp (second line) in `file_copy()`?

```
cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file target_file
cp [-R [-H | -L | -P]] [-fi | -n] [-apvX] source_file ... target_directory
```

``` r
library(fs)

source_file <- path(R.home("doc"), "THANKS")
target_directory <- dir_create("just_hold_me")
file_copy(source_file, target_directory)
#> Error: [EEXIST] Failed to copy '/Library/Frameworks/R.framework/Resources/doc/THANKS' to 'just_hold_me': file already exists

file_copy(source_file, path(target_directory, path_file(source_file)))
dir_ls(target_directory)
#> just_hold_me/THANKS
```

Created on 2018-04-19 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

What if the first call to `file_copy()` "just worked", i.e. gave the result from the second call? We basically did this in googledrive and it seems nice. But I also had/have some misgivings that it's too helpful.

**Comment by jimhester** [comment]
I agree this should be supported

**Comment by jimhester** [comment]
Ok this should be fixed now
