### ISSUE TITLE
handling errors?

### ISSUE THREAD

**Issue by randomgambit** [r-lib/fs#105]
Hi @jimhester !

Thanks again for this very nice package. I tried to run a little snippet that sorts my folders by size.

```
dir_info("/hpc/myfolder/", recursive = TRUE) %>%
+   group_by(directory = path_dir(path)) %>%
+   tally(wt = size, sort = TRUE)
```

but I get an error (after 10min of processing)

`Error: [EACCES] Failed to search directory '/hpc/myfolder/blabla': permission denied`

Is there a way to avoid these errors with `fs` so that the tabulation can occur?

Thanks!

**Comment by jimhester** [comment]
Not currently, as of now you would need to do the recursion manually and wrap the directory in something like `purrr::safely()`.

**Comment by randomgambit** [comment]
argh... can you be a bit more specific here? I am afraid I am too noob to do that right now :)

**Comment by ThomasThelen** [comment]
Have you tried running the script with elevated privileges? Permission was denied when you attempted to access one of the directories.

**Comment by vnijs** [comment]
My remaining comments https://github.com/r-lib/fs/issues/121 seem directly related to this (open) issue. I installed the `warnings` branch mentioned in the commit but still get an error and no return value. It would be great to have a worked example on how to most efficiently deal with errors like the below with `fs`. In my setting it is possible a lot of files in a directory would need to be scanned and using a loop with `try` and `file_info` will likely be quite slow

> options(fs.should_error = FALSE)
> files <- fs::dir_ls("C:/")
> fs::file_info(files)
 Show Traceback
 
 Rerun with Debug
 Error: [EBUSY] Failed to stat 'C:/hiberfil.sys': resource busy or locked

**Comment by jimhester** [comment]
This should now be fixed by passing `fail = FALSE` to `dir_info()`.

**Comment by randomgambit** [comment]
well done!
