### ISSUE TITLE
Feature Suggestion: resolve "~" to "%UserProfile%"

### ISSUE THREAD

**Issue by jzadra** [r-lib/fs#106]
In OSX, "~" is a path shortcut to the user home directory.  It is useful to get around paths that differ depending on what user is logged in.  Would be great if it would work for PC's too to make paths cross-platform by resolving to %UserProfile%.

**Comment by jimhester** [comment]
Did you try this? This is already the behavior of `path_expand()`.

https://github.com/r-lib/fs/blob/master/NEWS.md#breaking-changes
