### ISSUE TITLE
fs 1.2.2 not tagged / under releases

### ISSUE THREAD

**Issue by HenrikBengtsson** [r-lib/fs#108]
fs 1.2.2 is on CRAN but is neither tagged (https://github.com/r-lib/fs/tags) nor listed under https://github.com/r-lib/fs/releases.

**Comment by jimhester** [comment]
Thanks for catching this! What are you using GitHub releases for?

**Comment by HenrikBengtsson** [comment]
Mostly to quickly look up when a specific version was released and to do `git diff`:s between versions.

**Comment by HenrikBengtsson** [comment]
FYI, https://github.com/petervanderdoes/gitflow-avh automates the tagging releases etc in a really nice way so you don't have to do it manually.

**Comment by jimhester** [comment]
Ah, I generally use the cran GH, mirror for that.

The main issue is I can't tag a given commit until it is actually accepted by CRAN, and that is usually hours / days after I submit and I am generally then working on a different package.

**Comment by HenrikBengtsson** [comment]
I also don't _push_ tags until on CRAN either.

**Comment by jimhester** [comment]
Now fixed
