### ISSUE TITLE
devtools::install_github("r-lib/fs") fails due to configure permissions

### ISSUE THREAD

**Issue by wch** [r-lib/fs#113]
This is the same issue as rstudio/httpuv#151.

On rstudio.cloud, this happens:

```
> devtools::install_github("r-lib/fs")
...
(cd libuv \
	&& touch aclocal.m4 \
	&& touch -r aclocal.m4 configure Makefile.in \
&& CC="gcc" CFLAGS="-g -O2  -fpic -fvisibility=hidden" AR="ar" RANLIB="ranlib" LDFLAGS="-L/usr/local/lib" ./configure --quiet)
/bin/bash: line 3: ./configure: Permission denied
Makevars:32: recipe for target 'libuv/Makefile' failed
make: *** [libuv/Makefile] Error 126
ERROR: compilation failed for package ‘fs’
```

It happens whenever the `unzip` option is set to `"internal"`. It can be reproduced on any Linux or Mac with:

```R
options(unzip = "internal")
remotes::install_github("rstudio/httpuv")
```

**Comment by jimhester** [comment]
I think I am going to close this in favor of https://github.com/r-lib/devtools/issues/1799

I could explicitly set the internal configure as executable, but I think it is better changed upstream.

**Comment by travis-leith** [comment]
@jimhester this problem does not seem to have been fixed upstream and is still an issue, at least for me on RHEL8
