### ISSUE TITLE
globs and file paths?

### ISSUE THREAD

**Issue by cboettig** [r-lib/fs#118]
I'm trying to emulate the common `ls` behavior with globs and file paths.  I thought that the `path` argument would effectively be the  "working directory" for `ls` call and that the glob could include paths, but this doesn't seem to be the case, e.g.

```r
fs::dir_create("data/stuff")
fs::dir_create("data/stuff2")
fs::file_create("data/stuff/good.tsv")
fs::dir_ls(glob = "data/*/*.tsv")
```
does not find `good.tsv`, but running `ls data/*/*.tsv` from the terminal with the same working dir (`.`) does.  If the path part doesn't have wild-cards I can manually split this into a path and a final glob, and include whatever base working directory, e.g. something like:

```r
proj_dir  ="."
g = "data/*/*.tsv"

path <- fs::path_join(c(proj_dir, fs::path_rel(fs::path_dir(g))))
glob <- fs::path_file(g)
fs::dir_ls(path = path, glob = glob, recursive = TRUE)
```

but this won't work for the example above where the path includes a glob.  (Context: I'd like to reliably parse files like .gitattributes to identify all files "tracked" by git lfs).

**Comment by jimhester** [comment]
`dir_ls()` does not recurse by default, so in this case you need to set `recursive = TRUE` in the call to `dir_ls()`.

``` r
fs::dir_create("data/stuff")
fs::dir_create("data/stuff2")
fs::file_create("data/stuff/good.tsv")
fs::dir_ls(glob = "data/*/*.tsv", recursive = TRUE)
#> data/stuff/good.tsv
```

Created on 2018-06-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by cboettig** [comment]
@jimhester Ah, I was already using `recursive = TRUE`, but I was also setting `path = usethis::proj_get()`, which causes this to fail:

```r
fs::dir_create("data/stuff")
fs::dir_create("data/stuff2")
fs::file_create("data/stuff/good.tsv")
fs::dir_ls(glob = "data/*/*.tsv", recursive = TRUE, path = usethis::proj_get())
#> character(0)
```

Given that my project directory was my working directory (`"."`, I thought this would be the same as the default, but the problem seems to be that I get different behavior when giving an absolute rather than the equivalent relative path!

```r
fs::dir_create("data/stuff")
fs::dir_create("data/stuff2")
fs::file_create("data/stuff/good.tsv")
fs::dir_ls(glob = "data/*/*.tsv", path = fs::path_abs("."), recursive = TRUE)
#> character(0)
```

that behavior seems unexpected to me...

**Comment by jimhester** [comment]
your glob doesn't account for absolute paths, you would need to prefix `*` to it for that to work, e.g.

```r
fs::dir_ls(glob = "*/data/*/*.tsv", path = fs::path_abs("."), recursive = TRUE)
```

**Comment by cboettig** [comment]
clever! I haven't quite wrapped my head around that one (i.e. what the bash "equivalent" is -- my mental model for `dir_ls` is that it is doing the equivalent to `cd` <path>` and then `ls <glob>`, but clearly that's not the case -- I guess `path` and `glob` are getting appended somehow?

 I'm hoping to parse user-specified globs from things like  Git LFS's`.gitattributes` file, so I guess I could equivalently just wrap my `path` in `fs::path_rel`?  Does that sound wise? e.g. 

```r
fs::dir_ls(glob = "data/*/*.tsv", recursive = TRUE, path = fs::path_rel(usethis::proj_get()))
```

Clearly pre-pending a glob to the user's specified value doesn't sound like a good solution.  (i.e. if the user puts `binary-*` as the pattern in `.gitattributes`, I'd want a command that doesn't decide `not-binary-*` is also a tracked pattern. )

**Comment by jimhester** [comment]
`dir_ls()` lists the files on the specified path, then filters them by whatever is in the glob argument, which is kind of the opposite of how this works in a shell. It is exactly equivalent to `dir_ls(path = "xyz") %>% path_filter(glob = "abc")`

`fs::path_rel()` computes paths relative to the current working directory, which is not what I think you want in this case, you want to compute paths relative to the project directory regardless of what the working directory is.

```r
library(fs)
proj <- usethis::proj_get()

dir_ls(path = proj, recursive = TRUE) %>%
  path_rel(proj) %>%
  path_filter(glob = "data/*/*.tsv"))
```

**Comment by cboettig** [comment]
Nice, that all makes sense to me now.  You are the best. Thanks so much for this!

**Comment by ralonso-igenomix** [comment]
Hello,

what do you think a function like the one in native R:
Sys.glob("/home/ralonso/projects/myosarcoma/BaseSpace/BaseSpace_TRAININGTS170/Projects/*/Samples/*M*/SampleProperties")

something like:
dir_ls(glob ="/home/ralonso/projects/myosarcoma/BaseSpace/BaseSpace_TRAININGTS170/Projects/*/Samples/*M*/SampleProperties")

I think will simpler things a lot.

Thanks a lot
