### ISSUE TITLE
is the anchor start at line "^" implemented?

### ISSUE THREAD

**Issue by olesendan** [r-lib/fs#127]
I'm having trouble getting the regexp to work with "^". I get respected output when I use "$" as a anchor end of line

see exemples here
Working -> lists files ending with ".csv"
  tibble::tibble(
    path = fs::dir_ls(
      here::here( "data"),
      regexp = ".csv$"))

not working -> says character(0)
purrr::map(
    fs::dir_ls(
      here::here( "r"),
      regexp = "^func"),
    .f = source, local = .GlobalEnv)

greetings from Denmark
Dan Olesen

**Comment by jimhester** [comment]
`here::here()` returns an absolute path, so the `^` of the regexp would be the root directory on your filesystem. Maybe you want to use the [word boundary anchor](https://www.regular-expressions.info/wordboundaries.html)? e.g. `"\\bfoo"`
