### ISSUE TITLE
file_temp() handles extensions differently

### ISSUE THREAD

**Issue by gadenbuie** [r-lib/fs#136]
`file_temp()` passes it's arguments to `tempfile()` so the dot before the extension isn't added when `ext` is supplied.

``` r
fs::file_temp(ext = "png")
#> /var/folders/zw/8z2vpz1s0cl3gwpyh5p72mwh0000gn/T/RtmpCH0bFk/file182f41b49023bpng
```

But all other functions in `fs` do add the dot.

``` r
fs::path("image", ext = "png")
#> image.png
fs::path_wd("image", ext = "png")
#> /private/var/folders/zw/8z2vpz1s0cl3gwpyh5p72mwh0000gn/T/RtmpK6r2gf/reprex1539e7ebfaa4/image.png
fs::path_ext_set("image", ext = "png")
#> image.png
```

They all have similar documentation

    path(..., ext = "")
    path_wd(..., ext = "")
        ext An optional extension to append to the generated path.
    
    path_ext_set(path, ext)
    path_ext(path) <- value
        ext, value The new file extension.
        
    file_temp(pattern = "file", tmp_dir = tempdir(), ext = "")
        ext The file extension of the temporary file.

so it's easy to miss this detail. The examples for `file_temp()` mention that its arguments are passed on to `tempfile()`, but I think it’s easy to overlook the implication that the `.` is required (especially because this information doesn't appear in the RStudio autocomplete helper).

``` r
tempfile(fileext = "png")
#> [1] "/var/folders/zw/8z2vpz1s0cl3gwpyh5p72mwh0000gn/T//RtmpCH0bFk/file182f47b2d70e8png"
```

It would be nice to to mention this difference in the documentation of `ext` in `file_temp()`, or even better for `ext` to behave similarly across `fs`.
<sup>Created on 2018-10-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment]
Thank, I agree having this consistent with the rest of the fs functions would be ideal. PR would be greatly appreciated if you are interested!
