### ISSUE TITLE
Add vectorized `path_join` with multiple parameters

### ISSUE THREAD

**Issue by colearendt** [r-lib/fs#139]
Use case:

I have a list of files, a directory, and want a fully qualified path to the files. I could perhaps work around this with `path_rel` with a different start point (or `paste`), but I think having a way to easily concatenate the files together with some type of `path_join` would be nice.

``` r
# I have a handful of files
files <- c("one", "two", "three")
files_list <- list("one", "two", "three")

# in a directory
current_dir <- "./path/to/files"

# i want the full path to these files
fs::path_join(list(current_dir, files))
#> ./path/to/files one/two/three
fs::path_join(c(current_dir, files))
#> ./path/to/files/one/two/three
fs::path_join(list(current_dir, files_list))
#> Error in vapply(parts, path_join, character(1)): values must be length 1,
#>  but FUN(X[[2]]) result is length 3
fs::path_join(c(current_dir, files_list))
#> ./path/to/files one             two             three

# ideally... something like
# fs::path_join(current_dir, files)
#> ./path/to/files/one ./path/to/files/two ./path/to/files/three
#>

# workaround
paste(current_dir, files, sep = "/")
#> [1] "./path/to/files/one"   "./path/to/files/two"   "./path/to/files/three"
```

Created on 2018-10-17 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jimhester** [comment]
If I understand the question this is what `fs::path()` is for. `path_join()` is mainly there just to be the inverse of `path_split()`, most of the time you should use `path()` to construct paths.

``` r
current_dir <- "./path/to/files"
files <- c("one", "two", "three")

fs::path(current_dir, files)
#> ./path/to/files/one   ./path/to/files/two   ./path/to/files/three
```

<sup>Created on 2018-10-17 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by colearendt** [comment]
Completely missed that, thanks!! Was looking for a verb 🤦‍♂️
