### ISSUE TITLE
Colorize file types like `dircolors`

### ISSUE THREAD

**Issue by jimhester** [r-lib/fs#14]
`dircolors --print-database` gives you all the combinations, we could use `LS_COLORS` environment variable, falling back to the defaults otherwise.

**Comment by jimhester** [comment]
e.g.

![screenshot 2017-12-21 21 44 08](https://user-images.githubusercontent.com/205275/34283133-2b0b12f4-e698-11e7-830a-e7edd85110c5.png)

**Comment by hadley** [comment]
This would be another S3 helper class, I'm guessing?

**Comment by jimhester** [comment]
yeah

**Comment by jimhester** [comment]
closed by https://github.com/r-lib/fs/pull/23
