### ISSUE TITLE
Allow limit on dir_ls

### ISSUE THREAD

**Issue by hammer** [r-lib/fs#140]
I have a directory with 2.8 million files in it (don't blame me, I did not create this directory!). I would like the option to limit the number of items returned by `fs::dir_ls` to `n`. Looking through the [implementation](https://github.com/r-lib/fs/blob/master/src/dir.cc#L48), this seems quite possible; we can just stop calling `uv_fs_scandir_next` when we hit either `n` items or the end of the directory. Would you be open to extending the `fs::dir_ls` API to include a limit?

**Comment by jimhester** [comment]
It is certainly possible, however I am not sure if we should do it, if you are able to control the number of files you would also ideally have control over the order the files are in, which I don't really want to handle.

What is the issue with the directory with a lot of files? Does it take a long time to return results or is it more handling the data?

**Comment by jimhester** [comment]
You can now limit at least the depth of files returned with e.g. `recurse = 2`, which I think is sufficient for most cases. Will close this for now.
