### ISSUE TITLE
file_open() - New Function for opening files via path

### ISSUE THREAD

**Issue by mdancho84** [r-lib/fs#142]
Jim and company,

`fs` is an awesome package. I use it a ton. I love it.

Here's a function, `file_open()` that might be a nice addition that I use quite a bit in my course to open files (e.g. PDF, images, etc) from R. 

Try it out. See if you become addicted as I did. If so, feel free to use it in `fs`. 

``` {r}
file_open <- function(path) {
    
    open_path_chr <- paste0("open '", path, "'")
    
    return(system(open_path_chr))
    
}
```

**Comment by jimhester** [comment]
This is what `fs::file_show()` does.

**Comment by mdancho84** [comment]
Also I saw the xopen package.
