### ISSUE TITLE
fs does not compile on openbsd

### ISSUE THREAD

**Issue by emgee61** [r-lib/fs#145]
Installing "tidyverse" in R op openbsd 6.4 ( on 6.3 it works) throws errors because fs (and likely consequently reprex) wont compile; on r/openbsd I asked if anyone experienced that also; which was confirmed by u/vtail57; he dug into it and came up with an offending line:
https://github.com/r-lib/fs/blob/73bde0d42fce4acc786f4610e81ca2ede4d32f49/src/unix/getmode.cc#L3

#if (defined(__APPLE__) && defined(__MACH__)) || defined(__BSD__)

running: cpp -dM /dev/null | grep -i BSD shows that only __OpenBSD__ is defined by clang 6.0.0, which is a C compiler shipping with OpenBSD 6.4.

This my first reporting issue ever so if it not complies to the proper guidelines apologies

**Comment by vtail** [comment]
And here is an [Pre-defined compiler macros](https://sourceforge.net/p/predef/wiki/OperatingSystems/) resource that is referenced in multiple SO answers and has a BSD section:

**Comment by greenfork** [comment]
I have the same issue.

There's a log of fs being compiled:

```
* installing *source* package 'fs' ...
** package 'fs' successfully unpacked and MD5 sums checked
** libs
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c error.cc -o error.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c dir.cc -o dir.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c fs.cc -o fs.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c path.cc -o path.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c link.cc -o link.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c utils.cc -o utils.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c file.cc -o file.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c id.cc -o id.o
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -I/us
r/local/include   -fpic  -O2 -pipe  -c unix/getmode.cc -o unix/getmode.o

In file included from unix/getmode.cc:7:
In file included from ./bsd/string.h:37:
./bsd/cdefs.h:2:9: warning: '__BEGIN_DECLS' macro redefined [-Wmacro-redefined]
#define __BEGIN_DECLS extern "C" {
        ^
/usr/include/sys/cdefs.h:258:9: note: previous definition is here
#define __BEGIN_DECLS   __BEGIN_EXTERN_C
        ^
In file included from unix/getmode.cc:7:
In file included from ./bsd/string.h:37:
./bsd/cdefs.h:3:9: warning: '__END_DECLS' macro redefined [-Wmacro-redefined]
#define __END_DECLS }
        ^
/usr/include/sys/cdefs.h:259:9: note: previous definition is here
#define __END_DECLS     __END_EXTERN_C
        ^
In file included from unix/getmode.cc:7:
./bsd/string.h:44:6: error: conflicting types for 'strmode'
void strmode(mode_t mode, char *str);
     ^
/usr/include/string.h:131:7: note: previous declaration is here
void     strmode(int, char *);
         ^
In file included from unix/getmode.cc:8:
./bsd/unistd.h:58:6: error: functions that differ only in their return type cannot be overloaded
void closefrom(int lowfd);
~~~~ ^
/usr/include/unistd.h:478:6: note: previous declaration is here
int      closefrom(int);
~~~      ^
2 warnings and 2 errors generated.
gmake: *** [/usr/local/lib/R/etc/Makeconf:164: unix/getmode.o] Error 1
ERROR: compilation failed for package 'fs'

```

**Comment by zeloff** [comment]
Adding `#include <sys/param.h>` to the top of `getmode.cc` and changing `__BSD__` to `BSD` on line 3 (which becomes line 4 after inserting the `#include`) partially fixed compilation on OpenBSD. I'm getting trouble further down the line with the `libuv` part, but I'll check it next.
Will make a pull request when/if I get it all sorted and properly tested.

**Comment by mkurdej** [comment]
The same issue on FreeBSD, just getting a bit different errors but the issue seems to be the same (not checking `__FreeBSD__`) at line https://github.com/r-lib/fs/blob/73bde0d42fce4acc786f4610e81ca2ede4d32f49/src/unix/getmode.cc#L3.

```
c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/library/Rcpp/include" -DLIBICONV_PLUG -I/usr/local/include -isystem /usr/local/include   -fpic  -O2 -pipe -DLIBICONV_PLUG -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include   -c unix/getmode.cc -o unix/getmode.o
In file included from unix/getmode.cc:7:
./bsd/string.h:44:6: error: conflicting types for 'strmode'
void strmode(mode_t mode, char *str);
     ^
 /usr/include/string.h:97:7: note: previous declaration is here
void     strmode(int, char *);
        ^
1 error generated.

gmake: *** [/usr/local/lib/R/etc/Makeconf:164: unix/getmode.o] Error 1
ERROR: compilation failed for package 'fs'
```

So, here the problem is that `string.h` was included somewhere before and now it includes `bsd/string.h`.

**Comment by commandline-be** [comment]
also fail on mode_t on Alpine Linux, see the fresh issue created for this

**Comment by joelmaxuel** [comment]
+1 for FreeBSD 12-RELEASE:

    c++  -I"/usr/local/lib/R/include" -DNDEBUG -I./libuv/include -I. -I"/home/joel/Build/bin/R/amd64-portbld-freebsd12.0-library/Rcpp/include" -DLIBICONV_PLUG -I/usr/local/include -isystem /usr/local/include   -fpic  -O2 -pipe -DLIBICONV_PLUG -fstack-protector -isystem /usr/local/include -fno-strict-aliasing  -DLIBICONV_PLUG -isystem /usr/local/include   -c unix/getmode.cc -o unix/getmode.o
    In file included from unix/getmode.cc:7:
    ./bsd/string.h:44:6: error: conflicting types for 'strmode'
    void strmode(mode_t mode, char *str);
         ^
    /usr/include/string.h:99:7: note: previous declaration is here
    void     strmode(int, char *);
             ^
    1 error generated.
    gmake: *** [/usr/local/lib/R/etc/Makeconf:167: unix/getmode.o] Error 1
    ERROR: compilation failed for package ‘fs’
 
Is there a workaround for now?  I could modify/mess-with the guard but I am not that familiar enough with R to compile a locally modified package (given `install.packages()` downloads a fresh copy and destroys it if it fails).

**Comment by kirchkamp** [comment]
+1 for FreeBSD 12-Release from me, too! It is just one line - please :-)

Indeed, line 3 of  `fs/src/unix/getmode.cc` is just wrong. It should be something like the following:
```
#if (defined(__APPLE__) && defined(__MACH__)) || defined(__OpenBSD__) || defined(__FreeBSD__)
 || defined(__NetBSD__)
```
The *workaround* is: 
* Download package source from CRAN
* extract source with `tar xzvf fs_1.2.6.tar.gz` 
* change line 3 in `fs/src/unix/getmode.cc` to the correct value.
* create corrected version with `tar czvf fs_1.2.6a.tar.gz` 
* install with `R CMD INSTALL tar czvf fs_1.2.6a.tar.gz`
