### ISSUE TITLE
Installation failed on Raspberry PI 3 - Debian Stretch - R 3.5.1

### ISSUE THREAD

**Issue by AnthonyGermain** [r-lib/fs#146]
I'm trying to install the tidyverse package that depends on your package but I failed to install your package.
 I have a new installation of stretch where I just ran apt-get update && upgrade and installed R 3.5.1.

Here is the full log I got : 

pi@raspberrypi:~ $ R CMD config --all
CC = gcc -std=gnu99
CFLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g
CPICFLAGS = -fpic
CPP = gcc -std=gnu99 -E
CPPFLAGS =
CXX = g++
CXXCPP = g++ -E
CXXFLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g
CXXPICFLAGS = -fpic
CXX11 = g++
CXX11STD = -std=gnu++11
CXX11FLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g
CXX11PICFLAGS = -fpic
CXX14 = g++
CXX14STD = -std=gnu++14
CXX14FLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g
CXX14PICFLAGS = -fpic
CXX98 = g++
CXX98STD = -std=gnu++98
CXX98FLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g
CXX98PICFLAGS = -fpic
CXX17 =
CXX17STD =
CXX17FLAGS =
CXX17PICFLAGS =
CXX1X = g++
CXX1XSTD = -std=gnu++11
CXX1XFLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g
CXX1XPICFLAGS = -fpic
DYLIB_EXT = .so
DYLIB_LD = gcc -std=gnu99
DYLIB_LDFLAGS = -shared -fopenmp
F77 = gfortran
FFLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong
FPICFLAGS = -fpic
FLIBS = -lgfortran -lm
SAFE_FFLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong
FC = gfortran
FCFLAGS = -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong
FCPICFLAGS = -fpic
OBJC =
OBJCFLAGS =
JAVA = /usr/lib/jvm/default-java/jre/bin/java
JAVAC = /usr/lib/jvm/default-java/bin/javac
JAVAH = /usr/lib/jvm/default-java/bin/javah
JAR = /usr/lib/jvm/default-java/bin/jar
JAVA_HOME = /usr/lib/jvm/default-java
JAVA_LIBS = -L/usr/lib/jvm/default-java/jre/lib/arm/client -ljvm
JAVA_CPPFLAGS = -I/usr/lib/jvm/default-java/include -I/usr/lib/jvm/default-java/include/linux
LDFLAGS = -Wl,-z,relro
SHLIB_CFLAGS =
SHLIB_CXXLD = g++
SHLIB_CXXLDFLAGS = -shared
SHLIB_CXX98LD = g++ -std=gnu++98
SHLIB_CXX98LDFLAGS = -shared
SHLIB_CXX11LD = g++ -std=gnu++11
SHLIB_CXX11LDFLAGS = -shared
SHLIB_CXX14LD = g++ -std=gnu++14
SHLIB_CXX14LDFLAGS = -shared
SHLIB_CXX17LD =
SHLIB_CXX17LDFLAGS = -shared
SHLIB_EXT = .so
SHLIB_FFLAGS =
SHLIB_LD = gcc -std=gnu99
SHLIB_LDFLAGS = -shared
SHLIB_FCLD = gfortran
SHLIB_FCLDFLAGS = -shared
SHLIB_CXX1XLD = g++ -std=gnu++11
SHLIB_CXX1XLDFLAGS = -shared
TCLTK_CPPFLAGS = -I/usr/include/tcl8.6 -I/usr/include/tcl8.6
TCLTK_LIBS = -L/usr/lib/arm-linux-gnueabihf -ltcl8.6 -L/usr/lib/arm-linux-gnueabihf -ltk8.6 -lX11 -lXss -lXext
BLAS_LIBS = -lblas
LAPACK_LIBS = -llapack
MAKE = make
LIBnn = lib
LOCAL_SOFT =
COMPILED_BY =

pi@raspberrypi:~ $ sudo R

R version 3.5.1 (2018-07-02) -- "Feather Spray"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: arm-unknown-linux-gnueabihf (32-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("fs")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/fs_1.2.6.tar.gz'
Content type 'application/x-gzip' length 799325 bytes (780 KB)
==================================================
downloaded 780 KB

* installing *source* package ‘fs’ ...
** package ‘fs’ successfully unpacked and MD5 sums checked
** libs
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c id.cc -o id.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c utils.cc -o utils.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c file.cc -o file.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c path.cc -o path.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c link.cc -o link.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c fs.cc -o fs.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c dir.cc -o dir.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c error.cc -o error.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c unix/getmode.cc -o unix/getmode.o
g++  -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bsd/setmode.c -o bsd/setmode.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bsd/strmode.c -o bsd/strmode.o
gcc -std=gnu99 -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -I"/usr/local/lib/R/site-library/Rcpp/include"    -fpic  -g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bsd/reallocarray.c -o bsd/reallocarray.o
cp -p -f libuv/m4/lt_obsolete.m4 libuv/m4/lt~obsolete.m4
(cd libuv \
        && touch aclocal.m4 \
        && touch -r aclocal.m4 configure Makefile.in \
&& CC="gcc -std=gnu99" CFLAGS="-g -O2 -fdebug-prefix-map=/root/git/r-backports/stretch/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -fpic -fvisibility=hidden" AR="ar" RANLIB="ranlib" LDFLAGS="-Wl,-z,relro" ./configure --quiet)
make --directory=libuv \
        HAVE_DTRACE=0
make[1]: Entering directory '/tmp/Rtmppo6lCa/R.INSTALL2e212d029191/fs/src/libuv'
  CC       src/libuv_la-fs-poll.lo
  CC       src/libuv_la-inet.lo
  CC       src/libuv_la-threadpool.lo
  CC       src/libuv_la-uv-common.lo
  CC       src/libuv_la-version.lo
  CC       src/unix/libuv_la-async.lo
  CC       src/unix/libuv_la-core.lo
  CC       src/unix/libuv_la-dl.lo
  CC       src/unix/libuv_la-fs.lo
  CC       src/unix/libuv_la-getaddrinfo.lo
  CC       src/unix/libuv_la-getnameinfo.lo
  CC       src/unix/libuv_la-loop-watcher.lo
  CC       src/unix/libuv_la-loop.lo
  CC       src/unix/libuv_la-pipe.lo
  CC       src/unix/libuv_la-poll.lo
  CC       src/unix/libuv_la-process.lo
  CC       src/unix/libuv_la-signal.lo
  CC       src/unix/libuv_la-stream.lo
  CC       src/unix/libuv_la-tcp.lo
  CC       src/unix/libuv_la-thread.lo
  CC       src/unix/libuv_la-timer.lo
  CC       src/unix/libuv_la-tty.lo
  CC       src/unix/libuv_la-udp.lo
  CC       src/unix/libuv_la-linux-core.lo
  CC       src/unix/libuv_la-linux-inotify.lo
  CC       src/unix/libuv_la-linux-syscalls.lo
  CC       src/unix/libuv_la-procfs-exepath.lo
  CC       src/unix/libuv_la-proctitle.lo
  CC       src/unix/libuv_la-sysinfo-loadavg.lo
  CC       src/unix/libuv_la-sysinfo-memory.lo
  CCLD     libuv.la
ar: `u' modifier ignored since `D' is the default (see `U')
make[1]: Leaving directory '/tmp/Rtmppo6lCa/R.INSTALL2e212d029191/fs/src/libuv'
g++ -shared -L/usr/lib/R/lib -Wl,-z,relro -o fs.so id.o utils.o file.o path.o link.o fs.o dir.o error.o unix/getmode.o RcppExports.o bsd/setmode.o bsd/strmode.o bsd/reallocarray.o ./libuv/.libs/libuv.a -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/fs/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘fs’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/fs/libs/fs.so':
  /usr/local/lib/R/site-library/fs/libs/fs.so: undefined symbol: pthread_atfork
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/usr/local/lib/R/site-library/fs’

The downloaded source packages are in
        ‘/tmp/RtmpLGKSri/downloaded_packages’
Warning message:
In install.packages("fs") :
  installation of package ‘fs’ had non-zero exit status

Any idea how I could fix this ?

**Comment by andresrcs** [comment]
This has been already assessed in this other issue #128, and this walk around [solution](https://github.com/r-lib/fs/issues/128#issuecomment-435552967) worked for me.
