### ISSUE TITLE
Behaviour when copying a file onto itself

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#148]
I wonder if `fs::file_copy()` should behave like `cp` here, which refuses to copy a file onto itself, even with `-f`?

---

A study of copying a file onto itself, in R vs. the shell.

Motivated by this troubleshooting in rcmdcheck:  
<a href="https://github.com/r-lib/rcmdcheck/pull/86" class="uri">https://github.com/r-lib/rcmdcheck/pull/86</a>  
<a href="https://github.com/r-lib/rcmdcheck/issues/87" class="uri">https://github.com/r-lib/rcmdcheck/issues/87</a>

fs complains about copying to a pre-existing file. With `overwrite = TRUE`, it seems to silently unlink it and write a new file with requested name but no content.

    library(fs)

    writeLines("I have content!", "~/tmp/foo.txt")
    readLines("~/tmp/foo.txt")
    #> [1] "I have content!"

    file_copy("~/tmp/foo.txt", "~/tmp")
    #> Error: [EEXIST] Failed to copy '/Users/jenny/tmp/foo.txt' to '/Users/jenny/tmp/foo.txt': file already exists

    file_copy("~/tmp/foo.txt", "~/tmp", overwrite = TRUE)
    readLines("~/tmp/foo.txt")
    #> character(0)

Base R effectively does same, but with more mystifying communications.

    writeLines("I have content!", "~/tmp/foo.txt")

    file.copy("~/tmp/foo.txt", "~/tmp")
    #> [1] FALSE
    readLines("~/tmp/foo.txt")
    #> [1] "I have content!"

    file.copy("~/tmp/foo.txt", "~/tmp", overwrite = TRUE)
    #> [1] TRUE
    readLines("~/tmp/foo.txt")
    #> character(0)

`cp` in the shell cannot even be forced to overwrite a file with itself. Note that it always errors about the target file being identical to the source file.

    echo 'I have content!' > ~/tmp/foo.txt
    cat ~/tmp/foo.txt

    cp ~/tmp/foo.txt ~/tmp

    cp -f ~/tmp/foo.txt ~/tmp

    cat ~/tmp/foo.txt
    #> I have content!
    #> cp: /Users/jenny/tmp/foo.txt and /Users/jenny/tmp/foo.txt are identical (not copied).
    #> cp: /Users/jenny/tmp/foo.txt and /Users/jenny/tmp/foo.txt are identical (not copied).
    #> I have content!

**Comment by jimhester** [comment]
Yes I agree

Note to self, probably the best way to do this is to check the device and inode are the same, e.g. https://github.com/openbsd/src/blob/aaf790e0a6b74f8be428f4eddbd71fd97efba3d5/bin/cp/cp.c#L378-L379

**Comment by jimhester** [comment]
After looking at this a bit more I don't think we want to go down this route, in order to check if the file is the same we would need to stat each source and destination and then check the inode, which means each copy would be 3 system calls instead of 1, and it would complicate the code quite a lot. It seems like too much work to me for the gain in behavior.
