### ISSUE TITLE
path_ext_*() should only look at the last "part" of path

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#153]
Discovered via https://github.com/tidyverse/reprex/issues/223

Seems like the "extension finding / replacing" should only operate on the last part of the path.

``` r
library(fs)

path_ext_remove("C:/Users/jenny.bryan/AppData/Local/Temp/foo.R")
#> C:/Users/jenny.bryan/AppData/Local/Temp/foo

path_ext_remove("C:/Users/jenny.bryan/AppData/Local/Temp")
#> C:/Users/jenny

p <- "C:/Users/jenny.bryan/AppData/Local/Temp"
path(path_dir(p), path_ext_remove(path_file(p)))
#> C:/Users/jenny.bryan/AppData/Local/Temp
```

<sup>Created on 2018-11-14 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by GegznaV** [comment]
I agree, that only the last part of the path should be modified.
In example:
```r
fs::path_ext_set("D:/Data.R/RcmdrPlugin/EZR/iris", "txt")
```
I get `D:/Data.txt`, but I expected `D:/Data.R/RcmdrPlugin/EZR/iris.txt`.
