### ISSUE TITLE
Comparison table: base R vs fs

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#156]

**Comment by jennybc** [comment]
And unix/shell?

**Comment by xvrdm** [comment]
Would this be a step in the right direction, or are you looking for something that includes comments about the pro/cons/caveats of each approach?

fs | base | shell
-|-|-
`dir_create(<new-dir-path>)` | `dir.create(<new-dir-path>)` | `mkdir <new-dir-path>`
`dir_copy(<dir-path>, <new_dir_path>)` | `dir.create(<new_dir_path>); file.copy(<dir-path>, <new_dir_path>, recursive=TRUE)` | `cp <dir-path> <new_dir_path>`
`dir_delete(<dir-path>)` | `unlink(<dir-path>, recursive = TRUE)` | `rm -rf <dir-path>`
`dir_exists(<dir-path>)` | `dir.exists(<dir-path>)` | `if [ -d <dir-path> ]; then ... ; fi`
`dir_info(<dir-path>)` | `do.call(rbind, lapply(list.files(<dir-path>), file.info))` | `ls -al <dir-path>`
`dir_ls(<dir-path>)` | `list.files(<dir-path>)` | `ls <dir-path>`

**Comment by jimhester** [comment]
If it helps here is the table of base R functions we used when writing tibble, although it is not completely updated, there may be some fs functions missing / renamed.

| base R           | fs          |
|------------------|-------------|
| file.append      | —           |
| Sys.setFileTime  | —           |
| file.mode        | —           |
| file.mtime       | —           |
| file.size        | —           |
| Sys.umask        | —           |
| —                | dir_copy    |
| dir.create       | dir_create  |
| —                | dir_info    |
| dir              | dir_list    |
| —                | dir_move    |
| —                | dir_delete  |
| —                | dir_walk    |
| —                | dir_watch   |
| file.access      | file_access |
| Sys.chmod        | file_chmod  |
| —                | file_chown  |
| file.copy        | file_copy   |
| file.create      | file_create |
| file.remove      | file_delete |
| unlink           | file_delete |
| file.info        | file_info   |
| —                | file_move   |
| file.rename      | file_rename |
| —                | file_watch  |
| dir.exists       | is_dir      |
| file.exists      | is_file     |
| —                | is_link     |
| file.symlink     | link_create |
| file.link        | link_create |
| —                | link_info   |
| Sys.readlink     | link_path   |
| file.path        | path        |
| path.expand      | path_expand |
| path.expand("~") | path_home   |
| normalizePath    | path_norm   |
|                  | path_split  |
| tempdir          | path_temp   |

**Comment by xvrdm** [comment]
Not finished yet, but it is [here](https://gist.github.com/xvrdm/842a185ac800626f349480a9a781d7e8) for now.

**Comment by cderv** [comment]
I think the comparison should include a part on specific behaviour changed from base R. 
I know they are some on windows like this one: 
``` r
fs::path_home()
#> C:/Users/chris
fs::path_expand("~")
#> C:/Users/chris
path.expand("~")
#> [1] "C:/Users/chris/Documents"
fs::path_expand_r("~")
#> C:/Users/chris/Documents
fs::path_home_r()
#> C:/Users/chris/Documents
```

<sup>Created on 2019-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

For a windows user, this specificity must be known. It is particularly tricky when working with 📦 that uses `fs` like usethis. For example, I need to write this: 
```r
usethis::create_from_github("r-lib/remotes", destdir = fs::path_home_r("DEV_R"))
```
to write in the `~/DEV_R` folder seen by R.  (_C:/Users/chris/Documents/DEV\_R_)
```r
usethis::create_from_github("r-lib/remotes", destdir = "~/DEV_R")
```
would have write in _C:/Users/chris/DEV\_R_

**Comment by xvrdm** [comment]
We could maybe add a link to a footnote next to the relevant functions, so that we are not limited by the space constraints of the table.

Should the table be a PR for the bottom of the README?

**Comment by hadley** [comment]
I think the README is probably big enough that a vignette (base vs fs) is the right place. We could prominently highlight the `~` differences at the top.
