### ISSUE TITLE
file_exists returns TRUE for directories

### ISSUE THREAD

**Issue by GegznaV** [r-lib/fs#159]
I expect `file_exists()` to return `FALSE` if a directory name is provided instead of a file name. But it returns `TRUE`. Is this behavior expected?

``` r
fs::file_exists("C:")
#>  C:/ 
#> TRUE
```

If the behavior is expected, it should be noted in documentation.

**Comment by jimhester** [comment]
Yes of course, directories _are_ files for all supported operating systems. This is the same behavior as `base::file.exists()`.

**Comment by GegznaV** [comment]
I think, `is_file()` does what I needed. But links between the functions in the documentation and more detailed descriptions that indicate similarities and differences would be appreciated.
