### ISSUE TITLE
ENOENT error with dir_ls() when hidden file is in path

### ISSUE THREAD

**Issue by richierocks** [r-lib/fs#164]
Under Windows 10, some directories can only be accessed by an administrator. Where R doesn't have enough permission to see a directory, the behavior of `fs::dir_ls()` and `dir()` differs: `dir_ls()` throws an error, but `dir()` silently ignores the existence of that directory.

For example, when searching the Program Files directory, I see

``` r
library(fs)
program_files <- "%ProgramFiles%"
dir_ls(program_files)
#> Error: [ENOENT] Failed to search directory '%ProgramFiles%': no such file or directory
dir(program_files)
#> character(0)
```

This behavior of `dir_ls()` seems fine in the non-recursive case. However, when `recursive = TRUE`, it seems preferable to skip directories where there is not enough permission.

I'm struggling to create a completely reproducible example, but here's the motivating example that led me to find this. I tried recursively searching `~`. Kaspersky Password Manager is installed, and this stores some data in an admin-protected folder inside the `%LocalAppData%` directory, which is  a subdirectory of `~`. I ran this while logged in as under a Windows admin account.

``` r
library(fs)
dir_ls("~", recursive = TRUE)
#> Error: [EPERM] Failed to search directory 'C:/Users/richie/AppData/Local/Kaspersky Lab/Kaspersky Password Manager': operation not permitted
```

Here's the traceback.

```
4: (function (..., call. = TRUE, domain = NULL) 
   {
       args <- list(...)
       if (length(args) == 1L && inherits(args[[1L]], "condition")) {
           cond <- args[[1L]]
           if (nargs() > 1L) 
               warning("additional arguments ignored in stop()")
           message <- conditionMessage(cond)
           call <- conditionCall(cond)
           .Internal(.signalCondition(cond, message, call))
           .Internal(.dfltStop(message, call))
       }
       else .Internal(stop(call., .makeMessage(..., domain = domain)))
   })(list(message = "[EPERM] Failed to search directory 'C:/Users/richie/AppData/Local/Kaspersky Lab/Kaspersky Password Manager': operation not permitted"))
3: dir_map_(old, fun, all, sum(directory_entry_types[type]), recursive, 
       fail)
2: dir_map(old, identity, all, recursive, type, fail)
1: dir_ls("~", recursive = TRUE)
```

The problem seems to be that the list of directories to search is created with high enough permission to see that the Kaspersky directory exists, then some operation is applied with lower permission that throws an error when it tries to access that directory.

This means that the user doesn't get to see the contents of any of the directories that they do have permission to access.

I think it makes sense to follow the behavior of `dir()` in the recursive case, and just ignore the contents of any subdirectories that the user doesn't have permission to see. Throwing a warning rather than an error would also be an option.

**Comment by jimhester** [comment]
`dir_ls(fail = FALSE)` will issue warnings on errors rather than failing.
