### ISSUE TITLE
install package fs 1.2.6 fail on Alpine 3.8.1 armhf with errors on RcppExports.cpp

### ISSUE THREAD

**Issue by commandline-be** [r-lib/fs#165]
platform= R 3.5.1 and R 3.5.2
apk info libuv    **libuv-1.23.2-r0** while the version inside fs is **1.18 (Stable)**

install.packages("fs", dependencies=TRUE)
. . . . .
g++  -I"/usr/include/R" -DNDEBUG -I./libuv/include -I. -I"/usr/lib/R/library/Rcpp/include" -Os -fomit-frame-pointer -pipe   -fpic  -Os -fomit-frame-pointer -pipe -D__MUSL__   -c RcppExports.cpp -o RcppExports.o
RcppExports.cpp:9:35: error: 'mode_t' has not been declared
 void mkdir_(CharacterVector path, mode_t mode);
                                   ^~~~~~
RcppExports.cpp: In function 'SEXPREC* _fs_mkdir_(SEXP, SEXP)':
RcppExports.cpp:14:36: error: 'mode_t' was not declared in this scope
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
RcppExports.cpp:14:36: note: suggested alternative: 'off_t'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
                                    off_t
RcppExports.cpp:14:43: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                           ^
RcppExports.cpp:14:51: error: expected initializer before 'mode'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                                   ^~~~
RcppExports.cpp:15:18: error: 'mode' was not declared in this scope
     mkdir_(path, mode);
                  ^~~~
RcppExports.cpp:15:18: note: suggested alternative: 'modf'
     mkdir_(path, mode);
                  ^~~~
                  modf
RcppExports.cpp: At global scope:
RcppExports.cpp:57:36: error: 'mode_t' has not been declared
 void create_(CharacterVector path, mode_t mode);
                                    ^~~~~~
RcppExports.cpp: In function 'SEXPREC* _fs_create_(SEXP, SEXP)':
RcppExports.cpp:62:36: error: 'mode_t' was not declared in this scope
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
RcppExports.cpp:62:36: note: suggested alternative: 'move_'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
                                    move_
RcppExports.cpp:62:43: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                           ^
RcppExports.cpp:62:51: error: expected initializer before 'mode'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                                   ^~~~
RcppExports.cpp:63:19: error: 'mode' was not declared in this scope
     create_(path, mode);
                   ^~~~
RcppExports.cpp:63:19: note: suggested alternative: 'modf'
     create_(path, mode);
                   ^~~~
                   modf
RcppExports.cpp: At global scope:
RcppExports.cpp:158:1: error: 'mode_t' does not name a type; did you mean 'move_'?
 mode_t getmode_(const char* mode_str, mode_t mode);
 ^~~~~~
 move_
RcppExports.cpp: In function 'SEXPREC* _fs_getmode_(SEXP, SEXP)':
RcppExports.cpp:164:36: error: 'mode_t' was not declared in this scope
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
RcppExports.cpp:164:36: note: suggested alternative: 'mode_str'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
                                    mode_str
RcppExports.cpp:164:43: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                           ^
RcppExports.cpp:164:51: error: expected initializer before 'mode'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                                   ^~~~
RcppExports.cpp:165:53: error: 'mode' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(getmode_(mode_str, mode));
                                                     ^~~~
RcppExports.cpp:165:53: note: suggested alternative: 'modf'
     rcpp_result_gen = Rcpp::wrap(getmode_(mode_str, mode));
                                                     ^~~~
                                                     modf
RcppExports.cpp:165:34: error: 'getmode_' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(getmode_(mode_str, mode));
                                  ^~~~~~~~
RcppExports.cpp:165:34: note: suggested alternative: '_fs_getmode_'
     rcpp_result_gen = Rcpp::wrap(getmode_(mode_str, mode));
                                  ^~~~~~~~
                                  _fs_getmode_
RcppExports.cpp: At global scope:
RcppExports.cpp:170:22: error: 'mode_t' was not declared in this scope
 std::string strmode_(mode_t mode);
                      ^~~~~~
RcppExports.cpp:170:22: note: suggested alternative: 'move_'
 std::string strmode_(mode_t mode);
                      ^~~~~~
                      move_
RcppExports.cpp: In function 'SEXPREC* _fs_strmode_(SEXP)':
RcppExports.cpp:175:36: error: 'mode_t' was not declared in this scope
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
RcppExports.cpp:175:36: note: suggested alternative: 'move_'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
                                    move_
RcppExports.cpp:175:43: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                           ^
RcppExports.cpp:175:51: error: expected initializer before 'mode'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                                   ^~~~
RcppExports.cpp:176:43: error: 'mode' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(strmode_(mode));
                                           ^~~~
RcppExports.cpp:176:43: note: suggested alternative: 'modf'
     rcpp_result_gen = Rcpp::wrap(strmode_(mode));
                                           ^~~~
                                           modf
RcppExports.cpp: At global scope:
RcppExports.cpp:181:42: error: 'mode_t' has not been declared
 std::string file_code_(std::string path, mode_t mode);
                                          ^~~~~~
RcppExports.cpp: In function 'SEXPREC* _fs_file_code_(SEXP, SEXP)':
RcppExports.cpp:187:36: error: 'mode_t' was not declared in this scope
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
RcppExports.cpp:187:36: note: suggested alternative: 'move_'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                    ^~~~~~
                                    move_
RcppExports.cpp:187:43: error: template argument 1 is invalid
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                           ^
RcppExports.cpp:187:51: error: expected initializer before 'mode'
     Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
                                                   ^~~~
RcppExports.cpp:188:51: error: 'mode' was not declared in this scope
     rcpp_result_gen = Rcpp::wrap(file_code_(path, mode));
                                                   ^~~~
RcppExports.cpp:188:51: note: suggested alternative: 'modf'
     rcpp_result_gen = Rcpp::wrap(file_code_(path, mode));
                                                   ^~~~
                                                   modf
make: *** [/usr/lib/R/etc/Makeconf:166: RcppExports.o] Error 1
ERROR: compilation failed for package ‘fs’
* removing ‘/usr/lib/R/library/fs’

The downloaded source packages are in
        ‘/tmp/RtmppgDNFN/downloaded_packages’
Updating HTML index of packages in '.Library'
Making 'packages.html' ... done
Warning message:
In install.packages("fs", dependencies = TRUE) :
  installation of package ‘fs’ had non-zero exit status

**Comment by commandline-be** [comment]
For this error
make: *** [/usr/lib/R/etc/Makeconf:166 RccpExports.o ] Error 1
this file reads on line 165-166

.cpp.o:
              $(CXX) $(ALL_CPPFLAGS) $(ALL_CXXFLAGS) -c $< -o $@

**Comment by commandline-be** [comment]
First error RcppExports.cpp:9:35: error: 'mode_t' has not been declared
void mkdir_(CharacterVector path, mode_t mode);
^~~~~~

// mkdir_
void mkdir_(CharacterVector path, **mode_t mode**);
RcppExport SEXP _fs_mkdir_(SEXP pathSEXP, SEXP modeSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type path(pathSEXP);
    Rcpp::traits::input_parameter< mode_t >::type mode(modeSEXP);
    mkdir_(path, mode);
    return R_NilValue;
END_RCPP
}

**Comment by adamcooper94** [comment]
Getting the same error:
`RcppExports.cpp:9:35: error: 'mode_t' has not been declared`

Were you able to resolve this?

**Comment by adamcooper94** [comment]
Nevermind, this issue has been resolved. See [here](https://github.com/r-lib/fs/pull/158).

I was able to install fp from source on the following image: `artemklevtsov/r-alpine:latest`.

The issue is that the most recent fp release on CRAN is from 8/18, while this fix occurred in 12/18. To get around this, you can install the master branch directly from the source on github.

1.  Download a zip of the master branch directly from github
2. Unzip and convert the unzipped directory to a gzip `tar -czf fs_master.tar.gz fs-master/`
3. `install.packages('Rcpp', repos='http://cran.us.r-project.org')`
4. `install.packages('/your/path/to/fs_master.tar.gz', repos = NULL, type='source')`
