### ISSUE TITLE
file_touch() should create a file if it doesn't exist

### ISSUE THREAD

**Issue by jimhester** [r-lib/fs#169]

**Comment by mattmalcher** [comment]
Sorry if i'm misreading/misunderstanding.
 
I think the documentation is out of date as it says that it does not create a file, however, it does now create a file, (as per the closed issue?) 
https://github.com/r-lib/fs/blob/7ff16a702fa50c407b4b983ac5a507014a9a92ac/man/file_touch.Rd#L16
