### ISSUE TITLE
Add similar functionality as Sys.glob() for dir_ls

### ISSUE THREAD

**Issue by ralonso-igenomix** [r-lib/fs#170]
Hello,

I think could be interesting that dir_ls could have a full glob path as Sys.glob does, for instance:

files <- Sys.glob("/path1/path2/*/*/*recombine.cov") # native R
files <- dir_ls(glob="/path1/path2/*/*/*recombine.cov") # fs package

Then we could use map_df(read_tsv, .id = "file") 

Many thanks,

Best

**Comment by jimhester** [comment]
I agree! In fact I opened https://github.com/r-lib/fs/issues/173, recently about this, so I am going to close this issue so we don't have a duplicate.
