### ISSUE TITLE
Convenience functions to check file permissions

### ISSUE THREAD

**Issue by jdblischak** [r-lib/fs#172]
It would be convenient to have functions that return TRUE/FALSE depending on the file permissions, e.g. `file_is_readable()`, `file_is_writeable()`, and `file_is_executable()`. Checking for different users could be done with arguments, e.g. `file_is_readable("file.txt", user = TRUE, group = TRUE, other = FALSE)`.

In the short term, I appreciate that I can get this information by parsing `fs::file_info()$permissions`. Below is the simple prototype I am using for now.

```
file_is_executable <- function(f) {
  stopifnot(fs::file_exists(f))
  perms <- fs::file_info(f)$permissions
  perms <- as.character(perms)
  perms <- stringr::str_split_fixed(perms, "", n = 9)
  perms <- as.character(perms)
  if (perms[3] == "x" || perms[6] == "x" || perms[9] == "x") {
    return(TRUE)
  }
  return(FALSE)
}
```

Related question. How can I reliably get the octal format as a number from an `fs_perms` object? My first idea for to determining if a file was executable or not was to check the octal representation for odd numbers.

If I passed the octal representation to `fs_perms()`, then I was able to retrieve it:

```
perms <- fs::fs_perms("644")
class(perms)
## [1] "fs_perms" "integer" 
as.numeric(as.character(as.octmode(perms)))
## [1] 644
```

However, I get a different result if the permissions are created by `file_info()`:

```
f <- fs::file_temp()
fs::file_create(f)
perms <- fs::file_info(f)$permissions
class(perms)
## [1] "fs_perms"
perms
## [1] rw-r--r--
as.numeric(as.character(as.octmode(perms)))
## [1] 100644
```

Shouldn't these be the same since the file was also "644"?

**Comment by cderv** [comment]
> It would be convenient to have functions that return TRUE/FALSE depending on the file permissions

Did you try `fs::file_access` ? (https://fs.r-lib.org/reference/file_access.html)

* is readable : `file_access(path, mode = "read")`
* is writeable : `file_access(path, mode = "write")`
* is executable: `file_access(path, mode = "execute")`

However, you can't test for other users or groups. 🤔

**Comment by jdblischak** [comment]
@cderv Thanks for the tip! `file_access()` does what I need on unix-alike systems. Unfortunately neither my original function nor `file_access()` appear to work on Windows. Here is an example from Git Bash on Windows 10:

```
$touch file.txt
$ls -l file.txt
-rw-r--r-- 1 john 197121 0 Feb  8 08:32 file.txt
$Rscript -e  'fs::file_access(\"file.txt\")'
file.txt
    TRUE
$Rscript -e  'fs::file_access(\"file.txt\", mode = \"execute\")'
file.txt
    TRUE
```

Basically, `file_access(mode = "execute)` always returns `TRUE` on Windows even if the file isn't executable. And the permissions returned by `file_info()` are different on Windows.

Is there a cross-platform method for determining if a file is executable?

**Comment by jdblischak** [comment]
Quick update. The base R function `file.access()` properly returns a `-1` for non-executable files:

```
# In Git Bash
$ rm file.txt
$ touch file.txt
$ ls -l file.txt
-rw-r--r-- 1 john 197121 0 Feb  8 09:11 file.txt
$ Rscript -e  'fs::file_access(\"file.txt\", mode = \"execute\")'
file.txt
    TRUE
$ Rscript -e  'file.access(\"file.txt\", mode = 1)'
file.txt
      -1
```

Is there any way to manipulate file permissions on Windows from R? Neither `Sys.chmod()` nor `fs::file_chmod()` appear to have any effect. Is manipulating file permissions just something I have to accept can't be cross-platform? Does either fs or libuv have a table of which functions are cross-platform and which are not? The libuv docs claim that Windows is a supported platform, but clearly that does not extend to all of its functionality: https://github.com/r-lib/fs/blob/master/src/libuv/SUPPORTED_PLATFORMS.md

**Comment by jimhester** [comment]
There is no executable bit on windows, the only thing you can control is read and write ability. Whether a file is executable depends only on the file extension on windows.

**Comment by jimhester** [comment]
Also how I would test for group permissions is like

```r
(fs::file_info("test.html")$permissions & "g=rw") == "g=rw"
```
```

**Comment by jdblischak** [comment]
> There is no executable bit on windows, the only thing you can control is read and write ability.

OK. Good to know. Could I send a PR to update the documentation? One of the big reasons I use fs is for its cross-platform capabilities, so it's nice to know when a given task is impossible to implement in a cross-platform manner.

> Whether a file is executable depends only on the file extension on windows.

Would it be worthwhile to update `file_access()` to check the file extension on Windows? Unfortunately I wasn't able to find a straight-forward list (e.g. this [SO question](https://superuser.com/questions/228680/on-windows-what-filename-extensions-denote-an-executable/228693)).

Also, in the documentation for `fs_perms()`, it states:

> On Windows the permissions are displayed as a 3 character string where the third character is only `-` or `x`.

On my Windows 10 machine, both files and directories always have a `-`, never a `x`, even for files like `file.bat`. Are there some Windows machines that do display an `x`?

Lastly, what is the motivation for always returning `TRUE` when checking if a file is executable on Windows? I'm not sure there is a great answer, but returning `FALSE` would at least be consistent with `base::file.access()`.

> (fs::file_info("test.html")$permissions & "g=rw") == "g=rw"

That works! I was surprised that an `fs_perms` object was able to combine with a character vector, but now I see that you've defined [`&.fs_perms`](https://github.com/r-lib/fs/blob/master/R/fs_perms.R#L169). Would this also be worth documenting?

**Comment by jimhester** [comment]
Yes documenting both the executable issues on Windows and testing for permissions would be very useful!
