### ISSUE TITLE
Case of Windows drive for tidy paths

### ISSUE THREAD

**Issue by jdblischak** [r-lib/fs#174]
I am getting errors on winbuilder due to differences in the case of the Windows drive.  `fs::path_wd()` returns the Windows drive in lower case (`d:/`) while `fs::path_temp()` returns it in upper case (`D:/`). This causes problems when I try to do path manipulations like `fs::path_rel()`, which do not take the case-insensitivity of the file system into account.

Would it be possible to have `fs::path_tidy()` ensure that the Windows drive is always capitalized?

For more details, please see the test package I created: [fswintest](https://github.com/jdblischak/fswintest)

**Comment by jimhester** [comment]
I think windows drive letters _must_ always be capitalized, so if `path_wd()` is returning a lower case letter it is a bug.

**Comment by jdblischak** [comment]
> if `path_wd()` is returning a lower case letter it is a bug.

Unfortunately `getwd()` also returns the lowercase `d:/`. See this [test](https://github.com/jdblischak/fswintest/blob/master/tests/testthat/test-fs.R#L71).

**Comment by jdblischak** [comment]
> if `path_wd()` is returning a lower case letter it is a bug.

@jimhester To follow-up on this, I don't think the problem is with `path_wd()`. For some reason the winbuilder server likes to use the lower-case `d:/`. For example, the start of each `00check.log` file produced by winbuilder uses `d:/`:

```
* using log directory 'd:/RCompile/CRANguest/R-release/fswintest.Rcheck'
```

Thus instead of trying to get `path_wd()` to return `D:/`, I think it would be better to enhance `path_tidy()` to automatically capitalize the Windows drive. This way arbitrary path computations with mismatched case of the Windows drive, e.g. `path_rel("d:/Users/a", "D:/Users/b")`, would properly return `"../a"` instead of `"../../../d:/Users/a"`.

**Comment by jimhester** [comment]
Fixed by https://github.com/r-lib/fs/commit/7634eb07595cccfc3e8117b1b36c35ca46dc5226

**Comment by jdblischak** [comment]
Thanks @jimhester! I installed from GitHub and confirmed that `path_rel("d:/Users/a", "D:/Users/b") == "../a"`. This will make testing on winbuilder so much easier. I look forward to the next release!

**Comment by jimhester** [comment]
This is actually in the latest CRAN release https://github.com/r-lib/fs/releases/tag/v1.2.7

**Comment by jdblischak** [comment]
> This is actually in the latest CRAN release https://github.com/r-lib/fs/releases/tag/v1.2.7

Ah, nice! I quickly glanced at `NEWS.md` and thought that version 1.2.7 was the development version since there are no entries between the headings at the moment.
