### ISSUE TITLE
path_package should work with `pkgload::load_all()`

### ISSUE THREAD

**Issue by jimhester** [r-lib/fs#175]
like `system.file()` does.

**Comment by ijlyttle** [comment]
I followed this from r-lib/usethis#347; this looks super!

Would this also solve (what appears to me) a similar issue when using htmlwidgets, for example, rstudio/leaflet#52? If so, would we need to do anything other than wait for everything to make its way to CRAN?

Thanks!

**Comment by jennybc** [comment]
I think a related conversation is going on in https://github.com/r-lib/pkgload/issues/69, so I suggest you explicitly raise this in both places. I'm not up-to-speed enough on those applications to give you an answer.

**Comment by jimhester** [comment]
@ijlyttle It would assuming they use `fs::path_package()`, but understandably they may not.

**Comment by ijlyttle** [comment]
@jennybc and @jimhester,

I'll raise the point in both places, thanks!
