### ISSUE TITLE
create file_download() as a wrapper for download.file()?

### ISSUE THREAD

**Issue by davidkane9** [r-lib/fs#176]
As best I can tell, there is no way to download files from the web in the fs package. This strikes me as an unfortunate lacuna. Would it be useful to have a new function, fs::file_download() would would do what the base function download.file() does, but in a more fs friendly way?

**Comment by jennybc** [comment]
Re: "more friendly" ... the logic in `usethis::use_course()` for naming the downloaded thing might be nice to move over here, if `fs::file_download()` happens.

https://github.com/r-lib/usethis/blob/0adfb5d902cc20bba3e324e52e234695f3a81a28/R/course.R#L173-L209

It consults the `Content-Disposition` header to figure out a decent filename and falls back to something computed from the URL. The path sanitization used there is already taken from fs anyway. I've always been frustrated that `download.file()` offers no default strategy for `destfile`. It seems very humane to offer this, as long as you are careful about path sanitization and not overwriting an existing file.

**Comment by gaborcsardi** [comment]
Downloading files is out of scope for fs.
