### ISSUE TITLE
fs Installation libuv

### ISSUE THREAD

**Issue by zillerm** [r-lib/fs#178]
Good morning,

I ran into some installation issues of fs using R version  3.5.1. 
Everything works fine until it tries to find the libuv.so file:
...
HAVE_DTRACE=0
make[1]: Entering directory `/tmp/RtmprBb2lI/R.INSTALL2a6bc2c30dcc1/fs/src/libuv'
	 CC       src/libuv_la-fs-poll.lo

CC       src/libuv_la-inet.lo
  CC       src/libuv_la-threadpool.lo
  CC       src/libuv_la-uv-common.lo
  CC       src/libuv_la-version.lo
  CC       src/unix/libuv_la-async.lo
  CC       src/unix/libuv_la-core.lo
  CC       src/unix/libuv_la-dl.lo
  CC       src/unix/libuv_la-fs.lo
  CC       src/unix/libuv_la-getaddrinfo.lo
  CC       src/unix/libuv_la-getnameinfo.lo
  CC       src/unix/libuv_la-loop-watcher.lo
  CC       src/unix/libuv_la-loop.lo
  CC       src/unix/libuv_la-pipe.lo
  CC       src/unix/libuv_la-poll.lo
  CC       src/unix/libuv_la-process.lo
  CC       src/unix/libuv_la-signal.lo
  CC       src/unix/libuv_la-stream.lo
  CC       src/unix/libuv_la-tcp.lo
  CC       src/unix/libuv_la-thread.lo
  CC       src/unix/libuv_la-timer.lo
  CC       src/unix/libuv_la-tty.lo
  CC       src/unix/libuv_la-udp.lo
  CC       src/unix/libuv_la-linux-core.lo
  CC       src/unix/libuv_la-linux-inotify.lo
  CC       src/unix/libuv_la-linux-syscalls.lo
  CC       src/unix/libuv_la-procfs-exepath.lo
  CC       src/unix/libuv_la-proctitle.lo
  CC       src/unix/libuv_la-sysinfo-loadavg.lo
  CC       src/unix/libuv_la-sysinfo-memory.lo
  CCLD     libuv.la
/usr/bin/ld: cannot find libuv.so.1: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [libuv.la] Error 1
make[1]: Leaving directory `/tmp/RtmprBb2lI/R.INSTALL2a6bc2c30dcc1/fs/src/libuv'
make: *** [libuv/.libs/libuv.a] Error 2
ERROR: compilation failed for package 'fs'

Thanks a lot for you help!
Michael

**Comment by jimhester** [comment]
I am not sure what is going wrong and unfortunately there is not enough information in the error message for me to debug it.

What system are you trying to compile fs on?

**Comment by serbinsh** [comment]
Not sure if its related but with Xcode 10.2 and latest command line tools I cannot install R fs 
```
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPDFPage.h:15,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPDFDocument.h:16,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:23,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from src/unix/darwin-proctitle.c:30:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPDFDictionary.h:116:15: error: expected identifier or '(' before '^' token
 typedef bool (^CGPDFDictionaryApplierBlock)(const char * key,
               ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGPDFDictionary.h:126:5: error: unknown type name 'CGPDFDictionaryApplierBlock'; did you mean 'CGPDFDictionaryApplierFunction'?
     CGPDFDictionaryApplierBlock cg_nullable block, void * __nullable info)
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
     CGPDFDictionaryApplierFunction
make[1]: *** [src/unix/libuv_la-darwin-proctitle.lo] Error 1
make: *** [libuv/.libs/libuv.a] Error 2
ERROR: compilation failed for package ‘fs’
* removing ‘/Users/sserbin/R/library/fs’
* restoring previous ‘/Users/sserbin/R/library/fs’
Error in i.p(...) :
  (converted from warning) installation of package ‘/var/folders/xp/h3k9vf3n2jx181ts786_yjrn9c2gjq/T//RtmpEd8XSa/file2af95bb36732/fs_1.2.7.9001.tar.gz’ had non-zero exit status****
```

or the latest "source" from CRAN?  THis is on macOS Mojave

**Comment by zib0** [comment]
Same problem here, on Mojave Xcode 10.2.1

**Comment by jimhester** [comment]
You likely need to install the missing Xcode headers to compile fs, e.g. try running `open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` in a shell terminal to install them.

**Comment by zib0** [comment]
Tried install separately, doesn’t help, seems a function name changed or something is missing from the new comma line tool.

**Comment by serbinsh** [comment]
Indeed....slightly different thread but I think the same issue arising from changes to CLTs: https://github.com/r-lib/xml2/issues/232

After running: 

sudo installer -pkg /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg -target /

and the next installers I was finally able to get xml2 installed.  Seems that removing /usr/include in XCODE 10 is causing problems, who knew! (sarcasm). 

That said, it looks like you also attempted to get the headers and is still not working....

**Comment by zib0** [comment]
I solved the problem by change compiler to clang7 provided here: https://cran.r-project.org/bin/macosx/tools/ and have Makevar:
CC=/usr/local/clang7/bin/clang
CXX=/usr/local/clang7/bin/clang++
CXX11=/usr/local/clang7/bin/clang++
CXX14=/usr/local/clang7/bin/clang++
CXX17=/usr/local/clang7/bin/clang++
CXX1X=/usr/local/clang7/bin/clang++
LDFLAGS=-L/usr/local/clang7/lib -L/usr/local/Cellar/gcc/8.3.0_2/lib
CXXFLAGS=-I/usr/local/clang7/include -I/usr/local/Cellar/gcc/8.3.0_2/include
CPPFLAGS=-I/usr/local/clang7/include -I/usr/local/Cellar/gcc/8.3.0_2/include
It compiled through now. Since R used those specific clang version, you need extra careful.
