### ISSUE TITLE
Option to set depth in dir_tree()

### ISSUE THREAD

**Issue by dfalster** [r-lib/fs#185]
What an awesome package! Thanks for your efforts. 

I love the `dir_tree` function - this will replace my local hack. 

I note the function only gives the whole tree. Would it be possible to expose the [recursive option used within the function](https://github.com/r-lib/fs/blob/master/R/tree.R#L6) as an argument for `dir_tree`? Even better, could we set a depth for the file list? 

I can image using this often. When I introduce a set of files, I usually start with high-level directories (depth=1). I may then given an example of a lower level directory.

**Comment by jimhester** [comment]
This relates to https://github.com/r-lib/fs/issues/187, maybe the best solution would be to pass the dots _and_ allow setting a max recursion depth in `dir_ls()`.

**Comment by dfalster** [comment]
Yeah, that would be a great solution

**Comment by russHyde** [comment]
I've just implemented passing along arguments from dir_tree to dir_ls; this could be implemented as:

```
dir_ls <- function(path = ".", all = FALSE, recursive = FALSE, type = "any",
                   glob = NULL, regexp = NULL, invert = FALSE, fail = TRUE,
                   max_depth = NULL, ...) {
  assert_no_missing(path)

  old <- path_expand(path)

  files <- as.character(dir_map(old, identity, all, recursive, type, fail))

  if (!is.null(max_depth)) {
    too_deep_regex <- paste0("(.*/){", max_depth ,"}.*$")
    files <- grep(too_deep_regex, files, value = TRUE, invert = TRUE)
  }
  path_filter(files, glob, regexp, invert = invert, ...)
}
```

[I appreciate that there are neater ways to do regexes now]

Running this in the `fs` package directory gives:

```
dir_tree(recursive = TRUE, max_depth = 2)
.
├── DESCRIPTION
├── LICENSE.md
├── NAMESPACE
├── NEWS.md
├── R
│   ├── RcppExports.R
│   ├── access.R
│   ├── copy.R
...
files of the form
./def
./dir1
./some_dir/abc

```

I was wondering whether you agree that this is the correct implementation for max_depth wrt 0-based and 1-based counting? For example, it could be argued that with max_depth=0, you should see the contents of the current-working directory

**Comment by jimhester** [comment]
Thanks @russHyde! I think we should probably handle the depth as an additional argument passed to the C++ code in `dir_map()`.

Since this will be a more invasive change I will probably take a look at it in the next day or two.

**Comment by russHyde** [comment]
No probs. C-level stuff is beyond my domain ...

**Comment by dfalster** [comment]
Look promising @russHyde !

**Comment by jimhester** [comment]
This is done now, https://github.com/r-lib/fs/commit/70e3317e82fe485506559782bb52a0232776f909

`dir_tree(recurse = 2)` will now use recurse to a max depth of 2.

**Comment by dfalster** [comment]
Awesome! thanks so much @jimhester - works wonderfully. Will start using immediately!
