### ISSUE TITLE
"..." pass-along in fs::dir_tree?

### ISSUE THREAD

**Issue by russHyde** [r-lib/fs#187]
Would it be useful to others to have a pass-along in the args to `dir_tree`, such that additional args can be passed to `dir_ls`.

My use case is so that I can see ".RProj.user", ".gitignore" etc in the tree. That is, I'd like to be able to

```
fs::dir_tree(".", all = TRUE) # all is passed to dir_ls
```

**Comment by jimhester** [comment]
Yes, good idea, feel free to open a PR if you would like!

**Comment by russHyde** [comment]
Will do. Cheers Jim
