### ISSUE TITLE
Confusing error message with create_package

### ISSUE THREAD

**Issue by kwstat** [r-lib/fs#196]
I had this experience:
```
create_package("junk")
Error: [ENOENT] Failed to stat 'junk': no such file or directory
```
This error message is confusing.  I think it really means, "R cannot write to the current working directory".

Once I `setwd()` to my home folder, then `create_package()` works fine.

It would be helpful for most people if the error message was more clear.

**Comment by jimhester** [comment]
I agree, it is a fs issue, here is a reprex without usethis

``` r
library(fs)

f <- dir_create(fs::file_temp())

file_chmod(f, "u-w")
setwd(f)
dir_create("foo")
#> Error: [ENOENT] Failed to stat 'foo': no such file or directory
```

<sup>Created on 2019-05-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jimhester** [comment]
Sorry this was confusing, should now be fixed

``` r
library(fs)

f <- dir_create(fs::file_temp())

file_chmod(f, "u-w")
setwd(f)
dir_create("foo")
#> Error: [EACCES] Failed to make directory 'foo': permission denied
```

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
