### ISSUE TITLE
fs compile warns + fails link using Rtools 3.5.0.4 under RStudio 1.2 on Windows 10 Pro

### ISSUE THREAD

**Issue by BloomingAzaleas** [r-lib/fs#199]
RStudio automates R pkg updates from CRAN binaries or builds using local Rtools from source if source newer.  Below Rstudio console log snippets of the interesting info.  Repetative compiler output elided.
> install.packages("fs")
Installing package into ‘C:/Users/REDACTED/lib/R’
(as ‘lib’ is unspecified)

There is a binary version available but the source version is later:
binary source needs_compilation
fs  1.2.7  1.3.0              TRUE

installing the source package ‘fs’

trying URL 'https://cran.rstudio.com/src/contrib/fs_1.3.0.tar.gz'
Content type 'application/x-gzip' length 812557 bytes (793 KB)
downloaded 793 KB

* installing *source* package 'fs' ...
** package 'fs' successfully unpacked and MD5 sums checked
** using staged installation
** libs
C:/Rtools/3.5/mingw_64/bin/g++  -std=gnu++11 -I"C:/PROGRA~1/R/R-36~1.X/include" -DNDEBUG -I./libuv/include -D_WIN32_WINNT=0x0600 -DSTRICT_R_HEADERS -I. -I"C:/Users/REDACTED/lib/R/Rcpp/include"        -O2 -Wall  -mtune=generic -c error.cc -o error.o

and so on...

-o dir.o
-o fs.o
-o link.o
-o path.o
-o file.o
-o utils.o
-o id.o
-o windows/getmode.o
-o RcppExports.o

/usr/bin/make --directory=libuv -f Makefile.mingw \
	CC="C:/Rtools/3.5/mingw_64/bin/gcc " CFLAGS="-O2 -Wall  -std=gnu99 -mtune=generic -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600  " AR="C:/Rtools/3.5/mingw_64/bin/ar" RANLIB="C:/Rtools/3.5/mingw_64/bin/ranlib" \
	HAVE_DTRACE=0

make[1]: Entering directory '/tmp/Rtmp4okXJK/R.INSTALL23ec30f53d48/fs/src/libuv'

C:/Rtools/3.5/mingw_64/bin/gcc  -O2 -Wall  -std=gnu99 -mtune=generic -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600   -c -o src/fs-poll.o src/fs-poll.c

and so on...
-o src/inet.o src/inet.c
-o src/threadpool.o src/threadpool.c
-o src/uv-common.o src/uv-common.c
-o src/version.o src/version.c
-o src/win/async.o src/win/async.c
-o src/win/core.o src/win/core.c
-o src/win/detect-wakeup.o src/win/detect-wakeup.c
-o src/win/dl.o src/win/dl.c
-o src/win/error.o src/win/error.c
-o src/win/fs-event.o src/win/fs-event.c

C:/Rtools/3.5/mingw_64/bin/gcc  -O2 -Wall  -std=gnu99 -mtune=generic -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600   -c -o src/win/fs.o src/win/fs.c
src/win/fs.c: In function 'fs__unlink':
src/win/fs.c:784:5: warning: missing braces around initializer [-Wmissing-braces]
     FILE_BASIC_INFORMATION basic = { 0 };
     ^
src/win/fs.c:784:5: warning: (near initialization for 'basic.CreationTime') [-Wmissing-braces]

-o src/win/getaddrinfo.o src/win/getaddrinfo.c
-o src/win/getnameinfo.o src/win/getnameinfo.c
-o src/win/handle.o src/win/handle.c
-o src/win/loop-watcher.o src/win/loop-watcher.c

C:/Rtools/3.5/mingw_64/bin/gcc  -O2 -Wall  -std=gnu99 -mtune=generic -Iinclude -Isrc -Isrc/win -DWIN32_LEAN_AND_MEAN -D_WIN32_WINNT=0x0600   -c -o src/win/pipe.o src/win/pipe.c
src/win/pipe.c: In function 'uv_pipe_chmod':
src/win/pipe.c:2140:3: warning: missing braces around initializer [-Wmissing-braces]
   SID_IDENTIFIER_AUTHORITY sid_world = SECURITY_WORLD_SID_AUTHORITY;
   ^
src/win/pipe.c:2140:3: warning: (near initialization for 'sid_world.Value') [-Wmissing-braces]

-o src/win/poll.o src/win/poll.c
-o src/win/process-stdio.o src/win/process-stdio.c
-o src/win/process.o src/win/process.c
-o src/win/req.o src/win/req.c
-o src/win/signal.o src/win/signal.c
-o src/win/stream.o src/win/stream.c
-o src/win/tcp.o src/win/tcp.c
-o src/win/thread.o src/win/thread.c
-o src/win/timer.o src/win/timer.c
-o src/win/tty.o src/win/tty.c
-o src/win/udp.o src/win/udp.c
-o src/win/util.o src/win/util.c
-o src/win/winapi.o src/win/winapi.c
-o src/win/winsock.o src/win/winsock.c

C:/Rtools/3.5/mingw_64/bin/ar crs libuv.a src/fs-poll.o src/inet.o src/threadpool.o src/uv-common.o src/version.o src/win/async.o src/win/core.o src/win/detect-wakeup.o src/win/dl.o src/win/error.o src/win/fs-event.o src/win/fs.o src/win/getaddrinfo.o src/win/getnameinfo.o src/win/handle.o src/win/loop-watcher.o src/win/pipe.o src/win/poll.o src/win/process-stdio.o src/win/process.o src/win/req.o src/win/signal.o src/win/stream.o src/win/tcp.o src/win/thread.o src/win/timer.o src/win/tty.o src/win/udp.o src/win/util.o src/win/winapi.o src/win/winsock.o

make[1]: Leaving directory '/tmp/Rtmp4okXJK/R.INSTALL23ec30f53d48/fs/src/libuv'

C:/Rtools/3.5/mingw_64/bin/g++ -shared -s -static-libgcc -o fs.dll tmp.def error.o dir.o fs.o link.o path.o file.o utils.o id.o windows/getmode.o RcppExports.o ./libuv/libuv.a -lpthread -lws2_32 -lkernel32 -lpsapi -liphlpapi -lshell32 -luserenv -LC:/PROGRA~1/R/R-36~1.X/bin/x64 -lR
: symbol not definedON_PREFIX
: symbol not definedON_PREFIX_LEN
: symbol not definedATH_PREFIX
: symbol not definedATH_PREFIX_LEN
: symbol not defined_fs
: symbol not definedTH_PREFIX
: symbol not definedTH_PREFIX_LEN
: symbol not definedle_code_Sst
: symbol not definedth_tidy_RKSs
: symbol not definedt_last_callv
: symbol not definedpand_windowsPKc
: symbol not definedt_dirent_typePKcRK16uv_dirent_type_t
: symbol not defined_windows_pathRKSs
: symbol not definednk_create_hard_N4Rcpp6VectorILi16ENS_15PreserveStorageEEES2_
: symbol not definedring_to_try_errorRKSs
: symbol not definednk_create_symbolic_N4Rcpp6VectorILi16ENS_15PreserveStorageEEES2_
: symbol not definedception_to_condition_templateIN4Rcpp9exceptionEEP7SEXPRECRKT_b
: symbol not definedception_to_condition_templateISt9exceptionEP7SEXPRECRKT_b
: symbol not definede_N4Rcpp6VectorILi16ENS_15PreserveStorageEEES2_
: symbol not definedh_N4Rcpp6VectorILi19ENS_15PreserveStorageEEEPKc
: symbol not definedt_N4Rcpp6VectorILi16ENS_15PreserveStorageEEEb
: symbol not definedy_N4Rcpp6VectorILi16ENS_15PreserveStorageEEE
: symbol not definedod_N4Rcpp6VectorILi16ENS_15PreserveStorageEEENS0_ILi13ES1_EE
: symbol not definedwn_N4Rcpp6VectorILi16ENS_15PreserveStorageEEEii
: symbol not definedir_N4Rcpp6VectorILi16ENS_15PreserveStorageEEEt
: symbol not definedir_N4Rcpp6VectorILi16ENS_15PreserveStorageEEE
: symbol not definedch_N4Rcpp6VectorILi16ENS_15PreserveStorageEEEdd
: symbol not definedrs_v
: symbol not definedess_N4Rcpp6VectorILi16ENS_15PreserveStorageEEEi
: symbol not definedate_N4Rcpp6VectorILi16ENS_15PreserveStorageEEEt
: symbol not defined_mapN4Rcpp13Function_ImplINS_15PreserveStorageEEEPKcbiyP13CollectorListb
: symbol not definedand_N4Rcpp6VectorILi16ENS_15PreserveStorageEEEb
: symbol not definedups_v
: symbol not definedmodetPc
: symbol not definedink_N4Rcpp6VectorILi16ENS_15PreserveStorageEEE
: symbol not definedanup_v
: symbol not defined_map_N4Rcpp6VectorILi16ENS_15PreserveStorageEEENS_13Function_ImplIS1_EEbNS0_ILi13ES1_EEyb
: symbol not definedmode_PKct
: symbol not definedlize_N4Rcpp6VectorILi16ENS_15PreserveStorageEEE
: symbol not defined_pathPcPKcyy
: symbol not definedrintfPcyPKcz
: symbol not definedmode_t
: symbol not definedyfile_N4Rcpp6VectorILi16ENS_15PreserveStorageEEES2_b
: symbol not definedgrnam_N4Rcpp6VectorILi16ENS_15PreserveStorageEEE
: symbol not definedpwnam_N4Rcpp6VectorILi16ENS_15PreserveStorageEEE
: symbol not defineddlink_N4Rcpp6VectorILi16ENS_15PreserveStorageEEE
: symbol not defined1stack_tracePKciE3fun
: symbol not defined0rcpp_get_stack_tracevE3fun
: symbol not defined0rcpp_set_stack_traceP7SEXPRECE3fun
: symbol not defineddataptrP7SEXPRECE3fun
: symbol not defineddemangleRKSsE3fun
: symbol not defined4Rcpp8internal12exitRNGScopeEvE3fun
: symbol not defined4Rcpp8internal13enterRNGScopeEvE3fun
: symbol not definedinyformat6detail10formatImplERSoPKcPKNS0_9FormatArgEi
: symbol not definedinyformat6detail15formatTruncatedIiEEvRSoRKT_i
: symbol not definedinyformat6detail21streamStateFromFormatERSoRbRiPKcPKNS0_9FormatArgES3_i
: symbol not definedinyformat6detail9FormatArg10formatImplIPKcEEvRSoS4_S4_iPKv
: symbol not definedinyformat6detail9FormatArg10formatImplIiEEvRSoPKcS5_iPKv
: symbol not definedinyformat6detail9FormatArg9toIntImplIPKcEEiPKv
: symbol not definedinyformat6detail9FormatArg9toIntImplIiEEiPKv
: symbol not definedinyformat6formatIIEEESsPKcDpRKT_
: symbol not definedinyformat6formatIIPKcEEESsS2_DpRKT_
: symbol not definedinyformat6formatIIPKcS2_EEESsS2_DpRKT_
: symbol not definedinyformat6formatIIPKciEEESsS2_DpRKT_
: symbol not definedinyformat6formatIIiEEESsPKcDpRKT_
: symbol not definedpp10RstreambufILb0EE4syncEv
: symbol not definedpp10RstreambufILb0EE6xsputnEPKcx
: symbol not definedpp10RstreambufILb0EE8overflowEi
: symbol not definedpp10RstreambufILb0EED0Ev
: symbol not definedpp10RstreambufILb0EED1Ev
: symbol not definedpp10RstreambufILb1EE4syncEv
: symbol not definedpp10RstreambufILb1EE6xsputnEPKcx
: symbol not definedpp10RstreambufILb1EE8overflowEi
: symbol not definedpp10RstreambufILb1EED0Ev
: symbol not definedpp10RstreambufILb1EED1Ev
: symbol not definedpp10eval_errorD0Ev
: symbol not definedpp10eval_errorD1Ev
: symbol not definedpp14not_compatibleC1IIPKcEEES3_DpOT_
: symbol not definedpp14not_compatibleC1IIPKcS3_EEES3_DpOT_
: symbol not definedpp14not_compatibleC1IIPKciEEES3_DpOT_
: symbol not definedpp14not_compatibleC1IIRKPKcEEES3_DpOT_
: symbol not definedpp14not_compatibleC1IIiEEEPKcDpOT_
: symbol not definedpp14not_compatibleD0Ev
: symbol not definedpp14not_compatibleD1Ev
: symbol not definedpp4growINS_6VectorILi16ENS_15PreserveStorageEEEEEP7SEXPRECRKT_S5_
: symbol not definedpp4stopERKSs
: symbol not definedpp4stopIIEEEvPKcDpOT_
: symbol not definedpp6r_castILi13EEEP7SEXPRECS2_
: symbol not definedpp6r_castILi14EEEP7SEXPRECS2_
: symbol not definedpp6r_castILi16EEEP7SEXPRECS2_
: symbol not definedpp8RostreamILb0EED0Ev
: symbol not definedpp8RostreamILb0EED1Ev
: symbol not definedpp8RostreamILb1EED0Ev
: symbol not definedpp8RostreamILb1EED1Ev
: symbol not definedpp8internal10basic_castILi10EEEP7SEXPRECS3_
: symbol not definedpp8internal10basic_castILi13EEEP7SEXPRECS3_
: symbol not definedpp8internal10basic_castILi14EEEP7SEXPRECS3_
: symbol not definedpp8internal10resumeJumpEP7SEXPREC
: symbol not definedpp8internal12exitRNGScopeEv
: symbol not definedpp8internal12primitive_asIbEET_P7SEXPREC
: symbol not definedpp8internal12primitive_asIdEET_P7SEXPREC
: symbol not definedpp8internal12primitive_asIiEET_P7SEXPREC
: symbol not definedpp8internal12primitive_asItEET_P7SEXPREC
: symbol not definedpp8internal12primitive_asIyEET_P7SEXPREC
: symbol not definedpp8internal13r_init_vectorILi13EEEvP7SEXPREC
: symbol not definedpp8internal3nthEP7SEXPRECi
: symbol not definedpp9Rcpp_evalEP7SEXPRECS1_
: symbol not definedpp9exceptionC1EPKcb
: symbol not definedpp9exceptionD0Ev
: symbol not definedpp9exceptionD1Ev
: symbol not definedcpp10eval_error4whatEv
: symbol not definedcpp14not_compatible4whatEv
: symbol not definedcpp9exception4whatEv
: symbol not defined5ctypeIcE8do_widenEc
: symbol not defined5basic_stringbufIcSt11char_traitsIcESaIcEED1Ev
: symbol not definedvectorISsSaISsEED1Ev
: symbol not definedRcpp8RostreamILb0EEE0_So
: symbol not definedRcpp8RostreamILb1EEE0_So
: symbol not definedRcpp10RstreambufILb0EEE
: symbol not definedRcpp10RstreambufILb1EEE
: symbol not definedRcpp10eval_errorE
: symbol not definedRcpp14not_compatibleE
: symbol not definedRcpp17LongjumpExceptionE
: symbol not definedRcpp8RostreamILb0EEE
: symbol not definedRcpp8RostreamILb1EEE
: symbol not definedRcpp8internal20InterruptedExceptionE
: symbol not definedRcpp9exceptionE
: symbol not defined9exception
: symbol not definedRcpp10RstreambufILb0EEE
: symbol not definedRcpp10RstreambufILb1EEE
: symbol not definedRcpp10eval_errorE
: symbol not definedRcpp14not_compatibleE
: symbol not definedRcpp17LongjumpExceptionE
: symbol not definedRcpp8RostreamILb0EEE
: symbol not definedRcpp8RostreamILb1EEE
: symbol not definedRcpp8internal20InterruptedExceptionE
: symbol not definedRcpp9exceptionE
: symbol not defined9exception
: symbol not definedRcpp8RostreamILb0EEE
: symbol not definedRcpp8RostreamILb1EEE
: symbol not definedRcpp10RstreambufILb0EEE
: symbol not definedRcpp10RstreambufILb1EEE
: symbol not definedRcpp10eval_errorE
: symbol not definedRcpp14not_compatibleE
: symbol not definedRcpp8RostreamILb0EEE
: symbol not definedRcpp8RostreamILb1EEE
: symbol not definedRcpp9exceptionE
: symbol not definedn24_N4Rcpp8RostreamILb0EED0Ev
: symbol not definedn24_N4Rcpp8RostreamILb0EED1Ev
: symbol not definedn24_N4Rcpp8RostreamILb1EED0Ev
: symbol not definedn24_N4Rcpp8RostreamILb1EED1Ev
: symbol not definedtack_tracePKciE3fun
: symbol not definedcpp_get_stack_tracevE3fun
: symbol not definedcpp_set_stack_traceP7SEXPRECE3fun
: symbol not definedtaptrP7SEXPRECE3fun
: symbol not definedmangleRKSsE3fun
: symbol not definedcpp8internal12exitRNGScopeEvE3fun
: symbol not definedcpp8internal13enterRNGScopeEvE3fun
: symbol not definedcess_
: symbol not definedmod_
: symbol not definedown_
: symbol not definedeanup_
: symbol not definedpyfile_
: symbol not definedeate_
: symbol not definedr_map_
: symbol not definedpand_
: symbol not definedle_code_
: symbol not definedtgrnam_
: symbol not definedtmode_
: symbol not definedtpwnam_
: symbol not definedoups_
: symbol not definednk_create_hard_
: symbol not definednk_create_symbolic_
: symbol not defineddir_
: symbol not definedve_
: symbol not definedth_
: symbol not definedadlink_
: symbol not definedalize_
: symbol not defineddir_
: symbol not definedat_
: symbol not definedrmode_
: symbol not defineddy_
: symbol not defineduch_
: symbol not definedlink_
: symbol not defineders_
: symbol not definedrncmp
: symbol not definedose
: symbol not defineddir
: symbol not defineddtemp
: symbol not defineden
: symbol not definedad
: symbol not defineddir
: symbol not definedandir
: symbol not definedlink
: symbol not definedite
: symbol not definedrogram_args
: symbol not definedrogram_env
: symbol not definedlIoEx
: symbol not definedlSynchronousIo
: symbol not definedeSymbolicLinkW
: symbol not definednalPathNameByHandleW
: symbol not definedeuedCompletionStatusEx
: symbol not definedalizeConditionVariable
: symbol not definediceIoControlFile
: symbol not definedryDirectoryFile
: symbol not definedryInformationFile
: symbol not definedrySystemInformation
: symbol not definedryVolumeInformationFile
: symbol not definedInformationFile
: symbol not definedRegisterSuspendResumeNotification
: symbol not definedStatusToDosError
: symbol not definedleCompletionNotificationModes
: symbol not definednEventHook
: symbol not definedConditionVariableCS
: symbol not definedConditionVariableSRW
: symbol not definedllConditionVariable
: symbol not definedonditionVariable
: symbol not definedcmd_arg
: symbol not defined_condition
: symbol not definedlloc
: symbol not definednvert_utf16_to_utf8
: symbol not definednvert_utf8_to_utf16
: symbol not definedunt_bufs
: symbol not definedeate_nul_handle
: symbol not definedee
: symbol not defined_poll_close
: symbol not defined_poll_endgame
: symbol not defined_scandir_cleanup
: symbol not definedtaddrinfo_translate_error
: symbol not definedtpwuid_r
: symbol not definedtime
: symbol not definedit_detect_system_wakeup
: symbol not definedop_close
: symbol not definedop_configure
: symbol not definedlloc
: symbol not definedxt_timeout
: symbol not definedce_init
: symbol not definedpe_insert_pending_socket
: symbol not definedpe_pause_read
: symbol not definedpe_stop_read
: symbol not definedpe_unpause_read
: symbol not definedalloc
: symbol not definedgnal_dispatch
: symbol not definedgnal_start
: symbol not definedcket_sockopt
: symbol not defineddio_create
: symbol not defineddio_destroy
: symbol not defineddio_handle
: symbol not defineddio_noinherit
: symbol not defineddio_size
: symbol not defineddio_verify
: symbol not definedrdup
: symbol not definedrndup
: symbol not definedp_bind
: symbol not definedp_connect
: symbol not definedp_try_write
: symbol not definedy_try_write
: symbol not definedp_bind
: symbol not definedp_recv_start
: symbol not definedp_recv_stop
: symbol not definedp_send
: symbol not definedp_set_membership6
: symbol not definedp_try_send
: symbol not definedil_init
: symbol not definedke_all_loops
: symbol not definedrk_done
: symbol not definedrk_submit
: symbol not definedept
: symbol not definedive_tcp_streams_threshold
: symbol not definedive_udp_streams_threshold
: symbol not definedr_ip4_any_
: symbol not definedr_ip6_any_
: symbol not definednc_close
: symbol not definednc_endgame
: symbol not definednc_init
: symbol not definednc_send
: symbol not definedkend_fd
: symbol not definedkend_timeout
: symbol not definedrier_destroy
: symbol not definedrier_init
: symbol not definedrier_wait
: symbol not defined_init
: symbol not definedcel
: symbol not definedir
: symbol not definedck_init
: symbol not definedck_invoke
: symbol not definedck_start
: symbol not definedck_stop
: symbol not definedse
: symbol not definedd_broadcast
: symbol not definedd_destroy
: symbol not definedd_init
: symbol not definedd_signal
: symbol not definedd_timedwait
: symbol not definedd_wait
: symbol not definedsole_init
: symbol not defined_info
: symbol not definedrent_pid
: symbol not defined
: symbol not definedault_loop
: symbol not definedectory_watcher_buffer_size
: symbol not definedable_stdio_inheritance
: symbol not definedlose
: symbol not definedrror
: symbol not definedpen
: symbol not definedym
: symbol not defined_name
: symbol not definedpath
: symbol not definedal_error
: symbol not definedeno
: symbol not definede_cpu_info
: symbol not definede_interface_addresses
: symbol not definedeaddrinfo
: symbol not definedaccess
: symbol not definedchmod
: symbol not definedchown
: symbol not definedclose
: symbol not definedcopyfile
: symbol not definedevent_close
: symbol not definedevent_endgame
: symbol not definedevent_getpath
: symbol not definedevent_init
: symbol not definedevent_start
: symbol not definedevent_stop
: symbol not definedfchmod
: symbol not definedfchown
: symbol not definedfdatasync
: symbol not definedfstat
: symbol not definedfsync
: symbol not definedftruncate
: symbol not definedfutime
: symbol not definedinit
: symbol not definedlink
: symbol not definedlstat
: symbol not definedmkdir
: symbol not definedmkdtemp
: symbol not definedopen
: symbol not definedpoll_getpath
: symbol not definedpoll_init
: symbol not definedpoll_start
: symbol not definedpoll_stop
: symbol not definedread
: symbol not definedreadlink
: symbol not definedrealpath
: symbol not definedrename
: symbol not definedreq_cleanup
: symbol not definedrmdir
: symbol not definedscandir
: symbol not definedscandir_next
: symbol not definedsendfile
: symbol not definedstat
: symbol not definedsymlink
: symbol not definedunlink
: symbol not definedutime
: symbol not definedwrite
: symbol not defined_acceptex_function
: symbol not defined_connectex_function
: symbol not defined_free_memory
: symbol not defined_osfhandle
: symbol not defined_process_title
: symbol not defined_total_memory
: symbol not definedaddrinfo
: symbol not definednameinfo
: symbol not definedrusage
: symbol not definedss_handle
: symbol not defineddle_size
: symbol not defined_ref
: symbol not definedime
: symbol not definede_init
: symbol not definede_invoke
: symbol not definede_start
: symbol not definede_stop
: symbol not definedindextoiid
: symbol not definedindextoname
: symbol not definedt_ntop
: symbol not definedt_pton
: symbol not definederface_addresses
: symbol not defined_addr
: symbol not defined_name
: symbol not defined_addr
: symbol not defined_name
: symbol not definedactive
: symbol not definedclosing
: symbol not definedreadable
: symbol not definedtty
: symbol not definedwritable
: symbol not defined_create
: symbol not defined_delete
: symbol not defined_get
: symbol not defined_set
: symbol not definedl
: symbol not definedten
: symbol not defineddavg
: symbol not definedp_alive
: symbol not definedp_close
: symbol not definedp_configure
: symbol not definedp_delete
: symbol not definedp_fork
: symbol not definedp_init
: symbol not definedp_new
: symbol not definedp_size
: symbol not definedp_watcher_endgame
: symbol not definedfd_poll
: symbol not definedex_destroy
: symbol not definedex_init
: symbol not definedex_init_recursive
: symbol not definedex_lock
: symbol not definedex_trylock
: symbol not definedex_unlock
: symbol not defined
: symbol not definedtatus_to_winsock_error
: symbol not definede
: symbol not definedfree_passwd
: symbol not definedget_passwd
: symbol not definedgetenv
: symbol not definedgethostname
: symbol not definedgetpid
: symbol not definedgetppid
: symbol not definedhomedir
: symbol not definedsetenv
: symbol not definedtmpdir
: symbol not definedunsetenv
: symbol not definede_accept
: symbol not definede_bind
: symbol not definede_chmod
: symbol not definede_cleanup
: symbol not definede_close
: symbol not definede_connect
: symbol not definede_endgame
: symbol not definede_getpeername
: symbol not definede_getsockname
: symbol not definede_init
: symbol not definede_listen
: symbol not definede_open
: symbol not definede_pending_count
: symbol not definede_pending_instances
: symbol not definede_pending_type
: symbol not definede_read_start
: symbol not definede_write
: symbol not definede_write2
: symbol not definedl_close
: symbol not definedl_endgame
: symbol not definedl_init
: symbol not definedl_init_socket
: symbol not definedl_start
: symbol not definedl_stop
: symbol not definedpare_init
: symbol not definedpare_invoke
: symbol not definedpare_start
: symbol not definedpare_stop
: symbol not definednt_active_handles
: symbol not definednt_all_handles
: symbol not definedcess_async_wakeup_req
: symbol not definedcess_close
: symbol not definedcess_endgame
: symbol not definedcess_fs_event_req
: symbol not definedcess_kill
: symbol not definedcess_pipe_accept_req
: symbol not definedcess_pipe_connect_req
: symbol not definedcess_pipe_read_req
: symbol not definedcess_pipe_shutdown_req
: symbol not definedcess_pipe_write_req
: symbol not definedcess_poll_req
: symbol not definedcess_proc_exit
: symbol not definedcess_signal_req
: symbol not definedcess_tcp_accept_req
: symbol not definedcess_tcp_connect_req
: symbol not definedcess_tcp_read_req
: symbol not definedcess_tcp_write_req
: symbol not definedcess_timers
: symbol not definedcess_tty_accept_req
: symbol not definedcess_tty_connect_req
: symbol not definedcess_tty_read_line_req
: symbol not definedcess_tty_read_raw_req
: symbol not definedcess_tty_read_req
: symbol not definedcess_tty_write_req
: symbol not definedcess_udp_recv_req
: symbol not definedcess_udp_send_req
: symbol not definedue_work
: symbol not definedd_start
: symbol not definedd_stop
: symbol not definedv_buffer_size
: symbol not defined
: symbol not definedlace_allocator
: symbol not defined_size
: symbol not definedident_set_memory
: symbol not defined
: symbol not definedock_destroy
: symbol not definedock_init
: symbol not definedock_rdlock
: symbol not definedock_rdunlock
: symbol not definedock_tryrdlock
: symbol not definedock_trywrlock
: symbol not definedock_wrlock
: symbol not definedock_wrunlock
: symbol not defined_destroy
: symbol not defined_init
: symbol not defined_post
: symbol not defined_trywait
: symbol not defined_wait
: symbol not definedd_buffer_size
: symbol not defined_process_title
: symbol not definedup_args
: symbol not definedtdown
: symbol not definednal_close
: symbol not definednal_endgame
: symbol not definednal_init
: symbol not definednal_start
: symbol not definednal_start_oneshot
: symbol not definednal_stop
: symbol not definednals_init
: symbol not definedultaneous_server_accepts
: symbol not definedwn
: symbol not definedio_pipe_server
: symbol not definedp
: symbol not definedeam_set_blocking
: symbol not definederror
: symbol not defined_accept
: symbol not defined_bind
: symbol not defined_close
: symbol not defined_connect
: symbol not defined_duplicate_socket
: symbol not defined_endgame
: symbol not defined_getpeername
: symbol not defined_getsockname
: symbol not defined_import
: symbol not defined_init
: symbol not defined_init_ex
: symbol not defined_keepalive
: symbol not defined_listen
: symbol not defined_nodelay
: symbol not defined_non_ifs_lsp_ipv4
: symbol not defined_non_ifs_lsp_ipv6
: symbol not defined_open
: symbol not defined_read_start
: symbol not defined_simultaneous_accepts
: symbol not defined_write
: symbol not definedead_create
: symbol not definedead_equal
: symbol not definedead_join
: symbol not definedead_self
: symbol not defineder_again
: symbol not defineder_endgame
: symbol not defineder_get_repeat
: symbol not defineder_init
: symbol not defineder_set_repeat
: symbol not defineder_start
: symbol not defineder_stop
: symbol not definednslate_sys_error
: symbol not defined_write
: symbol not defined_close
: symbol not defined_endgame
: symbol not defined_get_winsize
: symbol not defined_init
: symbol not defined_read_start
: symbol not defined_read_stop
: symbol not defined_reset_mode
: symbol not defined_set_mode
: symbol not defined_write
: symbol not defined_bind
: symbol not defined_close
: symbol not defined_endgame
: symbol not defined_getsockname
: symbol not defined_init
: symbol not defined_init_ex
: symbol not defined_open
: symbol not defined_recv_start
: symbol not defined_recv_stop
: symbol not defined_send
: symbol not defined_set_broadcast
: symbol not defined_set_membership
: symbol not defined_set_multicast_interface
: symbol not defined_set_multicast_loop
: symbol not defined_set_multicast_ttl
: symbol not defined_set_ttl
: symbol not defined_try_send
: symbol not definedef
: symbol not definedate_time
: symbol not definedime
: symbol not definedsion
: symbol not definedsion_string
: symbol not definedk
: symbol not definedapi_init
: symbol not definedsock_init
: symbol not definedte
: symbol not definedte2
: symbol not definedrecv_workaround
: symbol not definedrecvfrom_workaround
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'fs'
* removing 'C:/Users/REDACTED/lib/R/fs'
Warning in install.packages :
  installation of package ‘fs’ had non-zero exit status

The shear number of missing symbols suggests an entire library is missing or not listed on the link phase command line constructed by make.

Regards.

**Comment by jimhester** [comment]
I am guessing you had fs previously loaded and the dll was locked, I don't think this is an issue with the package. Please be sure you install fs with a fresh vanilla R session.

**Comment by BloomingAzaleas** [comment]
Actually, no. In this case package 'fs' was brought in as a dependency of something during a mass "update everything" refresh of my RStudio environment after a period of dis-use on this particular computer.  The package is not listed in either the system level nor my personal R package libraries, nor is a filesystem directory for 'fs' in either location.  Not showing in the RStudio package manager, nor in the results of (.packages()) and isNamespaceLoaded("fs") returns FALSE.

Further, RTools does or at least RTools under RStudio does all its work under a per-package temp directory tree such that all compilation and linking intermediates and pre-install finals occur in virgin directories, followed by an 'install' in the target package library directory tree.   Only during 'install' (typically done as a copy rather than a move) would the presence of a locked predecessor .dll file become an issue.  The failure reported was in the link of the pre-install .dll output.

Please re-open.

**Comment by jimhester** [comment]
There is nothing wrong with the fs package, so there is no reason to re-open the issue, it looks like something is wrong with your installation setup.

This sort of question is a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
