### ISSUE TITLE
temp_dir() ?

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#20]
The only advantage I can think of, is that we could have an API for inserting deterministic entries in order to avoid spurious diffs in README and examples.

**Comment by hadley** [comment]
Could also ensure that we don't get extra slashes (which is aesthetically unpleasing)

**Comment by hadley** [comment]
We could also make it `temp_path <- function(...)`

**Comment by jimhester** [comment]
I am still open to having a deterministic API of some kind however...

**Comment by hadley** [comment]
Maybe something like:

```R
env <- new.env(parent = emptyenv())
env$temp_names <- character()

add_temp_name <- function(paths) {
  env$temp_names <- c(env$temp_names, paths)
}

pop_temp_name <- function(paths) {
  n <- length(env$temp_names)
  if (n == 0) {
   return(NULL)
  }

  out <- env$temp_names[[1]]
  env$temp_names <- env$temp_names[-1]
  out
} 

temp_file <- function() {
  pop_temp_name() %||% tempfile()
}
```

?

**Comment by jimhester** [comment]
Yeah

**Comment by hadley** [comment]
Yeah, I don't know about examples. Maybe pkgdown could have a hook so you could preload?
