### ISSUE TITLE
dir_ls() with regexp is inconsistent with list.files()

### ISSUE THREAD

**Issue by paullemmens** [r-lib/fs#201]
Hi,

This might be a design choice, and is a matter of adjusting my code, and centers around the `^` start-of-line marker in the `regexp` argument. Somewhat related to https://github.com/r-lib/fs/issues/127.

`list.files(path, pattern = '^abc', recursive = TRUE, full.names = TRUE)` seems to first get all the files, then apply the pattern to filter, and then prepend the full path. `dir_ls()` first gets the full list of files, incl. full path, and then filters using `path_filter()`. 

The net effect is that the `^abc` pattern from `list.files()` does not work (or needs to be converted to something, possibly, more complicated to achieve the same effect). Given that the function comparison vignette "equates" `dir_ls()` with `list.files()` I would expect them to behave more similar regarding the filtering *or* to be more clearly documented to be different (it is somewhere to be read between the lines of the second bullet of that comparison vignette, but only vaguely).

**Comment by jimhester** [comment]
I am tracking this in #173
