### ISSUE TITLE
install fails from a read-only source mount

### ISSUE THREAD

**Issue by siddharthab** [r-lib/fs#202]
The installation for this package fails when the source code is mounted as read-only. This happens at the Makevars step `touch aclocal.m4` which will try to modify a file on a read-only file system.

While not completely necessary, it will be nice if the package could be built without modifying the source files or their attributes.

**Comment by jimhester** [comment]
We no longer use `touch` in the Makevars, so while I have not explicitly tested this I think it should now work.
