### ISSUE TITLE
Should path_expand() expand `~` in the middle of the path?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/fs#206]
E.g. 

```r
❯ fs::path_expand("a ~ b")
a /Users/gaborcsardi b
```

**Comment by jimhester** [comment]
Probably not, but this is also the behavior of `path.expand()`

```r
path.expand("a ~ b")
#> [1] "a /Users/jhester b"
```

**Comment by gaborcsardi** [comment]
Well, that does not make it right, though. :) See the discussion on R-devel as well.

**Comment by jimhester** [comment]
Yes, we can fix it I guess, on non-windows we call `R_ExpandFilename()`, which is why this ends up with the same behavior as `path.expand()`.

**Comment by gaborcsardi** [comment]
Yeah, I think we should definitely fix this, especially because
1) it is different on Windows,
2) it is different without libreadline, e.g. if you use `--no-readline`.

**Comment by gaborcsardi** [comment]
With https://github.com/wch/r-source/commit/598c422f82294350afb12b30b4340f3acefd0c46 this will solve itself around 3.6.1 or 3.7.0, I don't know if it is worth fixing it for older R versions in fs.

**Comment by jimhester** [comment]
It is also quite a specific case, there has to be spaces around the `~` for it to expand, sure it can happen but most people on POSIX systems avoid `~` in filenames in the first place...

**Comment by gaborcsardi** [comment]
This does not happen in R 3.6.x any more, and it is not worth fixing in R 3.5.x and R 3.4.x.
