### ISSUE TITLE
No (direct) fs equivalent for base::file.mtime()

### ISSUE THREAD

**Issue by kiernann** [r-lib/fs#211]
While you can pull the `modification_time` column from `fs::file_info()`, there is no {fs} equivalent for `base::file.mtime()`.

``` r
pacman::p_load(fs, dplyr)

# create files
dir_create("/tmp/test")
file_create("/tmp/test/temp1.txt")
Sys.sleep(60)
file_create("/tmp/test/temp2.txt")

# using fs and dplyr
dir_ls("/tmp/test") %>% 
  file_info() %>% 
  pull(modification_time)
#> [1] "2019-07-16 15:59:44 EDT" "2019-07-16 16:00:44 EDT"

# using base
file.mtime(list.files("/tmp/test", full.names = TRUE))
#> [1] "2019-07-16 15:59:44 EDT" "2019-07-16 16:00:44 EDT"
```

<sup>Created on 2019-07-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
I think this is fine, `file.mtime()` is just `file.info()$mtime`

nothing wrong with `file_info(...)$modification_time` IMHO.
