### ISSUE TITLE
Reading just a sample of the files

### ISSUE THREAD

**Issue by jjesusfilho** [r-lib/fs#214]
I am very often in situation where I have millions of files, but I just need a sample of them to test a function before  applying it to all files. Is there a way I can do that?

**Comment by jimhester** [comment]
Have you already tried just retrieving the full set of files and using `sample()`?

Anyway you can use `dir::fs_map()` to do this, e.g. to get 5% of the files in a path.

```r
unlist(fs::dir_map(".", recurse = TRUE, function(x) if (runif(1) < .05) x))
```

Alternatively you could use `dir_walk()` and append the results to a vector with `<<-`, which of the two options performs faster somewhat depends on how many files are in the directory and what percentage of the results you return. But it may very well be that `sample(dir_ls(), num_results)` is faster than either version.

**Comment by jjesusfilho** [comment]
I use sample(dir_list(), n), but I thought there was a better way of sampling without reading all file names to memory, like reading by index such as  dir_list(c(1,2,4,5,6).
