### ISSUE TITLE
need a function to concatonate files

### ISSUE THREAD

**Issue by aetiologicCanada** [r-lib/fs#215]
I have three files, (a,b,c) which I wish to concatonate into file d.
```
library(fs)
list_of_files <- c("a", "b", "c")
fs::file_create(list_of_files)
fs::file_copy(list_of_files, "d")

```
This fails with the sensible observation that:
"Error: Length of `path` must equal length of `new_path`"

Is there an "fs" way to achieve this?

**Comment by jimhester** [comment]
No there is not, concatenation is not really a file system operation IMHO.

But maybe you could write a function to do it, something like this.

``` r
cat <- function(x, filename) {
  out <- file(filename, "wb")
  on.exit(close(out))
  for (in_file in x) {
    writeBin(readBin(in_file, "raw", file.size(in_file)), out)
  }
  invisible(filename)
}
writeLines(c("foo", "bar"), "foo.txt")
writeLines(c("baz", "qux"), "baz.txt")
writeLines(c("hi", "ho"), "hi.txt")

cat(c("foo.txt", "baz.txt", "hi.txt"), "all.txt")
readLines("all.txt")
#> [1] "foo" "bar" "baz" "qux" "hi"  "ho"
```

<sup>Created on 2019-08-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
