### ISSUE TITLE
path_rel strips trailing sep

### ISSUE THREAD

**Issue by Alanocallaghan** [r-lib/fs#218]
``` r
fs::path_rel("tmp/")
#> tmp
```

<sup>Created on 2019-09-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Alanocallaghan** [comment]
Actually I think this is a more general bug; path_abs does similar.

**Comment by Alanocallaghan** [comment]
Or is this intended behaviour? https://github.com/r-lib/fs/blob/master/src/utils.cc#L101

Seems an odd default.

**Comment by jimhester** [comment]
This is the intended behavior of a [tidy path](https://github.com/r-lib/fs#tidy-paths)

> never have multiple / or trailing /

You should not be relying on the presence or absence trailing `/`, use `fs::path()` to construct paths, not string concatenation.

**Comment by Alanocallaghan** [comment]
I'm not relying on string concatenation to construct paths, I'm trying to use fs to specify a directory, eg `knitr::opt_chunks$set(fig.path="foo/")`

Fair enough if that's your definition, however much I dislike it

**Comment by jimhester** [comment]
Ok, then _knitr_ should not be sensitive to trailing slashes in the path then.
