### ISSUE TITLE
fail=FALSE needs to be extended to get_dirent_type

### ISSUE THREAD

**Issue by bellma-lilly** [r-lib/fs#219]
files <- dir_ls(location, all = TRUE, fail = FALSE)
Error: [EACCES] Failed to stat '/path/to/file/.ipynb_checkpoints': permission denied

This error occurs in the get_dirent_type call of uv_dirent_type_t entry_type = get_dirent_type(name.c_str(), e.type);

**Comment by jimhester** [comment]
Thanks! 
Can you please add a bullet to NEWS? It should briefly [describe the change](https://style.tidyverse.org/news.html) and end with `(@yourname, #issuenumber)`, then I can merge this.

**Comment by bellma-lilly** [comment]
@jimhester My apologies; I missed your request somehow. I have added the to the NEWS

**Comment by jimhester** [comment]
Closed by https://github.com/r-lib/fs/pull/220
