### ISSUE TITLE
file_exists does not expand

### ISSUE THREAD

**Issue by cderv** [r-lib/fs#222]
``` r
library(fs)
file.create(temp_file <- tempfile(tmpdir = "~"))
#> [1] TRUE
temp_file
#> [1] "~\\file90ec7b883886"
file.exists(temp_file)
#> [1] TRUE
file_exists(temp_file)
#> ~/file90ec7b883886 
#>              FALSE
file_exists(path_expand_r(temp_file))
#> C:/Users/chris/Documents/file90ec7b883886 
#>                                      TRUE
unlink(temp_file)
```

<sup>Created on 2019-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I would have expected to be true. 
Is this intended to manually expand the path before testing for existence ? 

Thanks.

**Comment by jennybc** [comment]
I think this is the expected result because fs is very clear about how it interprets `~/`. And the file above does not exist in the directory fs interprets as home directory.

**Comment by jennybc** [comment]
If you stay within the fs toolkit (for temp path creation, file creation, file existence check), it all works as expected. This is on Windows:

``` r
library(fs)

file_create(temp_file <- file_temp(tmp_dir = "~"))

temp_file
#> ~/file4a065d2192e

file.exists(temp_file)
#> [1] FALSE

file_exists(temp_file)
#> ~/file4a065d2192e 
#>              TRUE

file_delete(temp_file)
```

<sup>Created on 2019-09-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

The problems arise when doing path creation with base then the expansion / existence check with fs. Or *vice versa*.

**Comment by cderv** [comment]
Ok. My bad. 
This different `~` behavior make me go nuts and I get lost sometimes. 
I encounter this issue with another tool that give a path with `~` and an tried to create a reprex. A wrong one 😞  sorry. I was obvious from my use of `path_expand_r()` that this was not an issue

I think will do the correct `path_expand` every time to try prevent issue when using `fs` on situation where `fs` has not dealt with the creation. 

Thank you Jenny.

**Comment by jennybc** [comment]
The situation re: `~/` on Windows is just plain confusing. What fs does seems the most correct to me, but yes it's a place where switching between base and fs path handling can cause a mismatch.

**Comment by cderv** [comment]
How would you feel about a vignette specific on `~` for windows user regarding fs choice and how R base deals with it ? 

Currently, even the [existing vignette](https://fs.r-lib.org/articles/function-comparisons.html) does not deal with windows specifity :
it says `path_home()` is equivalent to `path.expand("~")` but 
``` r
library(fs)
# fs HOME is not the same as ~ on windows
path_home()
#> C:/Users/dervieuxchr
path.expand("~")
#> [1] "D:/Users/dervieuxchr/Documents"
path_expand("~")
#> C:/Users/dervieuxchr
# path_home_r is 
path_home_r()
#> D:/Users/dervieuxchr/Documents
path.expand("~")
#> [1] "D:/Users/dervieuxchr/Documents"
path_expand_r("~")
#> D:/Users/dervieuxchr/Documents
# changing R_USER env works to get R base behave like fs
callr::r_safe(
  function()  fs::path_home() == path.expand("~"), 
  env = c(callr::rcmd_safe_env(), R_USER = fs::path_norm(Sys.getenv("USERPROFILE")))
)
#> [1] TRUE
# as changing fs env to get fs behave as R base
withr::with_envvar(
  list(R_FS_HOME = Sys.getenv("R_USER")), {
  fs::path_home() == path.expand("~")
  }
)
#> [1] TRUE
```

<sup>Created on 2019-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I would see something talking about 

* R behavior re: HOME : https://cran.r-project.org/bin/windows/base/rw-FAQ.html#What-are-HOME-and-working-directories_003f
* fs choice as explained in `?fs::path_expand`: https://fs.r-lib.org/reference/path_expand.html#details
* the `*_r` variant that could be useful to get desired behavior. I use it in  `create_from_github` for example 
```r
usethis::create_from_github("rstudio/rmarkdown", destdir = fs::path_home_r("R/DEV"))
```
(This allows to have autocompletion on path from RStudio for destdir and still get the usethis function to work correctly)

I am willing to put all this in writing so it you are interested, please tell me.

**Comment by jennybc** [comment]
This is a question for @jimhester but it certainly seems like an important topic and these are good things to spell out explicitly somewhere.

**Comment by jimhester** [comment]
I think this is pretty well documented in `fs::path_expand` already
