### ISSUE TITLE
Feature request: dir_ls() family - argument to ignore temporary MS Office files

### ISSUE THREAD

**Issue by jzadra** [r-lib/fs#226]
All below is for OS X.

MS Office has an awful habit of creating a temporary file for any open files in the same directory, ie "myfile.xlsx" when opened creates a temporary file "~$myfile.xlsx".  Thus using a "*.xlsx" grob captures these.

Unfortunately, `all = F` to not return hidden files does not seem to apply to these files. 

Of course you can use `regexp` to filter these, but since the files only appear when another file is open, it's very easy to not catch that it's necessary if writing code without any files open that then pop up later if someone is looking at one of the files they are about to read in (fairly common in my experience).  In addition, the `regexp` argument wont' work along side the `grob` argument.

Perhaps the `all` argument could be updated to include filtering things that start with "~$"?  Or a new arg to ignore temporary MS Office files could be added with the default set to TRUE?

**Comment by jimhester** [comment]
Unfortunately `~$` is not a hidden file, I think you will just have to use some sort of workaround.

``` r
library(fs)
file_create("test.xlsx")
file_create("~$test.xlsx")
```

1.  A regular expression



``` r
dir_ls(regex = "^[^~].*[.]xlsx")
#> test.xlsx
```

2.  A filtering function



``` r
library(magrittr)

filter_temp <- function(x) { x[!startsWith(x, "~$")] }
dir_ls(glob = "*xlsx") %>% filter_temp()
#> test.xlsx
```

<sup>Created on 2019-10-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jzadra** [comment]
Yeah I'm aware it's not hidden and that I can filter using regexp, but at least in my experience this is a common enough issue that I thought it might be worth considering some built in functionality to ignore temporary files.
