### ISSUE TITLE
link_delete is broken in dev version 1.3.1.9000

### ISSUE THREAD

**Issue by jdblischak** [r-lib/fs#228]
My package's unit tests fail with the development version of fs. I investigated, and the problem appears to be with the function `link_delete()`.

With fs 1.3.1, the code below runs fine:

``` r

packageVersion("fs")
#> [1] '1.3.1'
d <- fs::file_temp()
fs::dir_create(d)
l <- fs::file_temp()
fs::link_create(d, l)
identical(fs::link_path(l), d)
#> [1] TRUE
fs::dir_exists(d)
#> /tmp/RtmpnnlI3x/file2e1a39e50243 
#>                             TRUE
fs::link_exists(l)
#> /tmp/RtmpnnlI3x/file2e1a19a04231 
#>                             TRUE
fs::link_delete(l)
fs::dir_exists(d)
#> /tmp/RtmpnnlI3x/file2e1a39e50243 
#>                             TRUE
fs::link_exists(l)
#> /tmp/RtmpnnlI3x/file2e1a19a04231 
#>                            FALSE
```

<sup>Created on 2019-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

However, with the development version 1.3.1.9000, `link_delete()` fails to delete the link:

``` r

packageVersion("fs")
#> [1] '1.3.1.9000'
d <- fs::file_temp()
fs::dir_create(d)
l <- fs::file_temp()
fs::link_create(d, l)
identical(fs::link_path(l), d)
#> [1] TRUE
fs::dir_exists(d)
#> /tmp/RtmpKU2BG2/file1cee499ea170 
#>                             TRUE
fs::link_exists(l)
#> /tmp/RtmpKU2BG2/file1cee2ab33ed8 
#>                             TRUE
fs::link_delete(l)
#> Error: [ENOTDIR] Failed to remove '/tmp/RtmpKU2BG2/file1cee2ab33ed8': not a directory
fs::dir_exists(d)
#> /tmp/RtmpKU2BG2/file1cee499ea170 
#>                             TRUE
fs::link_exists(l)
#> /tmp/RtmpKU2BG2/file1cee2ab33ed8 
#>                             TRUE
```

<sup>Created on 2019-10-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

I ran the code above on Ubuntu 18.04. Please let me know if you'd like me to run it on other operating systems.

**Comment by jimhester** [comment]
It was due to changes in https://github.com/r-lib/fs/commit/516eff9180f720f59437e4fe2d6e9508a24d8aaf, should now be fixed.

**Comment by jdblischak** [comment]
I confirmed it works. Thanks Jim!
