### ISSUE TITLE
`dir_delete` fails when `path` contains nested directories.

### ISSUE THREAD

**Issue by michaelbolger** [r-lib/fs#236]
If the `path` argument to `dir_delete` contains nested subdirectories, `dir_delete` will delete the subdirectories, but will fail prior to deleting the top level directories:

```
test <- c("~/test/about", "~/test/tags",  "~/test/tags/blogdown")
dir_create(test)  # Make sure there is no existing ~/test directory first.
dir_ls("~/test", recurse = TRUE) %>% as.character()
## [1] "/home/michael/test/about"         "/home/michael/test/tags"         
## [3] "/home/michael/test/tags/blogdown"
dir_delete(test)
## Error: [ENOENT] Failed to remove '/home/michael/test/tags/blogdown': no such file or directory
dir_ls("~/test", recurse = TRUE) %>% as.character()
## [1] "/home/michael/test/about" "/home/michael/test/tags" 
```

This happens because `dir_delete` itself goes off and gets subdirectories to delete, and then concatenates them with the original top-level directories before deleting:

```
old <- path_expand(path)
dirs <- dir_ls(old, type = "directory", recurse = TRUE, 
  all = TRUE)
# ...
rmdir_(rev(c(old, dirs)))
```

If `path` had subdirectories in it, `c(old, dirs)` will include subdirectories twice, so it fails the second time it gets to one.

A solution would be to wrap `c(old, dirs)` in `unique`:

```
rmdir_(rev(unique(c(old, dirs), fromLast = TRUE)))
```

This works in my testing. Happy to (try to) create a pull request if appropriate.

Versions:
fs 1.3.1
R 3.6.1
RStudio 1.2.5019

**Comment by jimhester** [comment]
This is the same behavior as if you did the same thing on the command line, I think it actually makes sense as-is.
```shell
mkdir -p test test/tags test/tags/blogdown
rm -r test test/tags test/tags/blogdown
rm: cannot remove 'test/tags': No such file or directory
rm: cannot remove 'test/tags/blogdown': No such file or directory
```

**Comment by michaelbolger** [comment]
True, the command line also returns an error, but it's not the same result--it still completes the task, leaving you back where you started, with no test directories:
```
mkdir -p test test/tags test/tags/blogdown
rm -r test test/tags test/tags/blogdown
```
But `dir_delete` only gets part-way through:
```
test <- c("test", "test/tags", "test/tags/blogdown")
dir_create(test)
dir_delete(test)
## Error: [ENOENT] Failed to remove 'test/tags/blogdown': no such file or directory
dir_ls()
## test 
```
