### ISSUE TITLE
Better supported for organised subdirectory structures

### ISSUE THREAD

**Issue by mgirlich** [r-lib/fs#237]
Often, one has an organised directory structure e.g. of the format `/<country>/<year>` and then needs to do some batch processing of files in these directories. A typical workflow would be to get info about a certain file in each of these directories and parse parts of the path to the file, e.g.

``` r
library(fs)
library(dplyr)
dir_info("~/Downloads/", recurse = TRUE, regexp = "(es|de|fr)/\\d{4}/population\\.xlsx") %>% 
  transmute(
    country = stringr::str_match(path, "(es|de|fr)/(\\d{4})/population\\.xlsx")[, 2],
    year = stringr::str_match(path, "(es|de|fr)/(\\d{4})/population\\.xlsx")[, 3],
    size
  )
#> # A tibble: 5 x 3
#>   country year         size
#>   <chr>   <chr> <fs::bytes>
#> 1 de      2000        2.95M
#> 2 de      2001        2.95M
#> 3 de      2002        2.95M
#> 4 fr      2000        2.95M
#> 5 fr      2002        2.95M
```

<sup>Created on 2019-12-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

and then process each file passing path, country and year as a parameter to the corresponding function.

Instead of the code above it would be very nice to have something like

``` r
dir_info("~/Downloads/", parts = c(country = "es|de|fr", year = "\\d{4}", "population\\.rds"))
```

i.e. specify the parts of the path and the named parts should become a column in the output.

Further, it would make sense to also support this in `dir_map()` and `dir_walk()` and pass the parsed parts of the path on to fun, i.e.

``` r
dir_walk(
  "~/Downloads/",
  parts = c(country = "es|de|fr", year = "\\d{4}", "population\\.rds"),
  fun = function(path, country, year) {}
)
```

**Comment by jimhester** [comment]
I think this is out of scope for fs, you can always do these types of manipulations after the fact, or on demand with custom functions in `dir_map()`, `dir_walk()`.
