### ISSUE TITLE
[.fs_bytes

### ISSUE THREAD

**Issue by romainfrancois** [r-lib/fs#239]
``` r
library(fs)

size <- structure(c(0, 0), class = "fs_bytes")
class(size)
#> [1] "fs_bytes"
class(size[1:2])
#> [1] "fs_bytes" "numeric"
```

<sup>Created on 2020-01-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

initially reported here: https://github.com/tidyverse/dplyr/issues/4685

**Comment by hadley** [comment]
I think it probably should have `numeric` class to begin with
