### ISSUE TITLE
dir_exists(".") returns TRUE when current working directory is deleted

### ISSUE THREAD

**Issue by jdblischak** [r-lib/fs#240]
I found an edge case where both `dir.exists(".")` and `fs::dir_exists(".")` return `TRUE` when the current working directory has been deleted. 

I'd like to be able to write code similar to below. It converts a relative path to a directory to an absolute path.

```
if (fs::dir_exists(relative_path_to_directory) {
  absolute_path_to_directory <- fs::path_abs(relative_path_to_directory)
}
```

The above code fails in this edge case when `path_abs()` tries to convert the relative path to the non-existent current working directory.

Is it possible to update `fs::dir_exists()` to handle this edge case? If not, what is the best way to handle it in my code? I also tried `fs::is_dir()` but it also returns `TRUE`.

Here's a reprex to demonstrate this behavior with both base R and fs functions:

``` r

cwd <- getwd()
path <- tempfile()
dir.create(path)
setwd(path)
unlink(path, recursive = TRUE, force = TRUE)
dir.exists(path)
#> [1] FALSE
dir.exists(".")
#> [1] TRUE
getwd()
#> NULL
setwd(cwd)

cwd <- fs::path_wd()
path <- fs::file_temp()
fs::dir_create(path)
setwd(path)
fs::dir_delete(path)
fs::dir_exists(path)
#> /tmp/RtmpP3SGE9/file3ca72edbcba1 
#>                            FALSE
fs::dir_exists(".")
#>    . 
#> TRUE
fs::is_dir(".")
#>    . 
#> TRUE
if (dir.exists(".")) fs::path_abs(".")
#> Error in path[!is_abs] <- path_norm(path(start, path[!is_abs])): replacement has length zero
fs::path_wd()
#> character(0)
setwd(cwd)
```

<sup>Created on 2020-01-08 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

<details>

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 3.6.2 (2019-12-12)
#>  os       Ubuntu 18.04.3 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2020-01-08                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                   
#>  assertthat    0.2.1      2019-03-21 [3] CRAN (R 3.5.3)           
#>  backports     1.1.5      2019-10-02 [3] CRAN (R 3.6.1)           
#>  cli           2.0.0      2019-12-09 [3] CRAN (R 3.6.2)           
#>  crayon        1.3.4      2017-09-16 [3] CRAN (R 3.5.0)           
#>  digest        0.6.23     2019-11-23 [3] CRAN (R 3.6.1)           
#>  evaluate      0.14       2019-05-28 [3] CRAN (R 3.6.0)           
#>  fansi         0.4.0      2018-10-05 [3] CRAN (R 3.5.1)           
#>  fs            1.3.1.9000 2020-01-08 [1] Github (r-lib/fs@2fb543e)
#>  glue          1.3.1      2019-03-12 [3] CRAN (R 3.5.3)           
#>  highr         0.8        2019-03-20 [3] CRAN (R 3.5.3)           
#>  htmltools     0.4.0      2019-10-04 [3] CRAN (R 3.6.1)           
#>  knitr         1.26       2019-11-12 [3] CRAN (R 3.6.1)           
#>  magrittr      1.5        2014-11-22 [3] CRAN (R 3.5.0)           
#>  Rcpp          1.0.3      2019-11-08 [3] CRAN (R 3.6.1)           
#>  reprex        0.3.0.9000 2019-07-19 [1] local                    
#>  rlang         0.4.2      2019-11-23 [3] CRAN (R 3.6.1)           
#>  rmarkdown     1.10       2018-06-11 [1] CRAN (R 3.6.2)           
#>  rprojroot     1.2        2017-01-16 [3] CRAN (R 3.5.0)           
#>  sessioninfo   1.1.1      2018-11-05 [3] CRAN (R 3.5.1)           
#>  stringi       1.4.3      2019-03-12 [3] CRAN (R 3.5.3)           
#>  stringr       1.4.0      2019-02-10 [3] CRAN (R 3.5.2)           
#>  withr         2.1.2      2018-03-15 [3] CRAN (R 3.5.0)           
#>  xfun          0.11       2019-11-12 [3] CRAN (R 3.6.1)           
#>  yaml          2.2.0      2018-07-25 [3] CRAN (R 3.5.1)           
#> 
#> [1] /home/jdb-work/R/x86_64-pc-linux-gnu-library/3.6
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by jimhester** [comment]
This is just how POSIX file systems work, unlink removes the directory from the file system, but the actual inode is not removed until all processes that hold a handle to it release their handles or exit. Since the R process has a handle to the current working directory `.` is still valid even though the path is no longer in the file system.

If you change the working directory before trying to remove the directory you shouldn't run into this.

**Comment by jdblischak** [comment]
> Since the R process has a handle to the current working directory . is still valid even though the path is no longer in the file system.

If `.` is still valid, can `path_abs()` be updated so that it returns the absolute path?

> If you change the working directory before trying to remove the directory you shouldn't run into this.

My code is not deleting the directory. I'm trying to handle the edge case where for some reason the user has deleted the current working directory and run one of my functions before they changed the working directory to an existing directory.

I was trying to avoid it, but it's looking like I'll have to add a check like the following to all the user-facing functions:

```
if (length(fs::path_wd()) == 0)
  stop("The current working directory doesn't exist.",
       " Use setwd() to change to existing directory.")
```

**Comment by jimhester** [comment]
There is no absolute path though in that case, the path has been removed from the file system, just the handle is still valid.

IMHO this sounds like an edge case you shouldn't worry about.
