### ISSUE TITLE
fs operations for file path URIs

### ISSUE THREAD

**Issue by cboettig** [r-lib/fs#245]
The [File URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme) is recognized by base R functions, but not `fs` functions.  I can understand that `fs` considers handling of generic URIs as out of scope (#97), but would you consider just supporting `file://` prefix?  It seems weird that a common standard for file paths would be out of scope.  It also makes for some unanticipated gotchas when moving from base R file management functions.  Thanks for considering!

**Comment by gaborcsardi** [comment]
@cboettig How exactly is `file://` supported in base R? E.g. these do not work for me:

```r
❯ dir("/Users")
[1] "foobar"      "gaborcsardi" "Guest"       "halidi"      "Shared"

❯ dir("file:///Users")
character(0)

❯ file.exists("/Users")
[1] TRUE

❯ file.exists("file:///Users")
[1] FALSE
```

**Comment by cboettig** [comment]
Sorry, I was pretty unclear, and possibly this is more of a readr/vroom question than a `fs` question.  Base R `file()` understands `file:///`, e.g. (with apologies for the absolute paths but you get the idea)

```
readr::write_csv(mtcars, "~/mtcars.csv")
# Nope
readr::read_csv("file:///home/cboettig/mtcars.csv")
# Okay
readr::read_csv(file("file:///home/cboettig/mtcars.csv"))
# Okay
read.csv(file("file:///home/cboettig/mtcars.csv"))

```

It's a good point that these other base R functions that are better `fs`-analogs anyway don't understand the convention.  If this convention isn't followed in the underlying C library or other places, I'm more than happy that you close it.  

(On the other hand, I would really like to see an R package analog to `fsspec` in python, which provides consistent file-system abstractions across local POSIX filesystems (i.e. `file:///`) but also over cloud-native object stores like `s3://` and [many others](https://filesystem-spec.readthedocs.io/en/latest/api.html#built-in-implementations)!

**Comment by gaborcsardi** [comment]
Yes, I think `file://` makes sense when you need to use URIs and want to refer to a local file. But fs does not work with URLs or URIs, so this is out of scope here, sorry.
