### ISSUE TITLE
Add ext argument to path()

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#25]
I could've sworn we used to have this?  But it would be useful to have argument to do this, so you can avoid a `paste()` inside `path()`.

**Comment by jimhester** [comment]
We decided it was a good idea, but didn't actually implement it yet, thank you for opening this as a reminder

**Comment by jimhester** [comment]
#27 adds a `path_ext_set()` function that could be used instead of `paste0(tools::file_path_sans_ext(path), ".xyz")` and could maybe make this argument less needed.

So you can write

```r
file <- "foo.txt"
path("a", "folder", path_ext_set(file, "zip"))
```

**Comment by hadley** [comment]
That's still a lot longer than `path("a", "folder", file, ext = "zip")`
