### ISSUE TITLE
Compilation fails on mac osx with R-devel

### ISSUE THREAD

**Issue by hcorrada** [r-lib/fs#251]
I see the same error shown in the Github action for macos-latest (devel):
https://github.com/r-lib/fs/runs/513791479?check_suite_focus=true

**Comment by jimhester** [comment]
This is a Rcpp bug, https://github.com/RcppCore/Rcpp/issues/1046, it should be fixed in the dev version of Rcpp.

**Comment by hcorrada** [comment]
Confirmed, fixed after installing Rcpp from github master. Thank you.
