### ISSUE TITLE
Feature request: check if file exists, otherwise add suffix+number

### ISSUE THREAD

**Issue by sda030** [r-lib/fs#252]
In many functions in CRAN packages that write file/folder to disk, the file/folder is either overwritten with or without a warning, or an error is produced. However, when producing many files in loops, for instance plots, and a specific filename has not been given, it makes sense to name these "plot_1.png", "plot_2.png", etc. Sometimes it is not possible to know how many files will be produced before the fact. Thus, a convenient function could check whether plot_1.png exists, and if it does, increase index by 1 and try again. If not, return the available path `"plot_1.png"`. By keeping the function outside of file_create, it will also be possible to delete files in similar fashion. I couldn't come up with a good name for such a function but makes sense to me to allow it to handle directories, files and to ignore extensions. The attempt below is only in part vectorized, and not taking advantage of Rcpp.
`file_alternative <- function(path, sep="_") {
    
    internalFunction <- function(path) {
        dir <- fs::path_dir(path)[1]
        file <- fs::path_ext_remove(fs::path_file(path)[1])
        ext <- fs::path_ext(path)[1]
        i <- 1L
       # couldn't think of how to vectorize this while loop
        while(fs::file_access(path=paste(dir, paste0(file, sep, i, if(nchar(ext)>0) ".", ext), sep="/"), mode="exists")) {
            i <- i+1
        }
        paste(dir, paste0(file, sep, i, if(nchar(ext)>0) ".", ext), sep="/")
    } 
    out <- dplyr::if_else(!fs::file_access(path, mode = "exists"), path, 
                  internalFunction(path))
    out <- fs::path(out) #Clean output
    setNames(out, path) # Old paths as names
}`

**Comment by jimhester** [comment]
Checking, then creating as you do here is unfortunately subject to race conditions, the file could be created by another process in between the check and when it is created. The only sure way to do this is to keep an open file handle.

In any case I think this is out of scope for fs, so I am closing this issue.
