### ISSUE TITLE
Rscript.exe crashing after window resized when using dir_exists and file_exists

### ISSUE THREAD

**Issue by ismirsehregal** [r-lib/fs#261]
I have a shiny app which I, every now and then, start via a batch file with a line like:
`".../R/bin/Rscript.exe" myApp.R`

I just realized, that when I resize the console window (cmd.exe) this app crashes and gives the following error:

```
==== C stack trace ===============================

        RtlImageDirectoryEntryToData [0x0x77612ad4+228]
        RtlEnterCriticalSection [0x0x7760d261+209]
        (No symbol) [0x0x6fae7e4c]
        GetWindowLongPtrW [0x0x773d9393+47]
        (No symbol) [0x0xf]
        (No symbol) [0x0x50000012c0050]
        (No symbol) [0x0x50000700000000]
        (No symbol) [0x0xf5003b0050001a]
```
I tracked down the issue to `dir_exists `and `file_exists`. Once I replace them with `dir.exists `and `file.exists` I can resize the window without any error.

Unfortunately so far I wasn't able to come up with a **minimal** reproducible example - I will add it as soon as possible. However, the error is reproducible in my actual project.

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
fs_1.3.2
```
**Edit**: the same behaviour can be seen on Windows 10.

![screen](https://user-images.githubusercontent.com/36849480/78685406-ff115980-78f1-11ea-85ea-d6b68c7176fc.gif)

**Comment by ismirsehregal** [comment]
By now I was able to condense the skript to four lines:

> myApp.R
```
library(fs)
library(V8)
dir_exists(tempdir())
Sys.sleep(120)
```

> go.bat
```
"D:\programs\R\bin\Rscript.exe" myApp.R
pause
```

To reproduce the error, run `go.bat` and resize the console window, while R is still running (120 seconds).

Accordingly the problem isn't related to shiny, but the R process needs to be running when resizing the console window. When I remove `library(V8)` from the code, the process still crashes, but there is no error message displayed. As mentioned above I was able to reproduce this on another PC using Windows 10.

I'd appreciate if anyone can confirm the above - thanks in advance!

**Comment by ismirsehregal** [comment]
By now I was able to condense the skript to four lines:

> myApp.R
```
library(fs)
library(V8)
dir_exists(tempdir())
Sys.sleep(120)
```

> go.bat
```
"D:\programs\R\bin\Rscript.exe" myApp.R
pause
```

To reproduce the error, run `go.bat` (in the same folder as `myApp.R`) and resize the console window, while R is still running (120 seconds).

Accordingly the problem isn't related to shiny, but the R process needs to be running when resizing the console window. When I remove `library(V8)` from the code, the process still crashes, but there is no error message displayed. As mentioned above I was able to reproduce this on another PC using Windows 10.

I'd appreciate if anyone can confirm the above - thanks in advance!

![image](https://user-images.githubusercontent.com/36849480/78757996-b3a48d00-797d-11ea-95ac-f70e36166a2a.png)

**Comment by ismirsehregal** [comment]
Sure, the usecase is a little exotic. But I'd be  grateful if anyone can reproduce the above scenario. Currently I have to use base R functions again.

**Comment by jimhester** [comment]
From the stacktrace it looks like the libuv signal handlers are catching the resize signal. I am not sure this is easily fixed, I think in the short term I would suggest you use base R for this project.

**Comment by ismirsehregal** [comment]
Thanks for the feedback!
