### ISSUE TITLE
Can't install fs from GitHub or CRAN under r-devel and Windows 10

### ISSUE THREAD

**Issue by sfirke** [r-lib/fs#264]
Trying to debug a package that is failing under R-devel & Windows and I'm setting up R-devel on a Windows machine.  fs seems to be the only package I can't get to install.  Both the CRAN and GitHub versions fail the same way, with output ending:
```
./libuv/libuv.a(thread.o):thread.c:(.text+0x357): undefined reference to `_mm_mfence'
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'fs'
* removing 'C:/Users/samfi/Documents/R/win-library/4.1/fs'
```

Session info:

R Under development (unstable) (2020-04-07 r78175)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

**Comment by jimhester** [comment]
What version of Rtools are you using, this was an issue with earlier versions of the Rtools 40 toolchain, but it should be fixed with recent ones.

**Comment by sfirke** [comment]
That did it!  It failed under Rtools35, it worked with Rtools40 (and the associated version of R `R-testing`).  https://cran.r-project.org/bin/windows/testing/rtools40.html in case others end up here.  Thanks, Jim.
