### ISSUE TITLE
path_real, non-existing files and drive letters on Windows

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/fs#267]
Reprex, the last seems wrong, at least I did not find any clue in the docs that this should happen:

``` r
library(fs)
path_real("/rtools")
#> C:/Rtools
path_real("/rtools123")
#> C:/rtools123
path_real("c:/rtools")
#> C:/Rtools
path_real("c:/rtools123")
#> C:/Users/csard/AppData/Local/Temp/RtmpWeQu8j/reprex419073b575e/rtools123
```

<sup>Created on 2020-04-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jimhester** [comment]
I am coming to the conclusion that https://github.com/r-lib/fs/issues/144 was a mistake, and `path_real()` should go back to throwing an error if the files don't exist.

Also if this is related to the R-devel post, I think `fs::path_abs()` is actually the function to use, as I recently replied.

**Comment by jimhester** [comment]
The comments in https://github.com/r-lib/fs/issues/221#issuecomment-536739350 likely show the issue, `path_real("C:")` returns the current working directory on Windows
