### ISSUE TITLE
PATH_MAX error on AppVeyor

### ISSUE THREAD

**Issue by jdblischak** [r-lib/fs#269]
With the release of [fs 1.3.2](https://github.com/r-lib/fs/blob/master/NEWS.md#fs-132) in March, the AppVeyor build of my workflowr package started failing with the error message `Total path length must be less than PATH_MAX: 260`, which was added in PR #233.

I'm having a real hard time debugging the issue because I can't reproduce it. The error doesn't happen locally on my Windows 10 machine. And when I remotely login to the AppVeyor server, I can't reproduce the error by manually running `R CMD check` or `devtools::check()`. I'm confused how it only occurs (consistently) when `R CMD check` is run automatically.

The [line](https://github.com/jdblischak/workflowr/blob/master/tests/testthat/test-wflow_build.R#L343) that errors is simply trying to delete one R Markdown file (to cleanup after a test has completed). The failure happens earlier though when trying to convert the path to an absolute path. I use this same strategy in multiple other tests, but for some reason it fails here. I'd appreciate any advice or insight on how I might be able to fix the issue (or even just to be able to reproduce it manually).

Here's the error message produced by `R CMD check`:

```
  Running 'testthat.R' [14m]
 ERROR
Running the tests in 'tests/testthat.R' failed.
Last 13 lines of output:
  Backtrace:
   1. workflowr::wflow_remove(file_w_cache, project = site_dir)
   2. workflowr:::wflow_delete(files_to_remove)
   3. workflowr:::absolute(path)
   4. fs::path_abs(newpath)
   6. fs::path(start, path[!is_abs])
   8. fs:::path_(...)
  
  == testthat results  ===========================================================
  [ OK: 1783 | SKIPPED: 13 | WARNINGS: 0 | FAILED: 2 ]
  1. Error: wflow_build deletes cache when delete_cache = TRUE (@test-wflow_build.R#343) 
  2. Error: wflow_publish deletes cache when delete_cache = TRUE (@test-wflow_publish.R#241) 
```

https://ci.appveyor.com/project/jdblischak/workflowr/builds/31466909#L1140

I found the full error message by downloading the AppVeyor [artifact](https://ci.appveyor.com/api/buildjobs/2gwbx7ycren296ah/artifacts/failure.zip).

```
Total path length must be less than PATH_MAX: 260
Backtrace:
 1. workflowr::wflow_remove(file_w_cache, project = site_dir)
 2. workflowr:::wflow_delete(files_to_remove)
 3. workflowr:::absolute(path)
 4. fs::path_abs(newpath)
 6. fs::path(start, path[!is_abs])
 8. fs:::path_(...)
```

**Comment by jimhester** [comment]
It seems likely to me that the temp directory used by appveyor is long enough, that along with your workflowr cache directory is exceeding the 260 character limit on Windows.

Could you just not convert the path to an absolute one? It doesn't seem necessarily if you are just going to then delete the file.

**Comment by jdblischak** [comment]
> It seems likely to me that the temp directory used by appveyor is long enough, that along with your workflowr cache directory is exceeding the 260 character limit on Windows.

I figured out why this particular instance is failing but not the many other times I teardown my tests using the same strategy. It's because the auto-generated cache files created by knitr are much longer than a typical filename (the full chunk name plus a 32 character hash).

> Could you just not convert the path to an absolute one? It doesn't seem necessarily if you are just going to then delete the file.

I tried directly deleting the files and cache directory:

```
fs::file_delete(c(file_w_cache, build_v03$html))
fs::dir_delete(dir_cache)
```

The files were deleted without problem, but perhaps not surprisingly, the cache directory full of files with long filenames couldn't be deleted:

```
  Backtrace:
   1. fs::dir_delete(dir_cache)
  
  -- 2. Error: wflow_publish deletes cache when delete_cache = TRUE (@test-wflow_p
  [ENOENT] Failed to remove '../../../../../Users/appveyor/AppData/Local/Temp/1/RtmpGaGZx9/working_dir/Rtmp25xO7Y/test-wflow_publish-79056fc4869/analysis/cache_cache/html/session-info-chunk-inserted-by-workflowr_af8682fd08bd46eea87d02caec9915c0.RData': no such file or directory
```

https://ci.appveyor.com/project/jdblischak/workflowr/builds/32424965#L1071

Next I'm going to try `unlink()`.

**Comment by jdblischak** [comment]
Frustratingly `unlink()` fails silently. I guess I'm just going to leave that cache directory on AppVeyor. Fortunately my final cleanup for the entire suite of tests uses `unlink()`, so it can fail silently on AppVeyor. My tests take place in separate subdirectories, so it isn't that big of a deal if this one persists.

**Comment by jic007** [comment]
I am having the same issue and it is driving me crazy

what is meant by absolute path? 

I am trying to use dir_copy in R

**Comment by jdblischak** [comment]
An absolute path is the full path from the root of the file system to the file or directory. A relative path is the path from the current working directory to the file or directory. Below are some resources to learn more:

https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths
https://swcarpentry.github.io/shell-novice/02-filedir/
https://datasciencebook.ca/reading.html#absolute-and-relative-file-paths
