### ISSUE TITLE
unknown type name 'sem_t'

### ISSUE THREAD

**Issue by purod** [r-lib/fs#271]
When installing fs, I got the following error.

clang++ -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -pthread    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c init.cc -o init.o
clang++ -I"/usr/share/R/include" -DNDEBUG -I./libuv/include -I. -pthread    -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c id.cc -o id.o
In file included from id.cc:1:
In file included from ./utils.h:3:
In file included from ./libuv/include/uv.h:62:
./libuv/include/uv-unix.h:136:9: error: unknown type name 'sem_t'
typedef UV_PLATFORM_SEM_T uv_sem_t;
        ^
./libuv/include/uv-unix.h:104:28: note: expanded from macro 'UV_PLATFORM_SEM_T'
# define UV_PLATFORM_SEM_T sem_t
                           ^
1 error generated.
/usr/lib/R/etc/Makeconf:175: recipe for target 'id.o' failed
make: *** [id.o] Error 1
ERROR: compilation failed for package ‘fs’

**Comment by purod** [comment]
remove semaphore.h from /usr/local/include  works for me

**Comment by bioinfotec** [comment]
> remove semaphore.h from /usr/local/include works for me

Yes, it really works. But why it works? And what is the function of semaphore.h?
