### ISSUE TITLE
Awkwardness around "full paths" as names

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#274]
``` r
library(fs)

hold_stuff <- dir_create("~/tmp/hold_stuff")

writeLines("X,Y\n1,a", path(hold_stuff, "a.csv"))
writeLines("X,Y\n2,b", path(hold_stuff, "b.csv"))
writeLines("X,Y\n3,c", path(hold_stuff, "c.csv"))

csv_files <- dir_ls(hold_stuff)
csv_files
#> /Users/jenny/tmp/hold_stuff/a.csv /Users/jenny/tmp/hold_stuff/b.csv 
#> /Users/jenny/tmp/hold_stuff/c.csv
names(csv_files)
#> [1] "/Users/jenny/tmp/hold_stuff/a.csv" "/Users/jenny/tmp/hold_stuff/b.csv"
#> [3] "/Users/jenny/tmp/hold_stuff/c.csv"

purrr::map_dfr(csv_files, read.csv, .id = "file")
#>                                file X Y
#> 1 /Users/jenny/tmp/hold_stuff/a.csv 1 a
#> 2 /Users/jenny/tmp/hold_stuff/b.csv 2 b
#> 3 /Users/jenny/tmp/hold_stuff/c.csv 3 c

names(csv_files) <- path_file(csv_files)

purrr::map_dfr(csv_files, read.csv, .id = "file")
#>    file X Y
#> 1 a.csv 1 a
#> 2 b.csv 2 b
#> 3 c.csv 3 c
```

<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

I love the way fs automatically names the return value of, e.g., `fs::dir_ls()`. However above is an awkwardness I encounter often. I almost always (always, even?) want just the file part as the name, not the full path.

Have you thought about this? Is my workflow suboptimal? Is there any way this could change?

**Comment by jimhester** [comment]
I don't see any way it could change, you need it to be the full path to avoid destroying information.

But if you deal with relative paths rather than absolute ones it will only be a relative path, e.g.

``` r
library(fs)
hold_stuff <- dir_create("hold_stuff")

writeLines("X,Y\n1,a", path(hold_stuff, "a.csv"))
writeLines("X,Y\n2,b", path(hold_stuff, "b.csv"))
writeLines("X,Y\n3,c", path(hold_stuff, "c.csv"))

csv_files <- dir_ls(hold_stuff)
csv_files
#> hold_stuff/a.csv hold_stuff/b.csv hold_stuff/c.csv

names(csv_files)
#> [1] "hold_stuff/a.csv" "hold_stuff/b.csv" "hold_stuff/c.csv"

purrr::map_dfr(csv_files, read.csv, .id = "file")
#>               file X Y
#> 1 hold_stuff/a.csv 1 a
#> 2 hold_stuff/b.csv 2 b
#> 3 hold_stuff/c.csv 3 c
```

<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jennybc** [comment]
This comes up when using rprojroot and here. Meaning: that's how we end up with an absolute path instead of a relative one.

**Comment by jennybc** [comment]
I guess one really just has to insert a call to `path_file()` somewhere, either "before" (on the names) or "after" (mutate the `.id` variable).
