### ISSUE TITLE
Add glob, regexp, invert in dir_map() and dir_walk()

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#275]
It seems like it would be handy if the inclusion / exclusion features offered by `glob`, `regexp`, and `invert` were also available in `dir_map()` and `dir_walk()`.

``` r
library(fs)

hold_stuff <- dir_create("~/tmp/hold_stuff")

writeLines("X,Y\n1,a", path(hold_stuff, "a.csv"))
writeLines("X,Y\n2,b", path(hold_stuff, "b.csv"))
writeLines("X,Y\n3,c", path(hold_stuff, "c.csv"))
file_copy(R.home('doc/html/Rlogo.pdf'), path(hold_stuff, "Rlogo.pdf"))

dir_ls(hold_stuff)
#> /Users/jenny/tmp/hold_stuff/Rlogo.pdf /Users/jenny/tmp/hold_stuff/a.csv     
#> /Users/jenny/tmp/hold_stuff/b.csv     /Users/jenny/tmp/hold_stuff/c.csv

dir_ls(hold_stuff, glob = "*.csv")
#> /Users/jenny/tmp/hold_stuff/a.csv /Users/jenny/tmp/hold_stuff/b.csv 
#> /Users/jenny/tmp/hold_stuff/c.csv

options(warn = 2)
dir_map(hold_stuff, read.csv)
#> Error in scan(file = file, what = what, sep = sep, quote = quote, dec = dec, : (converted from warning) embedded nul(s) found in input

# wish I could do this
dir_map(hold_stuff, read.csv, glob = "*.csv")
#> Error in dir_map(hold_stuff, read.csv, glob = "*.csv"): unused argument (glob = "*.csv")

dir_delete(hold_stuff)
```

<sup>Created on 2020-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by jimhester** [comment]
This seems like a duplicate of https://github.com/r-lib/fs/issues/157.

As mentioned there it is not really possible to do due to the way `dir_map()` is implemented.

But you _can_ do the filtering in the function you pass to dir_map, or filter the paths and them map them.

**Comment by jennybc** [comment]
Yes, I agree this is a duplicate of #157.

I was already working with `dir_ls(glob = "*.csv") %>% map()` but was wondering if there was a way to put the filtering into `dir_map()` itself.

This is likely to be a recurring ask because all of these functions are documented together, leading to the hope that the inclusion/exclusion features of `dir_ls()` are easily added to `dir_map()`.
