### ISSUE TITLE
Inconsistent error produced when using dir_ls

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/fs#281]
Hi,

I don't really know how to create a reprex for this issue because I can't seem to predict when or why it shows up. Inconsistently, when running the _exact same_ piece of code that recursively searches a directory with `dir_ls()`, it sometimes works fine and sometimes produces an error like this one:
```
Error in dir_ls(dirs, recurse = 3L) : 
  Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'double'
```
However, even when this error does show up, it is not always the exact same error. Sometimes where it says `'double'` it shows other values. Really at a loss for what is happening.

For added context, I am `dir_ls`ing a directory which is a mounted volume on my Mac. Not sure if that is relevant or not.

**Comment by jimhester** [comment]
What version of fs are you using? This sounds like a bug that was fixed in the last release (1.4.1).

**Comment by mattwarkentin** [comment]
I am using `fs v1.4.1`.

**Comment by mattwarkentin** [comment]
Sometimes when it doesn't error out, the returned vector of paths is just a vector of `NULL`s. Run it again and it works, usually.

**Comment by fikovnik** [comment]
I experience similar issue (using the same version - 1.4.1).
Although for me, the behavior is fairly random:

```
> fs::dir_ls("run/package-evals", regex="/seq$", recurse=1, type="f")
 *** caught segfault ***
address 0x55fd05d7be90, cause 'invalid permissions'

Traceback:
 1: dir_map(old, identity, all, recurse, type, fail)
 2: dir_ls(path, regex = "/seq$", recurse = 1)
```
or 
```
> fs::dir_ls("run/package-evals", regex="/seq$", recurse=1, type="f")
Error in dir_map(old, identity, all, recurse, type, fail) :
  SET_VECTOR_ELT() can only be applied to a 'list', not a 'NULL'
> fs::dir_ls("run/package-evals", regex="/seq$", recurse=1, type="f")
Error in grep(x = path, pattern = regexp, value = TRUE, invert = isTRUE(invert),  :
  'translateChar' must be called on a CHARSXP, but got 'integer'
> fs::dir_ls("run/package-evals", regex="/seq$", recurse=1, type="f")
Error in structure(enc2utf8(x), class = c("fs_path", "character")) :
  CHAR() can only be applied to a 'CHARSXP', not a 'list'
> fs::dir_ls("run/package-evals", regex="/seq$", recurse=1, type="f")
run/package-evals/A3/seq
run/package-evals/x12/seq
run/package-evals/x12GUI/seq
run/package-evals/x13binary/seq
...
```

It does work sometimes, but most of the time it is one of the above error.
