### ISSUE TITLE
feature request - emulate linux WC command 

### ISSUE THREAD

**Issue by aetiologicCanada** [r-lib/fs#283]
functions to emulate the linux wc command directly into R, e.g.

fs::file_wc_lines()
fs::file_wc_words()

would be most welcome!

**Comment by jimhester** [comment]
I don't think fs is the package that should handle this. Counting lines is not a file system operation.

Alternatives are `length(readLines())` or if you are concerned about speed `length(vroom::vroom_lines())` to count newlines in a file. The latter should be as fast or faster than `wc -l` for large files.
