### ISSUE TITLE
file.remove for dirs created with dir_create fail

### ISSUE THREAD

**Issue by renejuan** [r-lib/fs#288]
I am having problem deleting a directory within R created using `file.remove`

```
dir <- "" # Add a directory of your liking
fs::dir_create(dir)
file.remove(dir) # Does not work; it says "Permission denied"

fs::dir_delete(dir) # It works
```

**Comment by jimhester** [comment]
You don't say what OS you are running on, but if you are on windows or if the directory contains files you need to use `file.remove(recursive = TRUE)` to remove the directory.
