### ISSUE TITLE
Permissions comparison not working as expected

### ISSUE THREAD

**Issue by briandconnelly** [r-lib/fs#292]
I'm hoping to check whether a file is private (i.e., has no group or other permissions granted). My approach has been to & those bits with "go+rwx" to highlight any group/other bits that are set and then check for equality with "go-rwx". This example, where I'm using `fs_perms("0640")` to represent a file with group read permissions, is returning `TRUE`, even though I'd expect the result to be `FALSE`:

```r
library(fs)

(fs_perms("0640") & fs_perms("g+rwx")) == "go-rwx"
```

Am I approaching the comparison operator incorrectly? I've tried several different ways to both set and compare the permissions.

**Comment by jimhester** [comment]
If none of the group or other bits is set the result of the bitwise and will be 0, and R interprets 0 as FALSE so you can just use it as a logical directly. e.g.

``` r
library(fs)
is_private <- function(p) {
  !as.logical(p & fs::fs_perms("go=rwx"))
}

is_private(fs_perms("u=rwx"))
#> [1] TRUE
is_private(fs_perms("u=rwx,g+r"))
#> [1] FALSE
is_private(fs_perms("u=r,o+rw"))
#> [1] FALSE
```

<sup>Created on 2020-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
