### ISSUE TITLE
Error: [EBUSY] Failed to copy

### ISSUE THREAD

**Issue by kkyong77** [r-lib/fs#298]
I am using "file_copy" command to copy list of files to a folder, but sometimes, I have gotten this message:

```
files<-list.files(pattern=glob2rx(paste("*.",Filename,sep="")))
file_copy(files,TxtInoutf,overwrite = TRUE)"
"Error: [EBUSY] Failed to copy '022930001.sol' to 'C:/Project/Columbia_SWAT/codes/SWAT_CalbR/SWAT_CalbR/TxtInOut1/022930001.sol': resource busy or locked
Execution halted"
```

**Comment by jimhester** [comment]
On windows you cannot write to a location of that file is open by any other program. It is possible you have this file open elsewhere.

**Comment by kkyong77** [comment]
thank you.
