### ISSUE TITLE
Cygwin installation error 

### ISSUE THREAD

**Issue by MaikeHu** [r-lib/fs#299]
I am trying to install the fs package in R (v 4.0.2) on the 64-bit Cygwin, but keep getting the same error in the installation process, which then fails. Here is the output of the installation:

[CygwinR_FSinstallError.txt](https://github.com/r-lib/fs/files/5407355/CygwinR_FSinstallError.txt)

I am not sure what is causing the error, but it always gives me the warning about 'optreset', 'sed' and 'make'. I have also tried installing various ways (also previous versions and directly from the .tar.gz files)

Is this an incompatibility issue, or am I missing something for the installation?

Thank you in advance for your help!

**Comment by jimhester** [comment]
It looks to me like a quoting issue, but I can't help you too much further, I have never heard of someone trying to use R from cygwin, typically R users on Windows use [Rtools](https://cran.r-project.org/bin/windows/Rtools/) for packages with compiled code.

**Comment by MaikeHu** [comment]
Ah okay, thank you for taking a look. I've been seeing if I can get a bioinformatics R package designed for Linux/Mac to work on Windows through Cygwin, and one of its dependencies is devtools/fs. Normally, I would have just used R in Windows!
Thank you again.
