### ISSUE TITLE
Eliminate normalisation in file_move?

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#3]
Currently:

```R
file_move("NAMESPACE", "src/")
#>  Error in move_(path_norm(path_expand(path)), new_path) : 
#>  '/Users/hadley/Documents/r-lib/fs/NAMESPACE': illegal operation on a directory 
```

(I'd also be nice to eliminate the function name from the error message, but I've forgotten how to do that)

I'm not sure why we can't just do `move_(path_expand(path), path_expand(new_path))`. That gives:

```R
#> Error in move_(path_expand(path), path_expand(new_path)) : 
#>  'NAMESPACE': illegal operation on a directory 
```

This make also speak to needing custom error messages since here it'd be nice to also see the destination (which is the source of the problem)

**Comment by jimhester** [comment]
I removed the normalization in f983d59f, I don't think it is needed.

But that doesn't fix this error, which is happening because we need to append the basename to the directory if `new_path` is a directory. Will keep this open until that is fixed.

**Comment by hadley** [comment]
Yeah we should get this error for rename, but not move.

**Comment by jimhester** [comment]
`file_move` now handles the case of moving into a directory https://github.com/r-lib/fs/commit/0cdf8ca7fbdf3680bcfcd00e9ecd6a25f5ba0e82
