### ISSUE TITLE
dir_ls() cannot prepend the directory path as base::list.files() can

### ISSUE THREAD

**Issue by GitHunter0** [r-lib/fs#300]
I cannot find an option in dir_ls() to replicate list.files(full.names = TRUE). 
It would be very good not to have this limitation. Would you please consider implementing that?
Thank you.

**Comment by jimhester** [comment]
You can do this a number of ways.

1. by composing `fs::path_wd()` and `fs::dir_ls()`. e.g.

```r
fs::path_wd(fs::dir_ls("."))
```

Or by passing an absolute path rather than a relative path.

```r
fs::dir_ls(fs::path_abs("."))
```

I don't feel an argument is necessary, but I added an example of this in the documentation for `dir_ls()`.

**Comment by GitHunter0** [comment]
@jimhester Got it man, it is good enough, than you.
