### ISSUE TITLE
Segfault when running script but not when running interactively

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/fs#308]
Hi,

I'm running into a weird error that I haven't been able to diagnose. When I run a `dir_ls()` command in the RStudio IDE or in an interactive R session in the terminal, the command works fine. But when I run the script via `Rscript`, it fails with this error, every time.
```
 *** caught segfault ***
address 0x7fd26000d8e0, cause 'memory not mapped'

Traceback:
 1: dir_map(old, identity, all, recurse, type, fail)
 2: dir_ls("../scans/", recurse = TRUE, type = "file")
An irrecoverable exception occurred. R is aborting now ...
Segmentation fault: 11
```

Any idea what would cause that type of error to be thrown? I've tried both the CRAN and dev versions of `fs`.

**Comment by mattwarkentin** [comment]
I'm able to make the error go away by changing the command from
```r
dir_ls("../scans/", recurse = TRUE, type = "file")
```
to
```r
dir_ls("../scans/", recurse = TRUE, type = "directory")
```

**Comment by mattwarkentin** [comment]
After further testing, the command below works with `recurse` equal to `0L`, `1L`, and `2L`, but the segfault pops up for `3L`...
```r
dir_ls("../scans/", recurse = TRUE, type = "file")
```

**Comment by rpln** [comment]
> @mattwarkentin i'm experiencing the exact same error. Did you find a solution?

@peterchristofferholm 

Me too, I think this is a real issue and we should reopen this if possible

**Comment by gaborcsardi** [comment]
Can you please provide a reproducible example, and also a stack trace? Thanks!

**Comment by mattwarkentin** [comment]
@peterchristofferholm and @rpln I don't recall ever finding the root issue or a solution. Sorry.

**Comment by rpln** [comment]
@gaborcsardi, I'll try to make something reproducible, however it will be a bit challenging. 

Some details I can share: It currently only happens on a particular directory structure within a SMB (from Window Server) mount onto Ubuntu. Within that Ubuntu, we're running R in Docker with that SMB mount volumed into the container (in a read only mode). I suspected it was a problematic file or directory (and I'll do some iteration to see if I can find this), however that doesn't explain the _working in interactive mode_ bit.
