### ISSUE TITLE
ERROR: compilation failed for package ‘fs’

### ISSUE THREAD

**Issue by sielerjm** [r-lib/fs#317]
Hi, 

I'm trying to install devtools and one of the dependencies (fs) failed to install. I'm running a miniconda environment on a linux server (sessionInfo() included below). The main error appears to be:
```
mkdir: cannot create directory '/data/cg25179-24374': Permission denied
mkdir: cannot create directory '/data/cg-25179': Permission denied
config.guess: cannot create a temporary directory in /data
configure: error: cannot guess build type; you must specify one
make: *** [Makevars:31: libuv-1.38.1/Makefile] Error 1
ERROR: compilation failed for package ‘fs’
```

I receive this error when I try installing fs using `install.packages("fs")` and `BiocManager::install("fs")`.

I have no idea where `/data/...` are located to try and change the directory permissions. I'm not sure if it's entirely relevant, but here is the [all output from when I tried installing fs](https://pastebin.com/G4vBt1aS).

Here is my session info:

```> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-conda_cos6-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

Matrix products: default
BLAS/LAPACK: /raid1/home/micro/sielerjm/.conda/envs/R-v4.0.2/lib/libopenblasp-r0.3.10.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

loaded via a namespace (and not attached):
[1] BiocManager_1.30.10 compiler_4.0.2      tools_4.0.2```

I'd appreciate any guidance in solving this. Thanks!

**Comment by jimhester** [comment]
Theses sorts of configuration questions are a better fit for <https://community.rstudio.com>. Do you mind asking it over there? (You might want to read <https://www.tidyverse.org/help/> first to maximise your chances of getting a good answer)
