### ISSUE TITLE
Sort order varies between Windows and macOS/Linux?

### ISSUE THREAD

**Issue by krlmlr** [r-lib/fs#318]
I'm seeing peculiar differences in sort order between Windows and macOS/Linux in a test that runs `expect_snapshot({dir_tree(...)})`: https://github.com/cynkra/indiedown/runs/2130837120?check_suite_focus=true#step:13:253. Since `dir_tree()` forwards to `dir_ls()` and `dir_map()`, I suspect all `dir_()` functions will have this problem.

Is it possible to return the files sorted in the C locale?

**Comment by jimhester** [comment]
The order is dependant on what the operating system, in particular what `strcmp` returns for the directory names (https://github.com/libuv/libuv/blob/c464d213231ea371c4e9bddaa6455cf8a426a0fe/src/unix/fs.c#L537-L539)

I don't think it is really desired or practical for fs to change this. In general I don't think you can rely on the collation order to be consistent across operating systems.
