### ISSUE TITLE
`file_exists()` does not perform path expansion (anymore)

### ISSUE THREAD

**Issue by lorenzwalthert** [r-lib/fs#325]
on macOS. Maybe related to #295? This is likely to break the reverse dependency test.

```r
> fs::file_exists(fs::path_expand('~'))
/Users/lorenz 
         TRUE 
> fs::file_exists('~')
    ~ 
FALSE 
> packageVersion('fs')
[1] ‘1.5.0.9000’
```

Previously, this worked:
```r
> fs::file_exists(fs::path_expand('~'))
/Users/lorenz 
         TRUE 
> fs::file_exists('~')
    ~ 
TRUE 
> packageVersion('fs')
[1] ‘1.5.’
```

Related: https://github.com/r-lib/fs/issues/222

**Comment by lorenzwalthert** [comment]
It just broke one of my builds now that it's on CRAN and I forgot about it and found the half a year old issue. This potentially breaks peoples code.

**Comment by lorenzwalthert** [comment]
This breaks the {precommit} installation for all people on macOs who installed with `pip3 install pre-commit --user`. :-(

**Comment by gaborcsardi** [comment]
Yes, it seems that now we need to call `path_expand()` in `file_exists()`. If this breaks lots of code, then we can have a patch release soon.

**Comment by lorenzwalthert** [comment]
I mean it (apparently) did not break CRAN packages but I imagine people also have this in in their analysis code. I'd appreciate a patch release but I'll anyways release a new {precommit} version.

**Comment by gaborcsardi** [comment]
It seems to me that most `file_*` functions call `path_expand()`, so `file_exists()` should do the same.

**Comment by salim-b** [comment]
> I mean it (apparently) did not break CRAN packages (...)

It actually *did* break the **pins** pkg when used with [local folder boards](https://pins.rstudio.com/reference/board_folder.html) created with e.g. `board_folder(path = "~/my_board")` because of [this line](https://github.com/rstudio/pins/blob/main/R/meta.R#L6). Just cost me over an hour to figure that out. 😬

**Comment by gaborcsardi** [comment]
I will make a new release in ~ 2 days.

**Comment by jennybc** [comment]
It turns out this is being felt via usethis as well.
