### ISSUE TITLE
Column type in `dir_info()$path` differs to `dir_ls()`

### ISSUE THREAD

**Issue by KevinKotze** [r-lib/fs#330]
Hi,

When using `fs` version 1.5.0.900 and earlier versions, the column type in `dir_info()$path` differs to `dir_ls()`

```
> all_equal(fs::dir_info()[1,1], tibble(path = fs::dir_ls()[1]))
[1] "- Different types for column `path`: fs_path vs fs_path\n"
```

I suspect that the type of column in `dir_info()` is incorrect, since it is difficult to pass this result onto other commands, while `dir_ls()` works perfectly.

**Comment by gaborcsardi** [comment]
I cannot reproduce this:

```r
❯ fs::dir_info()[1,1]
# A tibble: 1 × 1
  path
  <fs::path>
1 DESCRIPTION

❯ tibble(path = fs::dir_ls()[1])
# A tibble: 1 × 1
  path
  <fs::path>
1 DESCRIPTION

❯ identical(fs::dir_info()[1,1], tibble(path = unname(fs::dir_ls()[1])))
[1] TRUE
```

If you think there is still a problem in fs, please reopen this with a reproducible example. Thanks!
