### ISSUE TITLE
`file_create()` and `dir_create()` return wrong path

### ISSUE THREAD

**Issue by davidchall** [r-lib/fs#332]
According to the [documentation](https://fs.r-lib.org/reference/create.html), `file_create()` and `dir_create()` are supposed to return

> The path to the created object (invisibly).

However, instead they return the `path` argument. When `...` arguments have been used, this is not the same as the path to the created object. I think this might have been introduced by https://github.com/r-lib/fs/commit/6ee3322076bd2cb6b9cacd0b52ac1717b11996e4.

``` r
library(fs)

out_path <- file_create(tempdir(), "foo.txt")
out_path
#> /var/folders/pn/sn7ybdms78x_1pgjr17pv8v40000gn/T/RtmpfZdUtx

out_path <- dir_create(tempdir(), "foo", "bar")
out_path
#> /var/folders/pn/sn7ybdms78x_1pgjr17pv8v40000gn/T/RtmpfZdUtx
```

<sup>Created on 2021-05-13 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jimhester** [comment]
Thanks you are correct. Are you interested in doing a PR to fix the issue?

**Comment by davidchall** [comment]
@jimhester - Sure! 🙂 While writing that, I discovered a separate related bug. It's all described in #333.
