### ISSUE TITLE
shortening `fs_path` content when printing tibbles

### ISSUE THREAD

**Issue by dholstius** [r-lib/fs#335]
Hi and thanks for the great package! If this feature is already available in some manner, my apologies.

I'd like to (optionally) shorten the display of `fs_path` objects in a vector when they're long, so that the ellipsis is on the left-hand side instead of the right. 

So, instead of:

```
library(tidyverse)
library(fs)

# current output formatting puts the ellipsis on the right side
x <- str_c("/lorem/ipsum/egestas/molestie/id/id/lacinia/feugiat/lacinia/augue/placerat/", c("apple", "banana", "cherry"), ".txt")
df <- tibble(path = fs::fs_path(x))
show(df)

# A tibble: 3 x 1
  path                                         
  <fs::path>                                   
1 /lorem/ipsum/egestas/molestie/id/id/lacinia/…
2 /lorem/ipsum/egestas/molestie/id/id/lacinia/…
3 /lorem/ipsum/egestas/molestie/id/id/lacinia/…
```

... one would instead (optionally) see something more like:

```
library(pillar)

# something like the desired output
df <- tibble(path = pillar::char(fs::fs_path(x), shorten = "front"))
show(df)

# A tibble: 3 x 1
  path                               
  <fs::path>                         
1 …/lacinia/augue/placerat/apple.txt 
2 …/lacinia/augue/placerat/banana.txt
3 …/lacinia/augue/placerat/cherry.txt
```

This could be useful when a long path prefix is common to all elements and the right side (the basenames and leaf-level subdirectories) is the thing that's varying a lot.

Maybe this could be controlled via `options(fs.fs_path.shorten = "front")`?

**Comment by jimhester** [comment]
Thanks for opening the issue, it seems like good idea, I have made it so, and actually changed the default to "front", as I think generally the end of the path is more useful to see than the start.
