### ISSUE TITLE
Path arithmetic, e.g. finding/removing common stem

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#34]
Any chance we can have something like this?

https://github.com/richfitz/pathr/blob/master/R/rel.R

**Comment by jimhester** [comment]
This should get us most of the way there, minus some fiddling with trailing slashes / same input paths.

```r
path_rel <- function(path, base = ".") {
  path <- path_tidy(path_norm(path))
  base <- path_tidy(path_norm(base))
  path_tidy(sub(base, "", path, fixed = TRUE))
}
```

**Comment by jennybc** [comment]
Also: check out the stub for `os.path.commonprefix()` that got removed in this commit:

https://github.com/richfitz/pathr/commit/e742bc5ec541da3728181dfeac1acfa0fefe076b

that would be really useful too

**Comment by jennybc** [comment]
I guess the most proper Python references are `os.path.commonpath(paths)` and `os.path.relpath(path, start=os.curdir)` in [os.path](https://docs.python.org/3/library/os.path.html).

**Comment by jennybc** [comment]
And one more (I promise I'll stop now):

https://docs.rs/pathdiff/0.1.0/pathdiff/fn.diff_paths.html

**Comment by jimhester** [comment]
We now have `path_relative()`

``` r
as.character(fs::path_relative(c("a", "a/b", "a/b/c"), "a/b"))
#> [1] ".." "."  "c"
```

Created on 2018-01-10 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by jennybc** [comment]
It's beautiful.
