### ISSUE TITLE
fs_perms columns causing issues with RStudio Viewer

### ISSUE THREAD

**Issue by rundel** [r-lib/fs#342]
The following reprex causes an error in RStudio (1.4.1725 Desktop on MacOS and 1.3.1056 Server on Linux):

```r
library(fs)

d = data.frame(
  a = "test",
  b = c(0L)
) 

class(d$b) = "fs_perms"

View(d)
```

The console reports the following errors:
```
Error in FUN(X[[i]], ...) : 
  INTEGER() can only be applied to a 'integer', not a 'double'
Error in FUN(X[[i]], ...) : 
  INTEGER() can only be applied to a 'integer', not a 'double'
```
and the tab in RStudio reports `r error 4 (R code execution error)`.

This originally occurred when attempting to `View()` the results of a large `fs::dir_info()` call.

**Comment by jimhester** [comment]
IMHO this is an RStudio bug, they are unconditionally using `storage.mode()` to coerce all vectors where `is.numeric()` returns `TRUE` to doubles at https://github.com/rstudio/rstudio/blob/0420c874afa261819a91d6ecf12c3d85cb4df7d6/src/cpp/session/modules/SessionDataViewer.R#L65, even though in this case the `format.fs_perms` function is correctly assuming the vector should actually be an integer. So then when the `format()` method runs on it it fails. A minimal reprex is

```r
x <- fs::as_fs_perms("777")
storage.mode(x) <- "double"
format(x)
```

**Comment by rundel** [comment]
Makes sense, I've opened an issue over there - thanks for digging into the underlying cause.

**Comment by jimhester** [comment]
Thanks!
