### ISSUE TITLE
An improper locking due to the unreleased lock global_epoll_lock

### ISSUE THREAD

**Issue by ryancaicse** [r-lib/fs#347]
Hi developers, in the below codes, the lock `global_epoll_lock` could be not released before program's exit `abort(); `. I think there is no harm to write `uv_mutex_unlock(&global_epoll_lock);`  before the `abort(); ` for better resource management and code symmetry. Thanks!

https://github.com/r-lib/fs/blob/0895f1a897ebf3e1c7a2223438fad6313a1e3f1f/src/libuv-1.38.1/src/unix/os390-syscalls.c#L241-L276

**Comment by jimhester** [comment]
The code you reference is from the upstream [libuv](https://github.com/libuv/libuv/issues) project, if the issue you observe is still present in the current version of libuv I would suggest you open an issue there.
