### ISSUE TITLE
Inconsistencys among file_exists and path_dir with ~ on windows.

### ISSUE THREAD

**Issue by FlorianMyronStork** [r-lib/fs#350]
My Company i am working at uses Onedrive:
```
Sys.getenv("HOME")
#> "C:\\Users\\florian.stork\\OneDrive - My Company\\Dokumente"
Sys.getenv("HOMEPATH")
#> "\\Users\\florian.stork"
```

I was building a path using path_dir and wanted to test for file existence. This was when i stumbled upon some inconsitency:
```
fs::file_create(fs::path_expand_r("~"), "any_file")
any_file_path <- "~/any_file"
fs::path_dir(any_file_path)
#> "C:/Users/florian.stork/OneDrive - My Company/Dokumente"
fs::file_exists(any_file_path)
#> ~/any_file 
#> FALSE 
base::file.exists(any_file_path)
#> TRUE
```

path_dir constructs the whole path using sysenv "HOME" while file_exists seems to look into "HOMEPATH"

I know that i can work arround this by using `path_expand()` and `path_expand_r()`
but that behavior isn't very intuitive. Because `fs::file_create()` also creates within sysenv "HOMEPATH".

Maybe you could add some options which path should be referred to when `~` is involved.

Cheers, and great package so far! I absolutely love it :)

**Comment by gaborcsardi** [comment]
I have just updated `file_exists()` to expand `~`, can you please check if that solves your issue. Thanks!

**Comment by FlorianMyronStork** [comment]
@gaborcsardi Yes indeed - that solved my problem! Thank you very much!
