### ISSUE TITLE
Unclear documentation of `link_create()`

### ISSUE THREAD

**Issue by rorynolan** [r-lib/fs#356]
In `link_create(path, new_path, symbolic = TRUE)`, it's not clear to me which is the `path` and which is the `new_path`. In `bash`'s `ln`, it's documented as `ln -s TARGET LINK_NAME` which I find much more clear. In particular, it's not clear which path is the _new_ path: the location of the newly created link or the location that it points to.

If you think that a change should be made, I'm happy to do a PR.

Thanks for `fs` I use it all the time.

**Comment by gaborcsardi** [comment]
Well, we cannot easily change the name of the argument, I am afraid, that would be a breaking change. 

`new_path` does not seem too bad to me, the `new_` prefix indicating that that is the link that is _newly_ created, and the docs say

```
> new_path: The path where the link should be created.
```

If you think we can improve the docs, then I am happy to look at a PR. Thanks!

**Comment by rorynolan** [comment]
Yeah perhaps you're right that the `new_path` doc isn't so bad.
I think you've got to get the word _target_ in there. `path` doesn't mean a whole lot. 
This may require moving `link_create()` away from `file_create()` and `dir_create()` or I guess you could just add a sentence onto the `path` doc to say _For `link_create()`, this is the target path_.

**Comment by gaborcsardi** [comment]
Yeah, adding that to the man page seems useful I think.

**Comment by rorynolan** [comment]
Alrighty. I'll do a PR for it. If you change your mind and don't want it, no hard feelings.
Thanks for the quick responses and all of your great work.
