### ISSUE TITLE
testsuite throws errors in version 1.5.1

### ISSUE THREAD

**Issue by tillea** [r-lib/fs#359]
Hi,
I tried to package the latest fs for Debian but unfortunately some tests are failing:

    ══ Failed tests ════════════════════════════════════════════════════════════════
    ── Failure (test-access.R:14:7): file_access: checks for file read and write ability ──
    file_access("foo/bar", "read") not equal to c(`foo/bar` = FALSE).
    1 element mismatch
    ── Failure (test-access.R:15:7): file_access: checks for file read and write ability ──
    file_access("foo/bar", "write") not equal to c(`foo/bar` = FALSE).
    1 element mismatch
    ── Failure (test-list.R:78:5): dir_ls: warns if fail == FALSE ──────────────────
    `dir_ls(".", recurse = TRUE)` did not throw an error.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:78:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_error(dir_ls(".", recurse = TRUE), class = "EACCES") test-list.R:83:6
    ── Failure (test-list.R:78:5): dir_ls: warns if fail == FALSE ──────────────────
    `dir_ls(fail = FALSE, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:78:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:84:6
    ── Failure (test-list.R:78:5): dir_ls: warns if fail == FALSE ──────────────────
    `dir_ls("foo2", fail = FALSE, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:78:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:88:6
    ── Failure (test-list.R:111:5): dir_map: warns if fail == FALSE ────────────────
    `dir_map(".", fun = identity, recurse = TRUE)` did not throw an error.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:111:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_error(...) test-list.R:116:6
    ── Failure (test-list.R:111:5): dir_map: warns if fail == FALSE ────────────────
    `dir_map(fail = FALSE, fun = identity, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:111:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:117:6
    ── Failure (test-list.R:111:5): dir_map: warns if fail == FALSE ────────────────
    `dir_map("foo2", fail = FALSE, fun = identity, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:111:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:121:6
    ── Failure (test-list.R:161:5): dir_walk: warns if fail == FALSE ───────────────
    `dir_walk(".", fun = identity, recurse = TRUE)` did not throw an error.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:161:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_error(...) test-list.R:166:6
    ── Failure (test-list.R:161:5): dir_walk: warns if fail == FALSE ───────────────
    `dir_walk(fail = FALSE, fun = identity, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:161:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:167:6
    ── Failure (test-list.R:161:5): dir_walk: warns if fail == FALSE ───────────────
    `dir_walk("foo2", fail = FALSE, fun = identity, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:161:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:171:6
    ── Failure (test-list.R:192:5): dir_info: warns if fail == FALSE ───────────────
    `dir_info(".", fun = identity, recurse = TRUE)` did not throw an error.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:192:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_error(...) test-list.R:197:6
    ── Failure (test-list.R:192:5): dir_info: warns if fail == FALSE ───────────────
    `dir_info(fail = FALSE, fun = identity, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:192:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:198:6
    ── Failure (test-list.R:192:5): dir_info: warns if fail == FALSE ───────────────
    `dir_info("foo2", fail = FALSE, fun = identity, recurse = TRUE)` did not produce any warnings.
    Backtrace:
        █
     1. ├─fs:::with_dir_tree(...) test-list.R:192:4
     2. │ └─base::force(code) helper.R:22:2
     3. └─testthat::expect_warning(...) test-list.R:202:6

    [ FAIL 14 | WARN 0 | SKIP 3 | PASS 3439 ]

Please note:  For the Debian package we are using the Debian packaged libuv.  In case you might suspect an issue here for the said tests please let us know so we can dig into this direction.
Kind regards, Andreas.

**Comment by gaborcsardi** [comment]
I think these tests fail because you run them as root, and the test cases expect "access denied" errors, which will not happen if you are the root user.

**Comment by gaborcsardi** [comment]
Closed by 8747eb5b916253a1210ad2273b01b2c07d7763c6

**Comment by tillea** [comment]
Hi Gábor,

Am Mon, Dec 06, 2021 at 03:57:52AM -0800 schrieb Gábor Csárdi:
> I think these tests fail because you run them as root, and the test cases expect "access denied" errors, which will not happen if you are the root user.
This is a pretty sensible explanation since my build environment is a chroot where root is building.  The tests are passing in a different CI environmen.
Thanks a lot for checking, Andreas.
