### ISSUE TITLE
User & group return NA

### ISSUE THREAD

**Issue by rjake** [r-lib/fs#368]
Thanks for building this package. When I use `dir_info()` or `file_info()`, I get `NA` for `user` and `group`. I didn't see an issue related to this. Is this unexpected?

&emsp;&emsp;&emsp; ![image](https://user-images.githubusercontent.com/14003618/151022457-b5344ab5-1c37-45f2-9ea3-5b187cbdcfe7.png)

These are the details about my OS and R
```
 version  R version 4.1.2 (2021-11-01)
 os       Windows 10 x64 (build 18363)
 system   x86_64, mingw32

**Comment by gaborcsardi** [comment]
Yes, it is expected, the `_stat` system call does not give us this information on Windows: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/stat-functions?view=msvc-170
