### ISSUE TITLE
fs::file_exists returns false for existing files on Window

### ISSUE THREAD

**Issue by danielruss** [r-lib/fs#369]
Hi.  The boxr package caches an oauth token in the file \~/.boxr-oauth.  During a forced refresh, the code uses fs::file_exists to check if the token exists.  However, on windows, even though the \~/.boxr-oauth file exist, file_exists return false.  

I don't believe this is caused by the '.', because when in the ~ directory on windows file_exists works correctly.  This is not a path expansion problem, because `fs::file_exists(fs::path_expand("~/.boxr-oauth"))` returns false. 

The issue in the boxr repository is https://github.com/r-box/boxr/issues/219.  It contains the session info. 

Happy to provide more details if needed.

**Comment by gaborcsardi** [comment]
I cannot reproduce this:
```
❯ echo foo > C:\Users\csard\.boxr-oauth
❯ R-4.1.2.bat -q
> fs::file_exists("~/.boxr-oauth")
~/.boxr-oauth
         TRUE
> fs::file_exists(fs::path_expand("~/.boxr-oauth"))
C:/Users/csard/.boxr-oauth
                      TRUE
```

Do you have non-ascii characters in the home directory path? What does `~` expand to? Is `fs::path_expand("~")` the same as `path.expand("~")`?

**Comment by danielruss** [comment]
path.expand expands to "C:/Users/<username>/Documents/.boxr-oauth" So it is the same as yours.  Can this be a versioning problem? or maybe a hidden file problem?

**Comment by gaborcsardi** [comment]
> path.expand expands to "C:/Users//Documents/.boxr-oauth"

OK, but what does `fs::fs_expand("~")` expand to?

**Comment by gaborcsardi** [comment]
So `fs_expand("~")` is `C:/Users/<username>/Documents` and `path_expand("~")` is `C:/Users//Documents`?

**Comment by danielruss** [comment]
the markdown in my response was off.  The \<username\> was left out because I forgot to escape the \< and \>

**Comment by gaborcsardi** [comment]
So the output is `C:/Users/<username>/Documents` for both?

**Comment by danielruss** [comment]
fs_expand is not exported.

**Comment by gaborcsardi** [comment]
Sorry, I meant `fs::path_expand()`.

**Comment by danielruss** [comment]
![image](https://user-images.githubusercontent.com/3767675/155226456-daceb06b-12df-4808-8821-fc7a74c6b7a4.png)

**Comment by danielruss** [comment]
Yes, there is a difference between path.expand and  fs::path.expand. I  think we are getting close to the root problem.

**Comment by gaborcsardi** [comment]
fs always uses the "real" home directory instead of `Documents`. You can read `?fs::path_expand` for details. 

So my guess is that boxr (?) created the file using some base R function, which put it in `Documents` and then uses `fs::file_exists()` to check if it is there and that uses a different path. Or an earlier version of boxr used the `Documents` path, and the new one the proper home directory. 

In any case, nothing points to fs having an issue here.

**Comment by danielruss** [comment]
Thank you @gaborcsardi.  @jennybc commented on our original issue.  We have a way forward.  thank you.
