### ISSUE TITLE
Handling of URL encoded paths

### ISSUE THREAD

**Issue by chrisbrownlie** [r-lib/fs#371]
Should URL encoded paths be handled by fs functions or is that not possible/desirable? Apologies if a stupid question!

For example, when there are spaces in folder names:
```{r}
folder_path <- "~/foo bar/image.png"
encoded_folder_path <- utils::URLencode(folder_path)

fs::path_rel(folder_path, encoded_folder_path)
# doesn't give the same result as
fs::path_rel(folder_path, folder_path)
```

I only ask because I'm having an issue with a pkgdown site, when building vignettes (i.e. `pkgdown::build_article()`): 
- `rmarkdown::render()` encodes image src paths as URLs, because an output_dir is set
- `pkgdown:::tweak_rmarkdown_html()` uses `fs::path_rel()` to replace absolute paths with relative paths
-  So image src paths are being converted to something like '../../../../../../../../../../{full url encoded path}'
-  I'm getting an error saying my file paths are too long

I can see three possibilities
1) `fs::path_rel` can/should handle URL encoded paths
2) there is/should be an option for rmarkdown to avoid URL encoding image src paths?
3) neither of the above is possible/desirable for some reason and it is just an unavoidable side effect of me having long file paths with spaces in

I'm not sure which of these is true (if any) so any help is much appreciated! Also if this isn't the right place for this question let me know, happy to post somewhere else instead if necessary.

**Comment by chrisbrownlie** [comment]
OK, thats understandable. Thanks for the quick reply. The error message is
```{r}
Error in path_tidy(.Call(fs_path_, lapply(args, function(x) enc2utf8(as.character(x))),  : 
  Total path length must be less than PATH_MAX: 260
```
Which is confusing because although I do have fairly long file paths, none of them are anywhere near 260 characters (I assume it is referring to characters?). I thought I'd figured out that was originating from the fs::path_rel conversion but maybe I'm wrong.
If I get time I'll try and reproduce it with a small package as you suggest.

**Comment by gaborcsardi** [comment]
Seems like libuv supports long paths now, so maybe all we need is removing the check on newer Windows: https://github.com/libuv/libuv/blob/2e42847f4efa77ff5e5b217a33536f341b0a3f1a/ChangeLog#L508

**Comment by chrisbrownlie** [comment]
OK thanks. I did a bit more digging and it is as I suspected, pkgdown is checking that a file exists using 
```
exists <- fs::file_exists(path(pkg$dst_path, rel_path))
```
where dst path is '{path}' and rel_path is '../../../../../../../{url encoded path}', so path lengths are effectively being doubled. I'll try and find out if there is a way to have rmarkdown not URL encode paths, or a way for pkgdown to use knitr::knit instead as I think that may solve it too, [by the sounds of it](https://stackoverflow.com/questions/52299423/how-to-prevent-urlencoding-of-liquid-tags).

**Comment by chrisbrownlie** [comment]
In case anyone else has the same problem as me in future, I found that this issue has been discussed before and there has always been issues with images in vignettes when a path has spaces in. Sounds like there isn't really anything to do about it - pkgdown can't be used for packages with spaces in their path unfortunately (https://github.com/r-lib/pkgdown/issues/1218)
