### ISSUE TITLE
Making directories recursively with limited permissions on a network share

### ISSUE THREAD

**Issue by jimhester** [r-lib/fs#38]
Need to verify this use case works with `fs::dir_create()`.

https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17159

**Comment by markvanderloo** [comment]
The `fs` package has the same issue as `base::dir.create`. Circumstances:

Windows network, say `//companynet/general/yourhome`. We wish to create `foo/bar`. It doesn't work since users have no right to write in higher levels then their home directory.

Assuming current working directory is `yourhome`

```r
d <- "foo/bar"
d <- file.path(getwd(),d)
# this fails:
dir.create(d, recursive=TRUE)
# this also fails
fs::dir_create(d, recursive=TRUE)
```
A workaround is to add `foo` and `bar` one by one. See example code [here](https://github.com/markvanderloo/dircreate/blob/master/pkg/R/dircreate.R)

**Comment by jimhester** [comment]
You can't check for folder existence before trying to create the folder, because another process could create (or delete) the folder before you call mkdir.

What is the _exact_ error you get from fs when this happens?

**Comment by markvanderloo** [comment]
```r
> library(fs)
Warning message:
package ‘fs’ was built under R version 3.4.3
> map <- "foo/bar"
> map <- file.path(getwd(),map)
> map
[1] "\\\\cbsp.nl/Profiel/Productie/MPLO/Desktop/foo/bar"
> base::dir.create(map,recursive=TRUE)
Warning message:
In base::dir.create(map, recursive = TRUE) :
  cannot create dir '\\cbsp.nl\Profiel', reason 'Permission denied'
> fs::dir_create(map,recursive=TRUE)
Error: [EPERM] Failed to make directory '//cbsp.nl/Profiel': operation not permitted
```
and here's the sessioninfo:
```r
> sessionInfo()

R version 3.4.1 (2017-06-30)

Platform: i386-w64-mingw32/i386 (32-bit)

Running under: Windows 7 (build 7601) Service Pack 1

Matrix products: default

locale:

[1] LC_COLLATE=Dutch_Netherlands.1252  LC_CTYPE=Dutch_Netherlands.1252    LC_MONETARY=Dutch_Netherlands.1252

[4] LC_NUMERIC=C                       LC_TIME=Dutch_Netherlands.1252   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base    
other attached packages:
[1] fs_1.0.0        dircreate_0.1.0
loaded via a namespace (and not attached):
[1] compiler_3.4.1 rmsfact_0.0.3  Rcpp_0.12.12   cowsay_0.5.0   fortunes_1.5-4
> 
```

**Comment by jimhester** [comment]
Thanks, should be fixed by https://github.com/r-lib/fs/commit/8104dd62717259b3b3926f69dc3837d9d3c0a7fc

**Comment by markvanderloo** [comment]
Good news everyone, it is now also fixed in R :-) 

[https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17159]()
