### ISSUE TITLE
`file_move()` and `file_delete()` did not work recursively

### ISSUE THREAD

**Issue by hongyuanjia** [r-lib/fs#393]
It is very common to use `dir_ls()` with `glob` or `regexp` to filter some files and move them into a target directory. However, `file_move()` did not work recursively. Neither did `file_delete()`. The reason for the error `file_delete()` is straightforward, since it runs `dir_delete()` on all directories first, then all file unlink.

Is this the expected behavior? If so, what is the suggested way to handle file moving or deleting recursively using {fs}? Thanks!

``` r
get_files <- function() {
    fs::dir_create("dir1/dir2")
    fs::file_create(fs::path("dir1/dir2", letters[1:5]))
    fs::dir_ls("dir1", recurse = TRUE)
}

fs::dir_create("dir3")
fs::file_move(get_files(), "dir3")
#> Error: [ENOENT] Failed to move 'dir1/dir2/a'to 'dir3/a': no such file or directory

fs::file_delete(get_files())
#> Error: [ENOENT] Failed to remove 'dir1/dir2/a': no such file or directory

file.remove(get_files()) # base::file.remove only works for files
#> Warning in file.remove(get_files()): cannot remove file 'dir1/dir2', reason
#> 'Permission denied'
#> [1] FALSE  TRUE  TRUE  TRUE  TRUE  TRUE
unlink(get_files()) # base::unlink() works
```

<sup>Created on 2022-09-10 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by gaborcsardi** [comment]
```
> fs::file_move(get_files(), "dir3")
```
You don't need `recurse = TRUE` for this, when you move a directory, it is always recursive because the whole directory is moved, including the subdirectories.

The same is true for `file_delete()`, no need to look up the files/directories recursively, the deletion is recursive, you cannot delete a directory and keep the files or subdirectories in it.
