### ISSUE TITLE
Function to make relative paths

### ISSUE THREAD

**Issue by GitHunter0** [r-lib/fs#396]
Hi folks, would you consider building a function to make relative paths, something like `make.path.relative(base.path, target.path)`?

It is an useful feature that I believe `fs` is missing.

There are details here: https://stackoverflow.com/questions/36726186/function-for-constructing-relative-paths-in-r

Thank you

**Comment by jennybc** [comment]
Have you seen `path_rel()`?

> `path_rel`: computes the path relative to the start path, which can be either an absolute or relative path.

https://fs.r-lib.org/reference/path_math.html

**Comment by GitHunter0** [comment]
Thank you @jennybc ! That is what I was looking for, just inserting the `base.path` in the `start` parameter did the job.
