### ISSUE TITLE
Copy directory tree but only keeping some files (e.g. CSVs)

### ISSUE THREAD

**Issue by orgadish** [r-lib/fs#399]
I have a server with data saved in a particular folder structure with CSV files I care about and others I don't, like images that take up a lot of space. I want to copy only the CSV files locally to my computer, but keep the directory structure so that I can then run the same analysis directly on the server.

I don't think there's a way of doing this easily with any current `fs` function, other than to write my own looping function that uses `dir_create` and `file_copy`. It would be great if there was either a new function that does this. I'd think it should either interface with the results of `dir_ls` (e.g. `dir_ls(...) %>% dir_select_copy()`) or have the same method signature as `dir_ls`.

**Comment by gaborcsardi** [comment]
This is more of a question than an issue with fs, I think, so it is better suited to a forum like https://community.rstudio.com/

One solution would be to list the files you want to keep with `dir_ls(pattern = ...)` and then copy the listed files only.

**Comment by orgadish** [comment]
This was meant to be a feature request for a single function that does this.

It can be accomplished with several fs steps (below), but I think it's a common enough use case that would benefit from a single function that could also be optimized.

My current method is something like:
```r
copy_tree <- function(path, start, new_start, overwrite=FALSE) {
  rel_path <- fs::path_rel(path, start)

 new_path <- fs::path(new_start, path)

  fs::dir_create(fs::path_dir(new_path))
  fs::file_copy(path, new_path, overwrite = overwrite)
}
```

I think it would also benefit from the ability to skip files that already exist, but I will file that feature request on `file_copy` separately.
