### ISSUE TITLE
error from path_rel()

### ISSUE THREAD

**Issue by vorpalvorpal** [r-lib/fs#408]
Hi,

I was using `fs::path_rel` inside my own function. I gave my function multiple paths as an argument which was then handed on to `path_rel` as multiple paths for its start argument. Obviously this created an error:

```
Error in if (is.na(start)) { : the condition has length > 1
```

This was quite an uninformative error, and it took quite a bit of digging around to figure out the error was from `path_rel`. Would it be possible to add a check for `length(start) == 1` (or something similar) and then display a more useful error?

**Comment by IndrajeetPatil** [comment]
Minimal reprex:

``` r
fs::path_rel(c("a", "a/b", "a/b/c"), c("a/b", "a"))
#> Error in if (is.na(start)) {: the condition has length > 1
```

<sup>Created on 2024-05-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
