### ISSUE TITLE
Is dropping of attributes by fs::path intentional?

### ISSUE THREAD

**Issue by jan-glx** [r-lib/fs#426]
`fs` operations like `fs::path` or `fs::path_rel` remove attributes from paths, in particular names.
Is this intended / Are attributes other than `"class"` considered untidy?
This seems to be in contrast to the advice given in [R-internals](
https://cran.r-project.org/doc/manuals/r-release/R-ints.html#Attributes). 

Full example:
``` r
my_paths <- c("A" = "/home/jan/a", "B" = "/home/jan/b")
attributes(my_paths)$note <- "remember me"

my_paths_rel <- fs::path_rel(my_paths, start = "/home/jan")

str(my_paths_rel) # current behaviour
#>  'fs_path' chr [1:2] "a" "b"


collapse::copyAttrib(my_paths_rel, from = my_paths)
#>   A   B 
#> "a" "b" 
#> attr(,"note")
#> [1] "remember me"
class(my_paths_rel) <- c("fs_path", class(my_paths_rel))
str(my_paths_rel) # behaviour expected by me
#>  'fs_path' Named chr [1:2] "a" "b"
#>  - attr(*, "names")= chr [1:2] "A" "B"
#>  - attr(*, "note")= chr "remember me"
```

<sup>Created on 2023-07-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by gaborcsardi** [comment]
Yeah, attributes on vectors are quite easy to lose, in particular, fs calls `as.character()` on the input, and that already drops (some of?) the attributes afaict. So it would be pretty hard to preserve them in fs.
