### ISSUE TITLE
split off the plotting piece of dir_tree()?

### ISSUE THREAD

**Issue by MichaelChirico** [r-lib/fs#433]
I'm looking for a nice way to display graph and/or tree structures in the terminal for when regular plots are not available, and `dir_tree()` is the first thing I came across that seems to do the job reasonably well (googling has proven a bit hard, though, as most searches seem to think I want the `text()` method for some other object).

Would it make sense to split off the plotting part of `dir_tree()` into a separate function to abstract away its dependence on files? Or maybe to put that part into a separate package?

I could hack together a way to fake the directory structure in `tempdir()` but that seems quite goldbergian.

**Comment by gaborcsardi** [comment]
There is a generic tree drawing function in cli: `cli::tree()`.
