### ISSUE TITLE
Support for `path("http://", ...)`

### ISSUE THREAD

**Issue by dlksmc** [r-lib/fs#439]
## Description

`fs` is a wonderful package--I use it in almost every script I write!  Thank you to everyone who contributes to it!

Is it a bug that `path` doesn't seem to work with `http://`, or is that by design?

## Steps to Reproduce

`fs::path("https://github.com/r-lib/fs", "issues")` returns 'https:/github.com/r-lib/fs/issues', stripping off the second slash.

## Expected Behavior

I expected a return value of 'https://github.com/r-lib/fs/issues', similar to the output of `file.path("https://github.com/r-lib/fs", "issues")` from base R.

**Comment by gaborcsardi** [comment]
It is by design, supporting URLs would complicate this function considerably, I think for URL you can use `paste()` or some URL specific function from another package. Changing this would also be a breaking change, so even if we wanted to support URLs, we cannot do it at this point.
