### ISSUE TITLE
`dir_copy` removes files in target directory

### ISSUE THREAD

**Issue by mllg** [r-lib/fs#51]
```r
dir_create(c("a", "b"))
file_create(path("a", "foo"))
file_create(path("b", "bar"))
dir_copy("a", "b", overwrite = TRUE)
dir_ls("b") # file bar is deleted
```

I don't know if this is intended, but it is not clearly documented and could lead to unwanted data loss. :worried:

**Comment by jimhester** [comment]
Yes this is not right, it should have the same semantics as `cp a b` for this, so `a/` would be copied into `b/a`.
