### ISSUE TITLE
file hash

### ISSUE THREAD

**Issue by jonocarroll** [r-lib/fs#52]
Would it be worthwhile to have a file hash as a column in `file_info()`? I often want to be able to compare either different versions of the same filename or different filenames but the same file.

This could be as simple as 

```
res$hash <- tools::md5sum(path)
```

or via some other mechanism.

**Comment by mllg** [comment]
MD5 is an expensive operation, this would make `file_info()` useless for larger directories (e.g., `md5sum` requires ~10s on CRAN's src/contrib directory on my system).

**Comment by jimhester** [comment]
Yes, this is not going to happen for `file_info()`. If you want to do this often I would suggest you define a wrapper function around `file_info()` that adds this column.

Btw if speed is a concern you might want to use something like `digest::digest(algo = "xxhash64")`
