### ISSUE TITLE
`path()` silently ignores zero-length input

### ISSUE THREAD

**Issue by mllg** [r-lib/fs#54]
This is probably just a matter of taste, but `path()` behaves differently compared to `file.path()` for 0-length input:
```r
file.path("a", character(0)) # -> character(0)
fs::path("a", character(0)) # -> "a"
```
If the second part is the result of some kind of filtering (`is_dir()`, `file.mtime()`, ...), you might end up accidentally deleting the base directory instead of only those candidates for which the filter criterion holds (which is exactly how I stumbled about this).

**Comment by jimhester** [comment]
I agree with you, I actually ran into this when I was rewriting `dir_copy()` as well. Should now work similarly to `file.path()` for this case.
