### ISSUE TITLE
random colors?!

### ISSUE THREAD

**Issue by randomgambit** [r-lib/fs#55]
Hello

Thanks for creating this package, I really like being able to explore my folders without resorting to the command line. 

However, I noticed that using `fs_ls` would show my files/directories with some random colors, with some files names shown in blue, others in black, other highlighted in green. Is that normal?

Thanks!

**Comment by jimhester** [comment]
It is not random, it is colored by file type, see http://fs.r-lib.org/reference/fs_path.html for how to customize it or turn it off.

**Comment by randomgambit** [comment]
well I have different colors for the same types of files. for instance these are two parquet files that have a different color:

/hpc/mypath/parquet_201511
/hpc/mypath/parquet_201512

**Comment by jimhester** [comment]
Also this is shown in the example image and mentioned in the [README](https://github.com/r-lib/fs#tidy-paths) and also explicitly mentioned in the [introductory blog post](https://www.tidyverse.org/articles/2018/01/fs-1.0.0/#tidy-paths)

**Comment by jimhester** [comment]
Then they have different permissions

**Comment by randomgambit** [comment]
indeed, you are right. Thanks again!
