### ISSUE TITLE
Windows home directory

### ISSUE THREAD

**Issue by kevinushey** [r-lib/fs#57]
On Windows, R sets the `R_USER` environment variable to the user's `Documents` folder, and R uses this as the 'home' directory (for e.g. tilde-path expansion). This implies that by default:

```R
> path.expand("~")
[1] "C:/Users/kevin/Documents"
> fs::path_home()
C:/Users/kevin/Documents
> Sys.getenv("R_USER")
[1] "C:/Users/kevin/Documents"
```

This seems a bit counter-intuitive as this folder is not really the user's "home" directory. The associated logic R uses to choose this path is here and below:

https://github.com/wch/r-source/blob/9bec1ec8b544e077cbb35f190ad9c62a99876190/src/gnuwin32/shext.c#L26-L45

Would it make sense for `fs` to enforce the 'real' home directory (as set with e.g. `%USERPROFILE%` or `%HOMEDRIVE%%HOMEPATH%`)?

**Comment by jimhester** [comment]
We deliberately used R's definition and implementation path expansion of the user home directory to avoid breaking compatibility with the base R definition.

On my Windows VM both `R_HOME` and `HOME` are set when R is run to `C:/Users/username/Documents`. However `%HOME%` is not set outside of R.

I think the main problem with changing the definition from what R expects is that if we did so then `~/.Rprofile` will no longer point to the location R expects the `~/.RProfile` to be in.

I guess we would have that same issue now, that non R programs (like git) would use the more standard definition of `%USERPROFILE%` / `%HOMEDRIVE%%HOMEPATH%%`.

**Comment by kevinushey** [comment]
Any thoughts about whether it would be worth breaking backwards-compatibility with R, so the Windows home directory really did point to `%USERPROFILE%`?
