### ISSUE TITLE
How should dir_move (and friends) handle files?

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#6]
i.e. in general, what should we do when a function could work the same for files and directories?

**Comment by jimhester** [comment]
I kind of feel like `dir_move()` should error if `path` is not a directory. But maybe `file_move()` should work on both directories and files?

**Comment by hadley** [comment]
Yeah, maybe we should just eliminate all `dir_x` functions that are just duplicates of `file_x` functions and instead make it clear that directories are a special case of files.
