### ISSUE TITLE
`path_home()` produces HOME path with tilde appended w/R installed from sources

### ISSUE THREAD

**Issue by kevinushey** [r-lib/fs#60]
E.g. I see:

```R
> path.expand("~")
[1] "/Users/kevin/~"
> path.expand("~/")
[1] "/Users/kevin/"
> fs::path_home()
/Users/kevin/~
```

This is almost certainly a consequence of how I've compiled R but it would be nice to handle this edge case since R's handling of `~` expansion depends on whether `readline` is used (IIUC)

**Comment by jimhester** [comment]
We simply rely on R's `R_ExpandFilename` function to expand the home, so `fs::path_expand("~/")` should return the same as base R.

https://github.com/r-lib/fs/blob/63d3453d83cf1bc54dc46b190d4f6256fc763904/src/path.cc#L87

I guess this implies that `path_home()` should expand "~/" rather than "~"
