### ISSUE TITLE
file_copy fails to copy network drive hosted files

### ISSUE THREAD

**Issue by imanuelcostigan** [r-lib/fs#62]
Copying files from a network drive to a local directory using `fs::file_copy()` does not work. Instead we see: 

> Error: [EPERM] Failed to copy '//serverurl/file.csv' to 'C:/Users/XYZ/AppData/Local/Temp/RtmpU7FY3j': operation not permitted

`base::file.copy()` works fine.

**Comment by jimhester** [comment]
This doesn't have to do with the network drive, you are trying to copy a file to a directory, and right now `file_copy()` only copies files to new file locations, not directories.

```r
file_copy("//serverurl/file.csv", path(tempdir(), "file.csv"))
```

Should work.

**Comment by imanuelcostigan** [comment]
thanks. sort of implicit in the help page, but given the behaviour of base::file.copy(), it might be worth highlighting this.
