### ISSUE TITLE
How to handle missing values?

### ISSUE THREAD

**Issue by jdblischak** [r-lib/fs#64]
Following up on #63, the functions vary in how they handle missing values. Some return `NA`, some return `FALSE`, and others throw an error.

## Proposal

I propose the following functionality for handling missing values:

* `path_*` functions return `NA`
* `is_*` functions return `FALSE`
* All other functions throw an error

## Current status

Here is the current status of fs functions:

* Return `NA`: path_abs, path_ext_remove, path_filter, path_norm, path_split, path_tidy
* Return `FALSE`: is_absolute_path
* Throw error: dir_copy, dir_create, dir_delete, dir_exists, dir_info, dir_ls, dir_map, dir_walk, file_access, file_chmod, file_chown, file_copy, file_create, file_delete, file_exists, file_info, file_move, file_show, file_temp_push, is_dir, is_file, is_link, link_copy, link_create, link_delete, link_exists, link_path, path_common, path_dir, path_expand, path_ext, path_ext_set, path_ext<-, path_file, path_real, path_rel

Here is the code I used to generate these lists:

```
library("fs")
funs <- ls(name = "package:fs")
result <- vector(mode = "list", length = length(funs))
names(result) <- funs
for (i in seq_along(funs)) {
  exec <- get(funs[i])
  arguments <- names(formals(exec))
  if (length(arguments) > 0 && arguments[1] == "path") {
    result[[i]] <- tryCatch(exec(NA), error = function(e) "error")
  } else {
    result[[i]] <- "No path argument"
  }
}
# Return NA
cat(names(result)[sapply(result, is.na)], sep = ", ")
# Return FALSE
cat(names(result)[sapply(result, function(x) x == "FALSE" && !is.na(x))], sep = ", ")
# Throw error
cat(names(result)[sapply(result, function(x) x == "error" && !is.na(x))], sep = ", ")
```

**Comment by jimhester** [comment]
Thanks, that script was very helpful to see what functions needed to change. I agree with your thoughts on how the functions should work and things should be much more consistent in regards to missing values now.

**Comment by jdblischak** [comment]
Thanks, Jim! I tested the new functionality, and it handles the missing values well.

One thing I noticed though is that it only accepts missing character values. If a user passes the standard logical NA (like I did in my script above), the behavior is variable (and the error message is terse):

```
# missing character value
> path_abs(NA_character_)
NA
> path_rel(NA_character_)
NA
# Missing logical value
> path_abs(NA)
NA
> path_rel(NA)
Error in enc2utf8(path) : argumemt is not a character vector
```

Would it be possible to either convert a logical NA to a character NA or alternatively to fail with an informative error message? Perhaps something like the check below:

```
if (length(path) == 1 && is.na(path) && is.logical(path)) {
  path <- NA_character_
}
```

**Comment by jimhester** [comment]
I don't think it is worth special casing this, in practice `NA` values will always be coerced to character vectors as long as there is at least one character value, so should not come up except in the case of passing a 1 element logical NA, which should not happen if you are using type stable functions upstream of fs.

**Comment by jdblischak** [comment]
Sounds reasonable to me. Now to go make my functions type stable...

**Comment by jimhester** [comment]
In general using `purrr::map_chr()` / `vapply(x, fun, character(1))` instead of `sapply()` or `unlist(lapply())` will go a long way towards ensuring this.

**Comment by jdblischak** [comment]
Thanks for the advice, @jimhester! My current issue is actually much more mundane than this. I have some functions that explicitly return `NA` when they should be returning `NA_character_`.
