### ISSUE TITLE
dir_ls() fails inside rmarkdown chunk

### ISSUE THREAD

**Issue by jzadra** [r-lib/fs#65]
Using all fs functions, I set a path using 
`filepath <- path("mypath/whatever")`

then get the full path to all files using:
`files <– dir_ls(filepath, glob = "*.xlsx")`

Run in the console, this works, but within an Rmarkdown chunk, filepath gets a value, but dir_ls returns a 0 row character vector.

**Comment by cderv** [comment]
It may help to know that an Rmarkdown file is executed by default in the document directory and not the working directory. You did not precise it but it could be related if your Rmd file is not in the right place compare to the path you are contructing.

In last version of RStudio, there is an option to change that directly in the IDE. 
![image](https://user-images.githubusercontent.com/6791940/35995215-007d6482-0d13-11e8-9de4-67e3af13ef14.png)

You can also use a `knitr` option `knitr::opts_knit$get('root.dir')` to change the root dir where code chunks are executed.  (using `knitr::opts_knit$set`

Not sure it is the issue, but could definitely be related. 

Hope it helps.

**Comment by jzadra** [comment]
Sorry, I didn't update this fast enough. I just finished some troubleshooting with Yihui and we determined that the cause of the problem is that the files are coming through google drive file stream.  It appears to happen with baseR file functions too, so it's not an `fs` issue but rather a combination of `rmarkdown` and google drive.
