### ISSUE TITLE
is regex working?

### ISSUE THREAD

**Issue by randomgambit** [r-lib/fs#66]
Hi Jim,

Sorry for the noob question, but I am trying to filter out files based on a simple regex query

`dir_info( regexp = "P://*.csv") `

always returns an empty dataframe. Am I getting the syntax wrong here?

Thanks!

**Comment by jimhester** [comment]
Yes, you are using a file glob, not a regex, you can use `dir_info(glob = "P://*.csv")` to use globbing.

See [Regular expressions VS globbing](https://askubuntu.com/a/714520/379717) for details of the difference.

The equivalent regular expression would be 

`dir_info(regexp = "P://.*\\.csv")`

Look at the documentation for these functions I see the distinction is muddied, will fix it thanks!

**Comment by randomgambit** [comment]
thanks Jim!
