### ISSUE TITLE
using fs with purrr

### ISSUE THREAD

**Issue by randomgambit** [r-lib/fs#67]
Hi Jim,

I am tring to use `fs` with purrr and ran into some difficulties. What is wrong here? My understanding is that this should work

```
> dir_info( "P://test") %>% 
+   filter(size > 0) %>% 
+   select(path) %>% 
+   purrr:::map(. , fs::path_file(.))
Error in basename(path) : a character vector argument expected
```

**Comment by jimhester** [comment]
`dplyr::select` returns a `data.frame`, not a `vector`.

I would use remove the select call and use`purrr::pluck("path") %>% path_file()`, or `summarise(path = path_file(path))[[1]]` If I wanted a vector of filenames in this case.

Unless you are sure there is a bug in the **fs** package I would encourage you to ask similar questions at https://community.rstudio.com/c/tidyverse.
