### ISSUE TITLE
Support to integrate HDFS filesystem

### ISSUE THREAD

**Issue by harryprince** [r-lib/fs#68]

**Comment by jimhester** [comment]
I am not sure what this would mean, and it is likely beyond the scope of this package

**Comment by harryprince** [comment]
I like `fs` package, however, I found which can only manipulate the local file system instead of Hadoop file system.

I wish `fs` command can implement in HDFS, and the grammar maybe not different.

**Comment by jimhester** [comment]
I think it is unlikely we will have resources to work on this, so am going to close it unless someone from the community expresses interest in working on the problem.

**Comment by awwsmm** [comment]
Hi @jimhester , I might be interested in working on this for `fs`. The Hadoop Distributed File System (HDFS) can only be queried via R's `system()` command -- I think -- but the output is easily parseable:

```
$ hdfs dfs -ls /
Found 8 items
drwxr-xr-x   - Andrew.Watson supergroup          0 2019-09-17 14:58 /LL
-rw-r--r--   1 Andrew.Watson supergroup       3952 2019-07-18 09:40 /README.md
drwxr-xr-x   - Andrew.Watson supergroup          0 2019-09-25 13:31 /a test
drwxr-xr-x   - Andrew.Watson supergroup          0 2019-07-24 10:16 /test
-rw-r--r--   1 Andrew.Watson supergroup         26 2019-07-24 09:30 /tiny.csv
-rw-r--r--   1 Andrew.Watson supergroup         43 2019-07-24 13:42 /tiny2.csv
-rw-r--r--   1 Andrew.Watson supergroup         42 2019-09-10 09:20 /tiny2b.csv
-rw-r--r--   1 Andrew.Watson supergroup         71 2019-09-10 09:19 /tiny3.csv
```

I've written scripts which do almost exactly what @harryprince is asking for and might be able to submit a PR if I'm pointed in the right direction.

**Comment by jimhester** [comment]
@awwsmm If you did want to tackle this I think it would be best done in a separate package that maybe builds on fs rather than being part of fs itself.

**Comment by awwsmm** [comment]
Why do you think that?

---

Side note: It looks like, [at the lowest level](https://github.com/r-lib/fs/blob/6ee3322076bd2cb6b9cacd0b52ac1717b11996e4/src/libuv/src/unix/os390-syscalls.h), `fs` is using [`scandir()`](http://man7.org/linux/man-pages/man3/scandir.3.html) to walk the file tree.

**Comment by jimhester** [comment]
Because HDFS has nothing really to do with a normal on-disk file system? Basically none of the code used in fs would overlap with that needed to access HDFS.
