### ISSUE TITLE
Convert user/group ids to strings

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#7]
As input (e.g. `file_chown()`) and output (e.g. `file_info()`)

**Comment by jimhester** [comment]
libuv has http://docs.libuv.org/en/v1.x/misc.html?highlight=passwd#c.uv_os_get_passwd, to query the passwd file for the user names, but AFAIK it does not have an equivalent for groups.

There are standard library functions for this on POSIX systems, but not sure how it will work on windows.
