### ISSUE TITLE
dir_copy fails to create directory

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#70]
``` r
library(fs)

base <- path_temp()

abc <- path(base, "a", "b", "c")
dir_create(abc)
file_create(path(abc, "test.txt"))

def <- path(base, "d", "e", "f")
dir_create(def)
dir_copy(abc, def)
#> Error: [ENOENT] Failed to copy '/tmp/RtmpIs2eFt/a/b/c/test.txt' to '/tmp/RtmpIs2eFt/d/e/f/tmp/RtmpIs2eFt/a/b/c/test.txt': no such file or directory
```

Created on 2018-02-16 by the [reprex package
(0.1.1.9000)](https://cran.r-project.org/package=reprex).

I think the primary problem is that `dir_copy()` is including the full path to the input files, rather than the relative path

**Comment by jimhester** [comment]
This is fixed in the devel version of fs, you must be using the CRAN version

**Comment by jimhester** [comment]
Actually this was fixed in fs 1.1.0 https://github.com/r-lib/fs/blob/master/NEWS.md#bugfixes-1

**Comment by hadley** [comment]
Doh, somehow I missed that fs 1.1.0 existed 😢

**Comment by hadley** [comment]
Oh this is the version that doesn't have a CRAN binary. Now I remember
