### ISSUE TITLE
Function for path to current file

### ISSUE THREAD

**Issue by wch** [r-lib/fs#76]
It would be handy to have a function that returns the path to the current file, similar to Python's `__file__`. This would be useful when R is used a general-purpose scripting language in a project that isn't necessarily centered around R.

Note that rprojroot has the `thisfile` function, but to me it seems like it's a better fit for fs.

**Comment by slee981** [comment]
Bumping this as I just came across it. 

+1 for me as well, would love this feature. @jimhester any estimation of how much work this would take?

**Comment by gaborcsardi** [comment]
Unfortunately this is very hard to implement properly, and there is now a package (whereami) that implements it, so I am going to close it.
