### ISSUE TITLE
option force and silent to link_create

### ISSUE THREAD

**Issue by statquant** [r-lib/fs#77]
Hello, many thanks for this nice package.
Would it be useful (my view is yes) to add to `link_create` an option 
- _force_ that would essentially be link `ln -sf new old`
- _silent_ that would allow to fail silently if the link already exists

Regards

**Comment by statquant** [comment]
Thanks for the lightening fast implementation. 
Do I get from this that silent is default and that you do not think you want to add `force`  ?

**Comment by jimhester** [comment]
Yes that is right
