### ISSUE TITLE
Add recursive argument to dir_delete() and link_delete()

### ISSUE THREAD

**Issue by elben10** [r-lib/fs#78]
It would be nice if `dir_delete()` and `link_delete()` had an recursive argument as [unlink()](https://www.rdocumentation.org/packages/base/versions/3.4.3/topics/unlink) has. Such that a non-empty directory also can be deleted without having to delete the contents of the directory.

**Comment by jimhester** [comment]
`dir_delete()` already does this automatically, there is no need for an argument.

**Comment by elben10** [comment]
I receive the following error message. I cannot figure out if it is connected to my Mac settings or the package?

```r
fs::dir_delete("~/desktop/dlib-19.9 2")
Error: [ENOTEMPTY] Failed to remove '/Users/jakobelben/desktop/dlib-19.9 2/tools/python/test': directory not empty
```

**Comment by jimhester** [comment]
I would have to know more about what your files in those directories look like, likely they were created as a root user, so you do not have permissions to remove them without sudo.

try `fs::dir_info("~/desktop/dlib-19.9 2")` and look at the permission and user fields.

**Comment by elben10** [comment]
Yes, didn't have the permission.
