### ISSUE TITLE
Should dir_create() etc take ...?

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#80]
And pass onto `path()` for you.

**Comment by jimhester** [comment]
Doing this would mean you would have to specify any additional arguments by name, and you can always use `path()` explicitly if needed. It would make creating a new file/directory from a user supplied variable with an  extension (and / or directory) easier though. Maybe it is a good tradeoff...

```r
x <- c("foo", "bar")
file_create(dir_temp(), x, ext = ".txt")
```
