### ISSUE TITLE
FR: dir_tree()

### ISSUE THREAD

**Issue by krlmlr** [r-lib/fs#82]
with similar output as the `tree` command, with colors and everything.

**Comment by mdancho84** [comment]
I second this. Was actually just getting ready to create an issue requesting this feature.

**Comment by jennybc** [comment]
If anyone ever pursued this, here's a gist where I noodled around with something years ago:

https://gist.github.com/jennybc/2bf1dbe6eb1f261dfe60

**Comment by jimhester** [comment]
Well I ended up doing this with colors and everything, because once I had it working it wasn't much more effort to do it nicely.

![Screen Shot 2019-03-18 at 4 54 34 PM](https://user-images.githubusercontent.com/205275/54563056-a3022d00-499e-11e9-917c-31cf1fce2141.png)
