### ISSUE TITLE
OS X binaries not available from CRAN

### ISSUE THREAD

**Issue by krlmlr** [r-lib/fs#84]
The examples segfault at `file_exists()`: https://www.r-project.org/nosvn/R.check/r-release-osx-x86_64/fs-00check.html.

**Comment by jimhester** [comment]
Yes, I am aware; it seems to occur only on the CRAN build machines and so far has been impossible for anyone to reproduce, which makes it kind of difficult to fix.

**Comment by jimhester** [comment]
Actually looks like Simon has tracked down the issue https://www.mail-archive.com/r-sig-mac@r-project.org/msg04664.html, so I can now fix this.

**Comment by krlmlr** [comment]
Thanks for the quick fix!
