### ISSUE TITLE
Clarify file_move vs. file_rename

### ISSUE THREAD

**Issue by hadley** [r-lib/fs#9]
```R
file_move("x.txt", "y")
file_rename("x.txt", "y.txt")
```

`file_rename(x, y)` must have `length(x) == length(y)`, where in `file_move()` `length(y)` could also be one (if you want to move many files into the same directory)

`file_rename()` needs `overwrite` argument, to check if any files exist (and are not directories). `file_move()` needs to check that the RHS is a directory.

**Comment by jimhester** [comment]
Ok so right now as of https://github.com/r-lib/fs/commit/0cdf8ca7fbdf3680bcfcd00e9ecd6a25f5ba0e82 `file_move()` does both things, although it does not check for existing files.

**Comment by hadley** [comment]
Maybe doing it all in once function is ok.

**Comment by jimhester** [comment]
I think we have decided to just use `file_move()` for everything.
