### ISSUE TITLE
path_ext_set(): behaviour varies by presence/absence of a parent directory

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#92]
``` r
fs::path_ext_set(".rels", "XML")
#> .rels.XML
fs::path_ext_set("_rels/.rels", "XML")
#> _rels.XML
## I expected/wanted "_rels/.rels.XML"
```

Created on 2018-03-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

I need to copy some XML files that lack the extension to filenames that have the extension, for favorable treatment in a web browser. Above is an example where my attempt to add the extension ultimately results in me making the copy with the wrong name and in the parent of the intended directory.

Can I simply not use `path_ext_set()` in this case?

**Comment by jimhester** [comment]
Ok this should now be fixed, the regex was not handling hidden files in directories correctly.
