### ISSUE TITLE
path_ext_set(): what if I don't want to replace?

### ISSUE THREAD

**Issue by jennybc** [r-lib/fs#93]
I was hoping to use `path_ext_set()` to set, vs. replace, the file extension. Is this just an unusual need and I should use `paste0()` in this case?

``` r
fs::path_ext_set("workbook.xml.rels", "XML")
#> workbook.xml.XML
## I was hoping for "workbook.xml.rels.XML"
```

Created on 2018-03-21 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by jimhester** [comment]
This would work fine if there was only one extension, but there are three in this case. Yes you will just need to use `paste0()`.
